#! /usr/bin/perl
use strict;
use FindBin;
use lib "$FindBin::Bin/.";
use GraphJG::SimilarityJG;


my %templateGraphs = {};

my $ChacoboBodyPartPfxVerbTrans_7-9 = Graph->new(multiedged => 1);
$ChacoboBodyPartPfxVerbTrans_7-9->set_graph_attribute("name", "ChacoboBodyPartPfxVerbTrans_7-9");
$ChacoboBodyPartPfxVerbTrans_7-9->add_edge_by_id("desmeme", "arch", "FOUNDATION");
$ChacoboBodyPartPfxVerbTrans_7-9->add_edge_by_id("arch", "component1", "RIGHT_VOUSSOIR");
$ChacoboBodyPartPfxVerbTrans_7-9->add_edge_by_id("component1", "unstable1", "STABILITY");
$ChacoboBodyPartPfxVerbTrans_7-9->add_edge_by_id("unstable1", "component2", "ASSOCIATE");
$ChacoboBodyPartPfxVerbTrans_7-9->add_edge_by_id("component2", "elastic1", "ELASTICITY");
$ChacoboBodyPartPfxVerbTrans_7-9->add_edge_by_id("elastic1", "MAXIMUM1-1", "MAXIMUM");
$ChacoboBodyPartPfxVerbTrans_7-9->add_edge_by_id("elastic1", "MINIMUM0-1", "MINIMUM");
$ChacoboBodyPartPfxVerbTrans_7-9->add_edge_by_id("component2", "open1", "FILLEDNESS");
$ChacoboBodyPartPfxVerbTrans_7-9->add_edge_by_id("open1", "coherent1", "COHERENCE");
$ChacoboBodyPartPfxVerbTrans_7-9->add_edge_by_id("component2", "stable1", "STABILITY");
$ChacoboBodyPartPfxVerbTrans_7-9->add_edge_by_id("unstable1", "left", "ASSOCIATE_POSITION");
$ChacoboBodyPartPfxVerbTrans_7-9->add_edge_by_id("component1", "open2", "FILLEDNESS");
$ChacoboBodyPartPfxVerbTrans_7-9->add_edge_by_id("open2", "coherent2", "COHERENCE");
$ChacoboBodyPartPfxVerbTrans_7-9->add_edge_by_id("component1", "elastic2", "ELASTICITY");
$ChacoboBodyPartPfxVerbTrans_7-9->add_edge_by_id("elastic2", "MAXIMUM1-2", "MAXIMUM");
$ChacoboBodyPartPfxVerbTrans_7-9->add_edge_by_id("elastic2", "MINIMUM0-2", "MINIMUM");
$ChacoboBodyPartPfxVerbTrans_7-9->add_edge_by_id("arch", "component1", "RIGHT_SUPPORT");
$ChacoboBodyPartPfxVerbTrans_7-9->add_edge_by_id("arch", "component3", "KEYSTONE");
$ChacoboBodyPartPfxVerbTrans_7-9->add_edge_by_id("component3", "open3", "FILLEDNESS");
$ChacoboBodyPartPfxVerbTrans_7-9->add_edge_by_id("open3", "coherent3", "COHERENCE");
$ChacoboBodyPartPfxVerbTrans_7-9->add_edge_by_id("component3", "inelastic1", "ELASTICITY");
$ChacoboBodyPartPfxVerbTrans_7-9->add_edge_by_id("inelastic1", "COUNT1-1", "COUNT");
$ChacoboBodyPartPfxVerbTrans_7-9->add_edge_by_id("component3", "stable2", "STABILITY");
$ChacoboBodyPartPfxVerbTrans_7-9->add_edge_by_id("arch", "component2", "LEFT_VOUSSOIR");
$ChacoboBodyPartPfxVerbTrans_7-9->add_edge_by_id("arch", "component2", "LEFT_SUPPORT");
$ChacoboBodyPartPfxVerbTrans_7-9->add_edge_by_id("desmeme", "notViolable", "VIOLABILITY");
$ChacoboBodyPartPfxVerbTrans_7-9->add_edge_by_id("desmeme", "order", "STRICTURE");
$ChacoboBodyPartPfxVerbTrans_7-9->add_edge_by_id("order", "simple", "RELATIONS");
$ChacoboBodyPartPfxVerbTrans_7-9->add_edge_by_id("order", "COUNT3-1", "COUNT");
$ChacoboBodyPartPfxVerbTrans_7-9->add_edge_by_id("order", "morphologicalConstituent", "CONSTITUENT");
$ChacoboBodyPartPfxVerbTrans_7-9->add_edge_by_id("desmeme", "constructionalConditioning", "CONDITIONING");
$templateGraphs{ChacoboBodyPartPfxVerbTrans_7-9} = $ChacoboBodyPartPfxVerbTrans_7-9;

my $ChacoboNonInterruptableBySimple_7-11 = Graph->new(multiedged => 1);
$ChacoboNonInterruptableBySimple_7-11->set_graph_attribute("name", "ChacoboNonInterruptableBySimple_7-11");
$ChacoboNonInterruptableBySimple_7-11->add_edge_by_id("desmeme", "constructionalConditioning", "CONDITIONING");
$ChacoboNonInterruptableBySimple_7-11->add_edge_by_id("desmeme", "arch", "FOUNDATION");
$ChacoboNonInterruptableBySimple_7-11->add_edge_by_id("arch", "component1", "RIGHT_SUPPORT");
$ChacoboNonInterruptableBySimple_7-11->add_edge_by_id("component1", "elastic1", "ELASTICITY");
$ChacoboNonInterruptableBySimple_7-11->add_edge_by_id("elastic1", "MINIMUM0-1", "MINIMUM");
$ChacoboNonInterruptableBySimple_7-11->add_edge_by_id("elastic1", "MAXIMUM2-1", "MAXIMUM");
$ChacoboNonInterruptableBySimple_7-11->add_edge_by_id("component1", "open1", "FILLEDNESS");
$ChacoboNonInterruptableBySimple_7-11->add_edge_by_id("open1", "coherent1", "COHERENCE");
$ChacoboNonInterruptableBySimple_7-11->add_edge_by_id("component1", "stable1", "STABILITY");
$ChacoboNonInterruptableBySimple_7-11->add_edge_by_id("arch", "component2", "RIGHT_VOUSSOIR");
$ChacoboNonInterruptableBySimple_7-11->add_edge_by_id("component2", "unstable1", "STABILITY");
$ChacoboNonInterruptableBySimple_7-11->add_edge_by_id("unstable1", "component3", "ASSOCIATE");
$ChacoboNonInterruptableBySimple_7-11->add_edge_by_id("component3", "elastic2", "ELASTICITY");
$ChacoboNonInterruptableBySimple_7-11->add_edge_by_id("elastic2", "MAXIMUM1-1", "MAXIMUM");
$ChacoboNonInterruptableBySimple_7-11->add_edge_by_id("elastic2", "MINIMUM0-2", "MINIMUM");
$ChacoboNonInterruptableBySimple_7-11->add_edge_by_id("component3", "open2", "FILLEDNESS");
$ChacoboNonInterruptableBySimple_7-11->add_edge_by_id("open2", "coherent2", "COHERENCE");
$ChacoboNonInterruptableBySimple_7-11->add_edge_by_id("component3", "stable2", "STABILITY");
$ChacoboNonInterruptableBySimple_7-11->add_edge_by_id("unstable1", "left", "ASSOCIATE_POSITION");
$ChacoboNonInterruptableBySimple_7-11->add_edge_by_id("component2", "open3", "FILLEDNESS");
$ChacoboNonInterruptableBySimple_7-11->add_edge_by_id("open3", "coherent3", "COHERENCE");
$ChacoboNonInterruptableBySimple_7-11->add_edge_by_id("component2", "elastic3", "ELASTICITY");
$ChacoboNonInterruptableBySimple_7-11->add_edge_by_id("elastic3", "MAXIMUM1-2", "MAXIMUM");
$ChacoboNonInterruptableBySimple_7-11->add_edge_by_id("elastic3", "MINIMUM0-3", "MINIMUM");
$ChacoboNonInterruptableBySimple_7-11->add_edge_by_id("arch", "restkomponentenSet", "RESTKOMPONENTEN");
$ChacoboNonInterruptableBySimple_7-11->add_edge_by_id("restkomponentenSet", "component4", "RESTKOMPONENTE");
$ChacoboNonInterruptableBySimple_7-11->add_edge_by_id("component4", "open4", "FILLEDNESS");
$ChacoboNonInterruptableBySimple_7-11->add_edge_by_id("open4", "coherent4", "COHERENCE");
$ChacoboNonInterruptableBySimple_7-11->add_edge_by_id("component4", "elastic4", "ELASTICITY");
$ChacoboNonInterruptableBySimple_7-11->add_edge_by_id("elastic4", "MAXIMUM1-3", "MAXIMUM");
$ChacoboNonInterruptableBySimple_7-11->add_edge_by_id("elastic4", "MINIMUM0-4", "MINIMUM");
$ChacoboNonInterruptableBySimple_7-11->add_edge_by_id("component4", "stable3", "STABILITY");
$ChacoboNonInterruptableBySimple_7-11->add_edge_by_id("arch", "component3", "LEFT_SUPPORT");
$ChacoboNonInterruptableBySimple_7-11->add_edge_by_id("arch", "component3", "LEFT_VOUSSOIR");
$ChacoboNonInterruptableBySimple_7-11->add_edge_by_id("arch", "component5", "KEYSTONE");
$ChacoboNonInterruptableBySimple_7-11->add_edge_by_id("component5", "open5", "FILLEDNESS");
$ChacoboNonInterruptableBySimple_7-11->add_edge_by_id("open5", "coherent5", "COHERENCE");
$ChacoboNonInterruptableBySimple_7-11->add_edge_by_id("component5", "inelastic1", "ELASTICITY");
$ChacoboNonInterruptableBySimple_7-11->add_edge_by_id("inelastic1", "COUNT1-1", "COUNT");
$ChacoboNonInterruptableBySimple_7-11->add_edge_by_id("component5", "stable4", "STABILITY");
$ChacoboNonInterruptableBySimple_7-11->add_edge_by_id("desmeme", "order", "STRICTURE");
$ChacoboNonInterruptableBySimple_7-11->add_edge_by_id("order", "simple", "RELATIONS");
$ChacoboNonInterruptableBySimple_7-11->add_edge_by_id("order", "COUNT5-1", "COUNT");
$ChacoboNonInterruptableBySimple_7-11->add_edge_by_id("order", "morphologicalConstituent", "CONSTITUENT");
$ChacoboNonInterruptableBySimple_7-11->add_edge_by_id("desmeme", "notViolable", "VIOLABILITY");
$templateGraphs{ChacoboNonInterruptableBySimple_7-11} = $ChacoboNonInterruptableBySimple_7-11;

my $ChacoboGrabGetLatent_7-24 = Graph->new(multiedged => 1);
$ChacoboGrabGetLatent_7-24->set_graph_attribute("name", "ChacoboGrabGetLatent_7-24");
$ChacoboGrabGetLatent_7-24->add_edge_by_id("desmeme", "juncture", "STRICTURE");
$ChacoboGrabGetLatent_7-24->add_edge_by_id("juncture", "morphologicalConstituent", "CONSTITUENT");
$ChacoboGrabGetLatent_7-24->add_edge_by_id("juncture", "COUNT2-1", "COUNT");
$ChacoboGrabGetLatent_7-24->add_edge_by_id("desmeme", "notViolable", "VIOLABILITY");
$ChacoboGrabGetLatent_7-24->add_edge_by_id("desmeme", "lexicophonologicalConditioning", "CONDITIONING");
$ChacoboGrabGetLatent_7-24->add_edge_by_id("lexicophonologicalConditioning", "templateInitial", "FILLER_POSITION");
$ChacoboGrabGetLatent_7-24->add_edge_by_id("lexicophonologicalConditioning", "filledComponentSet", "FILLED_COMPONENTS");
$ChacoboGrabGetLatent_7-24->add_edge_by_id("filledComponentSet", "component1", "FILLED_COMPONENT");
$ChacoboGrabGetLatent_7-24->add_edge_by_id("component1", "filled1", "FILLEDNESS");
$ChacoboGrabGetLatent_7-24->add_edge_by_id("filled1", "canonicalLineate1", "FORM");
$ChacoboGrabGetLatent_7-24->add_edge_by_id("component1", "stable1", "STABILITY");
$ChacoboGrabGetLatent_7-24->add_edge_by_id("component1", "inelastic1", "ELASTICITY");
$ChacoboGrabGetLatent_7-24->add_edge_by_id("inelastic1", "COUNT1-1", "COUNT");
$ChacoboGrabGetLatent_7-24->add_edge_by_id("desmeme", "span", "FOUNDATION");
$ChacoboGrabGetLatent_7-24->add_edge_by_id("span", "component1", "LEFT_SUPPORT");
$ChacoboGrabGetLatent_7-24->add_edge_by_id("span", "component2", "RIGHT_SUPPORT");
$ChacoboGrabGetLatent_7-24->add_edge_by_id("component2", "inelastic2", "ELASTICITY");
$ChacoboGrabGetLatent_7-24->add_edge_by_id("inelastic2", "COUNT1-2", "COUNT");
$ChacoboGrabGetLatent_7-24->add_edge_by_id("component2", "open1", "FILLEDNESS");
$ChacoboGrabGetLatent_7-24->add_edge_by_id("open1", "coherent1", "COHERENCE");
$ChacoboGrabGetLatent_7-24->add_edge_by_id("component2", "stable2", "STABILITY");
$templateGraphs{ChacoboGrabGetLatent_7-24} = $ChacoboGrabGetLatent_7-24;

my $ChacoboGlottalStopMax_7-19 = Graph->new(multiedged => 1);
$ChacoboGlottalStopMax_7-19->set_graph_attribute("name", "ChacoboGlottalStopMax_7-19");
$ChacoboGlottalStopMax_7-19->add_edge_by_id("desmeme", "span", "FOUNDATION");
$ChacoboGlottalStopMax_7-19->add_edge_by_id("span", "component1", "RIGHT_SUPPORT");
$ChacoboGlottalStopMax_7-19->add_edge_by_id("component1", "elastic1", "ELASTICITY");
$ChacoboGlottalStopMax_7-19->add_edge_by_id("elastic1", "MINIMUM0-1", "MINIMUM");
$ChacoboGlottalStopMax_7-19->add_edge_by_id("elastic1", "MAXIMUM1-1", "MAXIMUM");
$ChacoboGlottalStopMax_7-19->add_edge_by_id("component1", "open1", "FILLEDNESS");
$ChacoboGlottalStopMax_7-19->add_edge_by_id("open1", "coherent1", "COHERENCE");
$ChacoboGlottalStopMax_7-19->add_edge_by_id("component1", "stable1", "STABILITY");
$ChacoboGlottalStopMax_7-19->add_edge_by_id("span", "restkomponentenSet", "RESTKOMPONENTEN");
$ChacoboGlottalStopMax_7-19->add_edge_by_id("restkomponentenSet", "component1", "RESTKOMPONENTE");
$ChacoboGlottalStopMax_7-19->add_edge_by_id("restkomponentenSet", "component2", "RESTKOMPONENTE");
$ChacoboGlottalStopMax_7-19->add_edge_by_id("component2", "elastic2", "ELASTICITY");
$ChacoboGlottalStopMax_7-19->add_edge_by_id("elastic2", "MINIMUM0-2", "MINIMUM");
$ChacoboGlottalStopMax_7-19->add_edge_by_id("elastic2", "MAXIMUM2-1", "MAXIMUM");
$ChacoboGlottalStopMax_7-19->add_edge_by_id("component2", "open2", "FILLEDNESS");
$ChacoboGlottalStopMax_7-19->add_edge_by_id("open2", "coherent2", "COHERENCE");
$ChacoboGlottalStopMax_7-19->add_edge_by_id("component2", "stable2", "STABILITY");
$ChacoboGlottalStopMax_7-19->add_edge_by_id("restkomponentenSet", "component3", "RESTKOMPONENTE");
$ChacoboGlottalStopMax_7-19->add_edge_by_id("component3", "elastic3", "ELASTICITY");
$ChacoboGlottalStopMax_7-19->add_edge_by_id("elastic3", "MINIMUM0-3", "MINIMUM");
$ChacoboGlottalStopMax_7-19->add_edge_by_id("elastic3", "MAXIMUM100-1", "MAXIMUM");
$ChacoboGlottalStopMax_7-19->add_edge_by_id("component3", "stable3", "STABILITY");
$ChacoboGlottalStopMax_7-19->add_edge_by_id("component3", "open3", "FILLEDNESS");
$ChacoboGlottalStopMax_7-19->add_edge_by_id("open3", "coherent3", "COHERENCE");
$ChacoboGlottalStopMax_7-19->add_edge_by_id("restkomponentenSet", "component4", "RESTKOMPONENTE");
$ChacoboGlottalStopMax_7-19->add_edge_by_id("component4", "open4", "FILLEDNESS");
$ChacoboGlottalStopMax_7-19->add_edge_by_id("open4", "coherent4", "COHERENCE");
$ChacoboGlottalStopMax_7-19->add_edge_by_id("component4", "elastic4", "ELASTICITY");
$ChacoboGlottalStopMax_7-19->add_edge_by_id("elastic4", "MAXIMUM1-2", "MAXIMUM");
$ChacoboGlottalStopMax_7-19->add_edge_by_id("elastic4", "MINIMUM0-4", "MINIMUM");
$ChacoboGlottalStopMax_7-19->add_edge_by_id("component4", "stable4", "STABILITY");
$ChacoboGlottalStopMax_7-19->add_edge_by_id("restkomponentenSet", "component5", "RESTKOMPONENTE");
$ChacoboGlottalStopMax_7-19->add_edge_by_id("component5", "elastic5", "ELASTICITY");
$ChacoboGlottalStopMax_7-19->add_edge_by_id("elastic5", "MINIMUM0-5", "MINIMUM");
$ChacoboGlottalStopMax_7-19->add_edge_by_id("elastic5", "MAXIMUM1-3", "MAXIMUM");
$ChacoboGlottalStopMax_7-19->add_edge_by_id("component5", "filled1", "FILLEDNESS");
$ChacoboGlottalStopMax_7-19->add_edge_by_id("filled1", "canonicalLineate1", "FORM");
$ChacoboGlottalStopMax_7-19->add_edge_by_id("component5", "stable5", "STABILITY");
$ChacoboGlottalStopMax_7-19->add_edge_by_id("restkomponentenSet", "component6", "RESTKOMPONENTE");
$ChacoboGlottalStopMax_7-19->add_edge_by_id("component6", "elastic6", "ELASTICITY");
$ChacoboGlottalStopMax_7-19->add_edge_by_id("elastic6", "MINIMUM0-6", "MINIMUM");
$ChacoboGlottalStopMax_7-19->add_edge_by_id("elastic6", "MAXIMUM2-2", "MAXIMUM");
$ChacoboGlottalStopMax_7-19->add_edge_by_id("component6", "open5", "FILLEDNESS");
$ChacoboGlottalStopMax_7-19->add_edge_by_id("open5", "incoherent1", "COHERENCE");
$ChacoboGlottalStopMax_7-19->add_edge_by_id("component6", "stable6", "STABILITY");
$ChacoboGlottalStopMax_7-19->add_edge_by_id("restkomponentenSet", "component7", "RESTKOMPONENTE");
$ChacoboGlottalStopMax_7-19->add_edge_by_id("component7", "open6", "FILLEDNESS");
$ChacoboGlottalStopMax_7-19->add_edge_by_id("open6", "coherent5", "COHERENCE");
$ChacoboGlottalStopMax_7-19->add_edge_by_id("component7", "elastic7", "ELASTICITY");
$ChacoboGlottalStopMax_7-19->add_edge_by_id("elastic7", "MINIMUM0-7", "MINIMUM");
$ChacoboGlottalStopMax_7-19->add_edge_by_id("elastic7", "MAXIMUM3-1", "MAXIMUM");
$ChacoboGlottalStopMax_7-19->add_edge_by_id("component7", "stable7", "STABILITY");
$ChacoboGlottalStopMax_7-19->add_edge_by_id("restkomponentenSet", "component8", "RESTKOMPONENTE");
$ChacoboGlottalStopMax_7-19->add_edge_by_id("component8", "unstable1", "STABILITY");
$ChacoboGlottalStopMax_7-19->add_edge_by_id("unstable1", "component9", "ASSOCIATE");
$ChacoboGlottalStopMax_7-19->add_edge_by_id("component9", "elastic8", "ELASTICITY");
$ChacoboGlottalStopMax_7-19->add_edge_by_id("elastic8", "MAXIMUM1-4", "MAXIMUM");
$ChacoboGlottalStopMax_7-19->add_edge_by_id("elastic8", "MINIMUM0-8", "MINIMUM");
$ChacoboGlottalStopMax_7-19->add_edge_by_id("component9", "open7", "FILLEDNESS");
$ChacoboGlottalStopMax_7-19->add_edge_by_id("open7", "coherent6", "COHERENCE");
$ChacoboGlottalStopMax_7-19->add_edge_by_id("component9", "stable8", "STABILITY");
$ChacoboGlottalStopMax_7-19->add_edge_by_id("unstable1", "left", "ASSOCIATE_POSITION");
$ChacoboGlottalStopMax_7-19->add_edge_by_id("component8", "open8", "FILLEDNESS");
$ChacoboGlottalStopMax_7-19->add_edge_by_id("open8", "coherent7", "COHERENCE");
$ChacoboGlottalStopMax_7-19->add_edge_by_id("component8", "elastic9", "ELASTICITY");
$ChacoboGlottalStopMax_7-19->add_edge_by_id("elastic9", "MAXIMUM1-5", "MAXIMUM");
$ChacoboGlottalStopMax_7-19->add_edge_by_id("elastic9", "MINIMUM0-9", "MINIMUM");
$ChacoboGlottalStopMax_7-19->add_edge_by_id("restkomponentenSet", "component10", "RESTKOMPONENTE");
$ChacoboGlottalStopMax_7-19->add_edge_by_id("component10", "filled2", "FILLEDNESS");
$ChacoboGlottalStopMax_7-19->add_edge_by_id("filled2", "canonicalLineate2", "FORM");
$ChacoboGlottalStopMax_7-19->add_edge_by_id("component10", "elastic10", "ELASTICITY");
$ChacoboGlottalStopMax_7-19->add_edge_by_id("elastic10", "MAXIMUM1-6", "MAXIMUM");
$ChacoboGlottalStopMax_7-19->add_edge_by_id("elastic10", "MINIMUM0-10", "MINIMUM");
$ChacoboGlottalStopMax_7-19->add_edge_by_id("component10", "stable9", "STABILITY");
$ChacoboGlottalStopMax_7-19->add_edge_by_id("restkomponentenSet", "component11", "RESTKOMPONENTE");
$ChacoboGlottalStopMax_7-19->add_edge_by_id("component11", "elastic11", "ELASTICITY");
$ChacoboGlottalStopMax_7-19->add_edge_by_id("elastic11", "MINIMUM0-11", "MINIMUM");
$ChacoboGlottalStopMax_7-19->add_edge_by_id("elastic11", "MAXIMUM1-7", "MAXIMUM");
$ChacoboGlottalStopMax_7-19->add_edge_by_id("component11", "stable10", "STABILITY");
$ChacoboGlottalStopMax_7-19->add_edge_by_id("component11", "open9", "FILLEDNESS");
$ChacoboGlottalStopMax_7-19->add_edge_by_id("open9", "coherent8", "COHERENCE");
$ChacoboGlottalStopMax_7-19->add_edge_by_id("restkomponentenSet", "component12", "RESTKOMPONENTE");
$ChacoboGlottalStopMax_7-19->add_edge_by_id("component12", "elastic12", "ELASTICITY");
$ChacoboGlottalStopMax_7-19->add_edge_by_id("elastic12", "MAXIMUM1-8", "MAXIMUM");
$ChacoboGlottalStopMax_7-19->add_edge_by_id("elastic12", "MINIMUM0-12", "MINIMUM");
$ChacoboGlottalStopMax_7-19->add_edge_by_id("component12", "stable11", "STABILITY");
$ChacoboGlottalStopMax_7-19->add_edge_by_id("component12", "filled3", "FILLEDNESS");
$ChacoboGlottalStopMax_7-19->add_edge_by_id("filled3", "canonicalLineate3", "FORM");
$ChacoboGlottalStopMax_7-19->add_edge_by_id("restkomponentenSet", "component13", "RESTKOMPONENTE");
$ChacoboGlottalStopMax_7-19->add_edge_by_id("component13", "open10", "FILLEDNESS");
$ChacoboGlottalStopMax_7-19->add_edge_by_id("open10", "coherent9", "COHERENCE");
$ChacoboGlottalStopMax_7-19->add_edge_by_id("component13", "inelastic1", "ELASTICITY");
$ChacoboGlottalStopMax_7-19->add_edge_by_id("inelastic1", "COUNT1-1", "COUNT");
$ChacoboGlottalStopMax_7-19->add_edge_by_id("component13", "stable12", "STABILITY");
$ChacoboGlottalStopMax_7-19->add_edge_by_id("span", "component9", "LEFT_SUPPORT");
$ChacoboGlottalStopMax_7-19->add_edge_by_id("desmeme", "juncture", "STRICTURE");
$ChacoboGlottalStopMax_7-19->add_edge_by_id("juncture", "COUNT13-1", "COUNT");
$ChacoboGlottalStopMax_7-19->add_edge_by_id("juncture", "morphologicalConstituent", "CONSTITUENT");
$ChacoboGlottalStopMax_7-19->add_edge_by_id("desmeme", "segmental", "CONDITIONING");
$ChacoboGlottalStopMax_7-19->add_edge_by_id("desmeme", "notViolable", "VIOLABILITY");
$templateGraphs{ChacoboGlottalStopMax_7-19} = $ChacoboGlottalStopMax_7-19;

my $ChacoboDoTakeDrinkKillLatent_7-24 = Graph->new(multiedged => 1);
$ChacoboDoTakeDrinkKillLatent_7-24->set_graph_attribute("name", "ChacoboDoTakeDrinkKillLatent_7-24");
$ChacoboDoTakeDrinkKillLatent_7-24->add_edge_by_id("desmeme", "lexicophonologicalConditioning", "CONDITIONING");
$ChacoboDoTakeDrinkKillLatent_7-24->add_edge_by_id("lexicophonologicalConditioning", "templateInitial", "FILLER_POSITION");
$ChacoboDoTakeDrinkKillLatent_7-24->add_edge_by_id("lexicophonologicalConditioning", "filledComponentSet", "FILLED_COMPONENTS");
$ChacoboDoTakeDrinkKillLatent_7-24->add_edge_by_id("filledComponentSet", "component1", "FILLED_COMPONENT");
$ChacoboDoTakeDrinkKillLatent_7-24->add_edge_by_id("component1", "inelastic1", "ELASTICITY");
$ChacoboDoTakeDrinkKillLatent_7-24->add_edge_by_id("inelastic1", "COUNT1-1", "COUNT");
$ChacoboDoTakeDrinkKillLatent_7-24->add_edge_by_id("component1", "filled1", "FILLEDNESS");
$ChacoboDoTakeDrinkKillLatent_7-24->add_edge_by_id("filled1", "canonicalLineate1", "FORM");
$ChacoboDoTakeDrinkKillLatent_7-24->add_edge_by_id("component1", "stable1", "STABILITY");
$ChacoboDoTakeDrinkKillLatent_7-24->add_edge_by_id("desmeme", "notViolable", "VIOLABILITY");
$ChacoboDoTakeDrinkKillLatent_7-24->add_edge_by_id("desmeme", "juncture", "STRICTURE");
$ChacoboDoTakeDrinkKillLatent_7-24->add_edge_by_id("juncture", "morphologicalConstituent", "CONSTITUENT");
$ChacoboDoTakeDrinkKillLatent_7-24->add_edge_by_id("juncture", "COUNT2-1", "COUNT");
$ChacoboDoTakeDrinkKillLatent_7-24->add_edge_by_id("desmeme", "span", "FOUNDATION");
$ChacoboDoTakeDrinkKillLatent_7-24->add_edge_by_id("span", "component2", "RIGHT_SUPPORT");
$ChacoboDoTakeDrinkKillLatent_7-24->add_edge_by_id("component2", "inelastic2", "ELASTICITY");
$ChacoboDoTakeDrinkKillLatent_7-24->add_edge_by_id("inelastic2", "COUNT1-2", "COUNT");
$ChacoboDoTakeDrinkKillLatent_7-24->add_edge_by_id("component2", "open1", "FILLEDNESS");
$ChacoboDoTakeDrinkKillLatent_7-24->add_edge_by_id("open1", "coherent1", "COHERENCE");
$ChacoboDoTakeDrinkKillLatent_7-24->add_edge_by_id("component2", "stable2", "STABILITY");
$ChacoboDoTakeDrinkKillLatent_7-24->add_edge_by_id("span", "component1", "LEFT_SUPPORT");
$templateGraphs{ChacoboDoTakeDrinkKillLatent_7-24} = $ChacoboDoTakeDrinkKillLatent_7-24;

my $ChacoboApocope_1-24 = Graph->new(multiedged => 1);
$ChacoboApocope_1-24->set_graph_attribute("name", "ChacoboApocope_1-24");
$ChacoboApocope_1-24->add_edge_by_id("desmeme", "potentiallyViolable", "VIOLABILITY");
$ChacoboApocope_1-24->add_edge_by_id("potentiallyViolable", "surfaceViolable", "REPARABILITY");
$ChacoboApocope_1-24->add_edge_by_id("potentiallyViolable", "lexical", "EXCEPTIONALITY");
$ChacoboApocope_1-24->add_edge_by_id("desmeme", "juncture", "STRICTURE");
$ChacoboApocope_1-24->add_edge_by_id("juncture", "prosodicWord", "CONSTITUENT");
$ChacoboApocope_1-24->add_edge_by_id("juncture", "COUNT2-1", "COUNT");
$ChacoboApocope_1-24->add_edge_by_id("desmeme", "phonomorphosyntacticConditioning", "CONDITIONING");
$ChacoboApocope_1-24->add_edge_by_id("desmeme", "span", "FOUNDATION");
$ChacoboApocope_1-24->add_edge_by_id("span", "component1", "LEFT_SUPPORT");
$ChacoboApocope_1-24->add_edge_by_id("component1", "inelastic1", "ELASTICITY");
$ChacoboApocope_1-24->add_edge_by_id("inelastic1", "COUNT1-1", "COUNT");
$ChacoboApocope_1-24->add_edge_by_id("component1", "open1", "FILLEDNESS");
$ChacoboApocope_1-24->add_edge_by_id("open1", "incoherent1", "COHERENCE");
$ChacoboApocope_1-24->add_edge_by_id("component1", "stable1", "STABILITY");
$ChacoboApocope_1-24->add_edge_by_id("span", "component2", "RIGHT_SUPPORT");
$ChacoboApocope_1-24->add_edge_by_id("component2", "open2", "FILLEDNESS");
$ChacoboApocope_1-24->add_edge_by_id("open2", "incoherent2", "COHERENCE");
$ChacoboApocope_1-24->add_edge_by_id("component2", "stable2", "STABILITY");
$ChacoboApocope_1-24->add_edge_by_id("component2", "inelastic2", "ELASTICITY");
$ChacoboApocope_1-24->add_edge_by_id("inelastic2", "COUNT1-2", "COUNT");
$templateGraphs{ChacoboApocope_1-24} = $ChacoboApocope_1-24;

my $ChacoboGlottalStopMin_7-8 = Graph->new(multiedged => 1);
$ChacoboGlottalStopMin_7-8->set_graph_attribute("name", "ChacoboGlottalStopMin_7-8");
$ChacoboGlottalStopMin_7-8->add_edge_by_id("desmeme", "juncture", "STRICTURE");
$ChacoboGlottalStopMin_7-8->add_edge_by_id("juncture", "morphologicalConstituent", "CONSTITUENT");
$ChacoboGlottalStopMin_7-8->add_edge_by_id("juncture", "COUNT2-1", "COUNT");
$ChacoboGlottalStopMin_7-8->add_edge_by_id("desmeme", "segmental", "CONDITIONING");
$ChacoboGlottalStopMin_7-8->add_edge_by_id("desmeme", "notViolable", "VIOLABILITY");
$ChacoboGlottalStopMin_7-8->add_edge_by_id("desmeme", "span", "FOUNDATION");
$ChacoboGlottalStopMin_7-8->add_edge_by_id("span", "component1", "RIGHT_SUPPORT");
$ChacoboGlottalStopMin_7-8->add_edge_by_id("component1", "open1", "FILLEDNESS");
$ChacoboGlottalStopMin_7-8->add_edge_by_id("open1", "coherent1", "COHERENCE");
$ChacoboGlottalStopMin_7-8->add_edge_by_id("component1", "inelastic1", "ELASTICITY");
$ChacoboGlottalStopMin_7-8->add_edge_by_id("inelastic1", "COUNT1-1", "COUNT");
$ChacoboGlottalStopMin_7-8->add_edge_by_id("component1", "stable1", "STABILITY");
$ChacoboGlottalStopMin_7-8->add_edge_by_id("span", "component2", "LEFT_SUPPORT");
$ChacoboGlottalStopMin_7-8->add_edge_by_id("component2", "elastic1", "ELASTICITY");
$ChacoboGlottalStopMin_7-8->add_edge_by_id("elastic1", "MAXIMUM1-1", "MAXIMUM");
$ChacoboGlottalStopMin_7-8->add_edge_by_id("elastic1", "MINIMUM0-1", "MINIMUM");
$ChacoboGlottalStopMin_7-8->add_edge_by_id("component2", "open2", "FILLEDNESS");
$ChacoboGlottalStopMin_7-8->add_edge_by_id("open2", "coherent2", "COHERENCE");
$ChacoboGlottalStopMin_7-8->add_edge_by_id("component2", "stable2", "STABILITY");
$templateGraphs{ChacoboGlottalStopMin_7-8} = $ChacoboGlottalStopMin_7-8;

my $ChacoboHighToneReduction_6-27 = Graph->new(multiedged => 1);
$ChacoboHighToneReduction_6-27->set_graph_attribute("name", "ChacoboHighToneReduction_6-27");
$ChacoboHighToneReduction_6-27->add_edge_by_id("desmeme", "span", "FOUNDATION");
$ChacoboHighToneReduction_6-27->add_edge_by_id("span", "component1", "LEFT_SUPPORT");
$ChacoboHighToneReduction_6-27->add_edge_by_id("component1", "open1", "FILLEDNESS");
$ChacoboHighToneReduction_6-27->add_edge_by_id("open1", "coherent1", "COHERENCE");
$ChacoboHighToneReduction_6-27->add_edge_by_id("component1", "unstable1", "STABILITY");
$ChacoboHighToneReduction_6-27->add_edge_by_id("unstable1", "right", "ASSOCIATE_POSITION");
$ChacoboHighToneReduction_6-27->add_edge_by_id("unstable1", "component2", "ASSOCIATE");
$ChacoboHighToneReduction_6-27->add_edge_by_id("component2", "open2", "FILLEDNESS");
$ChacoboHighToneReduction_6-27->add_edge_by_id("open2", "coherent2", "COHERENCE");
$ChacoboHighToneReduction_6-27->add_edge_by_id("component2", "inelastic1", "ELASTICITY");
$ChacoboHighToneReduction_6-27->add_edge_by_id("inelastic1", "COUNT1-1", "COUNT");
$ChacoboHighToneReduction_6-27->add_edge_by_id("component2", "stable1", "STABILITY");
$ChacoboHighToneReduction_6-27->add_edge_by_id("component1", "inelastic2", "ELASTICITY");
$ChacoboHighToneReduction_6-27->add_edge_by_id("inelastic2", "COUNT1-2", "COUNT");
$ChacoboHighToneReduction_6-27->add_edge_by_id("desmeme", "prosodicConditioning", "CONDITIONING");
$ChacoboHighToneReduction_6-27->add_edge_by_id("desmeme", "notViolable", "VIOLABILITY");
$ChacoboHighToneReduction_6-27->add_edge_by_id("desmeme", "order", "STRICTURE");
$ChacoboHighToneReduction_6-27->add_edge_by_id("order", "simple", "RELATIONS");
$ChacoboHighToneReduction_6-27->add_edge_by_id("order", "prosodicConstituent", "CONSTITUENT");
$ChacoboHighToneReduction_6-27->add_edge_by_id("order", "COUNT2-1", "COUNT");
$templateGraphs{ChacoboHighToneReduction_6-27} = $ChacoboHighToneReduction_6-27;

my $ChacoboMinimality_7-10 = Graph->new(multiedged => 1);
$ChacoboMinimality_7-10->set_graph_attribute("name", "ChacoboMinimality_7-10");
$ChacoboMinimality_7-10->add_edge_by_id("desmeme", "prosodicConditioning", "CONDITIONING");
$ChacoboMinimality_7-10->add_edge_by_id("desmeme", "length", "STRICTURE");
$ChacoboMinimality_7-10->add_edge_by_id("length", "COUNT2-1", "COUNT");
$ChacoboMinimality_7-10->add_edge_by_id("length", "Mora", "CONSTITUENT");
$ChacoboMinimality_7-10->add_edge_by_id("desmeme", "span", "FOUNDATION");
$ChacoboMinimality_7-10->add_edge_by_id("span", "component1", "RIGHT_SUPPORT");
$ChacoboMinimality_7-10->add_edge_by_id("component1", "open1", "FILLEDNESS");
$ChacoboMinimality_7-10->add_edge_by_id("open1", "coherent1", "COHERENCE");
$ChacoboMinimality_7-10->add_edge_by_id("component1", "elastic1", "ELASTICITY");
$ChacoboMinimality_7-10->add_edge_by_id("elastic1", "MAXIMUM1-1", "MAXIMUM");
$ChacoboMinimality_7-10->add_edge_by_id("elastic1", "MINIMUM0-1", "MINIMUM");
$ChacoboMinimality_7-10->add_edge_by_id("component1", "stable1", "STABILITY");
$ChacoboMinimality_7-10->add_edge_by_id("span", "component2", "LEFT_SUPPORT");
$ChacoboMinimality_7-10->add_edge_by_id("component2", "inelastic1", "ELASTICITY");
$ChacoboMinimality_7-10->add_edge_by_id("inelastic1", "COUNT1-1", "COUNT");
$ChacoboMinimality_7-10->add_edge_by_id("component2", "stable2", "STABILITY");
$ChacoboMinimality_7-10->add_edge_by_id("component2", "filled1", "FILLEDNESS");
$ChacoboMinimality_7-10->add_edge_by_id("filled1", "embeddedDesmeme", "FORM");
$ChacoboMinimality_7-10->add_edge_by_id("desmeme", "potentiallyViolable", "VIOLABILITY");
$ChacoboMinimality_7-10->add_edge_by_id("potentiallyViolable", "surfaceViolable", "REPARABILITY");
$ChacoboMinimality_7-10->add_edge_by_id("potentiallyViolable", "lexical", "EXCEPTIONALITY");
$templateGraphs{ChacoboMinimality_7-10} = $ChacoboMinimality_7-10;

my $ChacoboHighToneInsertion_7-13 = Graph->new(multiedged => 1);
$ChacoboHighToneInsertion_7-13->set_graph_attribute("name", "ChacoboHighToneInsertion_7-13");
$ChacoboHighToneInsertion_7-13->add_edge_by_id("desmeme", "edge", "STRICTURE");
$ChacoboHighToneInsertion_7-13->add_edge_by_id("desmeme", "span", "FOUNDATION");
$ChacoboHighToneInsertion_7-13->add_edge_by_id("span", "component1", "LEFT_SUPPORT");
$ChacoboHighToneInsertion_7-13->add_edge_by_id("component1", "elastic1", "ELASTICITY");
$ChacoboHighToneInsertion_7-13->add_edge_by_id("elastic1", "MAXIMUM1-1", "MAXIMUM");
$ChacoboHighToneInsertion_7-13->add_edge_by_id("elastic1", "MINIMUM0-1", "MINIMUM");
$ChacoboHighToneInsertion_7-13->add_edge_by_id("component1", "open1", "FILLEDNESS");
$ChacoboHighToneInsertion_7-13->add_edge_by_id("open1", "coherent1", "COHERENCE");
$ChacoboHighToneInsertion_7-13->add_edge_by_id("component1", "stable1", "STABILITY");
$ChacoboHighToneInsertion_7-13->add_edge_by_id("span", "restkomponentenSet", "RESTKOMPONENTEN");
$ChacoboHighToneInsertion_7-13->add_edge_by_id("restkomponentenSet", "component2", "RESTKOMPONENTE");
$ChacoboHighToneInsertion_7-13->add_edge_by_id("component2", "open2", "FILLEDNESS");
$ChacoboHighToneInsertion_7-13->add_edge_by_id("open2", "coherent2", "COHERENCE");
$ChacoboHighToneInsertion_7-13->add_edge_by_id("component2", "inelastic1", "ELASTICITY");
$ChacoboHighToneInsertion_7-13->add_edge_by_id("inelastic1", "COUNT1-1", "COUNT");
$ChacoboHighToneInsertion_7-13->add_edge_by_id("component2", "stable2", "STABILITY");
$ChacoboHighToneInsertion_7-13->add_edge_by_id("restkomponentenSet", "component3", "RESTKOMPONENTE");
$ChacoboHighToneInsertion_7-13->add_edge_by_id("component3", "open3", "FILLEDNESS");
$ChacoboHighToneInsertion_7-13->add_edge_by_id("open3", "coherent3", "COHERENCE");
$ChacoboHighToneInsertion_7-13->add_edge_by_id("component3", "elastic2", "ELASTICITY");
$ChacoboHighToneInsertion_7-13->add_edge_by_id("elastic2", "MINIMUM0-2", "MINIMUM");
$ChacoboHighToneInsertion_7-13->add_edge_by_id("elastic2", "MAXIMUM3-1", "MAXIMUM");
$ChacoboHighToneInsertion_7-13->add_edge_by_id("component3", "stable3", "STABILITY");
$ChacoboHighToneInsertion_7-13->add_edge_by_id("restkomponentenSet", "component4", "RESTKOMPONENTE");
$ChacoboHighToneInsertion_7-13->add_edge_by_id("component4", "unstable1", "STABILITY");
$ChacoboHighToneInsertion_7-13->add_edge_by_id("unstable1", "component1", "ASSOCIATE");
$ChacoboHighToneInsertion_7-13->add_edge_by_id("unstable1", "left", "ASSOCIATE_POSITION");
$ChacoboHighToneInsertion_7-13->add_edge_by_id("component4", "open4", "FILLEDNESS");
$ChacoboHighToneInsertion_7-13->add_edge_by_id("open4", "coherent4", "COHERENCE");
$ChacoboHighToneInsertion_7-13->add_edge_by_id("component4", "elastic3", "ELASTICITY");
$ChacoboHighToneInsertion_7-13->add_edge_by_id("elastic3", "MAXIMUM1-2", "MAXIMUM");
$ChacoboHighToneInsertion_7-13->add_edge_by_id("elastic3", "MINIMUM0-3", "MINIMUM");
$ChacoboHighToneInsertion_7-13->add_edge_by_id("restkomponentenSet", "component5", "RESTKOMPONENTE");
$ChacoboHighToneInsertion_7-13->add_edge_by_id("component5", "open5", "FILLEDNESS");
$ChacoboHighToneInsertion_7-13->add_edge_by_id("open5", "coherent5", "COHERENCE");
$ChacoboHighToneInsertion_7-13->add_edge_by_id("component5", "elastic4", "ELASTICITY");
$ChacoboHighToneInsertion_7-13->add_edge_by_id("elastic4", "MAXIMUM1-3", "MAXIMUM");
$ChacoboHighToneInsertion_7-13->add_edge_by_id("elastic4", "MINIMUM0-4", "MINIMUM");
$ChacoboHighToneInsertion_7-13->add_edge_by_id("component5", "stable4", "STABILITY");
$ChacoboHighToneInsertion_7-13->add_edge_by_id("restkomponentenSet", "component6", "RESTKOMPONENTE");
$ChacoboHighToneInsertion_7-13->add_edge_by_id("component6", "elastic5", "ELASTICITY");
$ChacoboHighToneInsertion_7-13->add_edge_by_id("elastic5", "MINIMUM0-5", "MINIMUM");
$ChacoboHighToneInsertion_7-13->add_edge_by_id("elastic5", "MAXIMUM2-1", "MAXIMUM");
$ChacoboHighToneInsertion_7-13->add_edge_by_id("component6", "open6", "FILLEDNESS");
$ChacoboHighToneInsertion_7-13->add_edge_by_id("open6", "coherent6", "COHERENCE");
$ChacoboHighToneInsertion_7-13->add_edge_by_id("component6", "stable5", "STABILITY");
$ChacoboHighToneInsertion_7-13->add_edge_by_id("span", "component7", "RIGHT_SUPPORT");
$ChacoboHighToneInsertion_7-13->add_edge_by_id("component7", "filled1", "FILLEDNESS");
$ChacoboHighToneInsertion_7-13->add_edge_by_id("filled1", "canonicalLineate1", "FORM");
$ChacoboHighToneInsertion_7-13->add_edge_by_id("component7", "elastic6", "ELASTICITY");
$ChacoboHighToneInsertion_7-13->add_edge_by_id("elastic6", "MAXIMUM1-4", "MAXIMUM");
$ChacoboHighToneInsertion_7-13->add_edge_by_id("elastic6", "MINIMUM0-6", "MINIMUM");
$ChacoboHighToneInsertion_7-13->add_edge_by_id("component7", "stable6", "STABILITY");
$ChacoboHighToneInsertion_7-13->add_edge_by_id("desmeme", "prosodicConditioning", "CONDITIONING");
$ChacoboHighToneInsertion_7-13->add_edge_by_id("desmeme", "notViolable", "VIOLABILITY");
$templateGraphs{ChacoboHighToneInsertion_7-13} = $ChacoboHighToneInsertion_7-13;

my $ChacoboNonInterruptibleByNP_7-19 = Graph->new(multiedged => 1);
$ChacoboNonInterruptibleByNP_7-19->set_graph_attribute("name", "ChacoboNonInterruptibleByNP_7-19");
$ChacoboNonInterruptibleByNP_7-19->add_edge_by_id("desmeme", "arch", "FOUNDATION");
$ChacoboNonInterruptibleByNP_7-19->add_edge_by_id("arch", "component1", "KEYSTONE");
$ChacoboNonInterruptibleByNP_7-19->add_edge_by_id("component1", "inelastic1", "ELASTICITY");
$ChacoboNonInterruptibleByNP_7-19->add_edge_by_id("inelastic1", "COUNT1-1", "COUNT");
$ChacoboNonInterruptibleByNP_7-19->add_edge_by_id("component1", "stable1", "STABILITY");
$ChacoboNonInterruptibleByNP_7-19->add_edge_by_id("component1", "filled1", "FILLEDNESS");
$ChacoboNonInterruptibleByNP_7-19->add_edge_by_id("filled1", "embeddedDesmeme", "FORM");
$ChacoboNonInterruptibleByNP_7-19->add_edge_by_id("arch", "restkomponentenSet", "RESTKOMPONENTEN");
$ChacoboNonInterruptibleByNP_7-19->add_edge_by_id("restkomponentenSet", "component2", "RESTKOMPONENTE");
$ChacoboNonInterruptibleByNP_7-19->add_edge_by_id("component2", "elastic1", "ELASTICITY");
$ChacoboNonInterruptibleByNP_7-19->add_edge_by_id("elastic1", "MAXIMUM1-1", "MAXIMUM");
$ChacoboNonInterruptibleByNP_7-19->add_edge_by_id("elastic1", "MINIMUM0-1", "MINIMUM");
$ChacoboNonInterruptibleByNP_7-19->add_edge_by_id("component2", "stable2", "STABILITY");
$ChacoboNonInterruptibleByNP_7-19->add_edge_by_id("component2", "filled2", "FILLEDNESS");
$ChacoboNonInterruptibleByNP_7-19->add_edge_by_id("filled2", "canonicalLineate1", "FORM");
$ChacoboNonInterruptibleByNP_7-19->add_edge_by_id("restkomponentenSet", "component3", "RESTKOMPONENTE");
$ChacoboNonInterruptibleByNP_7-19->add_edge_by_id("component3", "elastic2", "ELASTICITY");
$ChacoboNonInterruptibleByNP_7-19->add_edge_by_id("elastic2", "MINIMUM0-2", "MINIMUM");
$ChacoboNonInterruptibleByNP_7-19->add_edge_by_id("elastic2", "MAXIMUM1-2", "MAXIMUM");
$ChacoboNonInterruptibleByNP_7-19->add_edge_by_id("component3", "stable3", "STABILITY");
$ChacoboNonInterruptibleByNP_7-19->add_edge_by_id("component3", "open1", "FILLEDNESS");
$ChacoboNonInterruptibleByNP_7-19->add_edge_by_id("open1", "coherent1", "COHERENCE");
$ChacoboNonInterruptibleByNP_7-19->add_edge_by_id("restkomponentenSet", "component4", "RESTKOMPONENTE");
$ChacoboNonInterruptibleByNP_7-19->add_edge_by_id("component4", "elastic3", "ELASTICITY");
$ChacoboNonInterruptibleByNP_7-19->add_edge_by_id("elastic3", "MINIMUM0-3", "MINIMUM");
$ChacoboNonInterruptibleByNP_7-19->add_edge_by_id("elastic3", "MAXIMUM2-1", "MAXIMUM");
$ChacoboNonInterruptibleByNP_7-19->add_edge_by_id("component4", "open2", "FILLEDNESS");
$ChacoboNonInterruptibleByNP_7-19->add_edge_by_id("open2", "incoherent1", "COHERENCE");
$ChacoboNonInterruptibleByNP_7-19->add_edge_by_id("component4", "stable4", "STABILITY");
$ChacoboNonInterruptibleByNP_7-19->add_edge_by_id("restkomponentenSet", "component5", "RESTKOMPONENTE");
$ChacoboNonInterruptibleByNP_7-19->add_edge_by_id("component5", "elastic4", "ELASTICITY");
$ChacoboNonInterruptibleByNP_7-19->add_edge_by_id("elastic4", "MINIMUM0-4", "MINIMUM");
$ChacoboNonInterruptibleByNP_7-19->add_edge_by_id("elastic4", "MAXIMUM1-3", "MAXIMUM");
$ChacoboNonInterruptibleByNP_7-19->add_edge_by_id("component5", "filled3", "FILLEDNESS");
$ChacoboNonInterruptibleByNP_7-19->add_edge_by_id("filled3", "canonicalLineate2", "FORM");
$ChacoboNonInterruptibleByNP_7-19->add_edge_by_id("component5", "stable5", "STABILITY");
$ChacoboNonInterruptibleByNP_7-19->add_edge_by_id("restkomponentenSet", "component6", "RESTKOMPONENTE");
$ChacoboNonInterruptibleByNP_7-19->add_edge_by_id("component6", "filled4", "FILLEDNESS");
$ChacoboNonInterruptibleByNP_7-19->add_edge_by_id("filled4", "canonicalLineate3", "FORM");
$ChacoboNonInterruptibleByNP_7-19->add_edge_by_id("component6", "elastic5", "ELASTICITY");
$ChacoboNonInterruptibleByNP_7-19->add_edge_by_id("elastic5", "MAXIMUM1-4", "MAXIMUM");
$ChacoboNonInterruptibleByNP_7-19->add_edge_by_id("elastic5", "MINIMUM0-5", "MINIMUM");
$ChacoboNonInterruptibleByNP_7-19->add_edge_by_id("component6", "stable6", "STABILITY");
$ChacoboNonInterruptibleByNP_7-19->add_edge_by_id("arch", "component1", "LEFT_SUPPORT");
$ChacoboNonInterruptibleByNP_7-19->add_edge_by_id("arch", "component7", "LEFT_VOUSSOIR");
$ChacoboNonInterruptibleByNP_7-19->add_edge_by_id("component7", "null1", "FILLEDNESS");
$ChacoboNonInterruptibleByNP_7-19->add_edge_by_id("component7", "stable7", "STABILITY");
$ChacoboNonInterruptibleByNP_7-19->add_edge_by_id("component7", "inelastic2", "ELASTICITY");
$ChacoboNonInterruptibleByNP_7-19->add_edge_by_id("inelastic2", "COUNT0-1", "COUNT");
$ChacoboNonInterruptibleByNP_7-19->add_edge_by_id("arch", "component8", "RIGHT_SUPPORT");
$ChacoboNonInterruptibleByNP_7-19->add_edge_by_id("component8", "elastic6", "ELASTICITY");
$ChacoboNonInterruptibleByNP_7-19->add_edge_by_id("elastic6", "MINIMUM0-6", "MINIMUM");
$ChacoboNonInterruptibleByNP_7-19->add_edge_by_id("elastic6", "MAXIMUM1-5", "MAXIMUM");
$ChacoboNonInterruptibleByNP_7-19->add_edge_by_id("component8", "open3", "FILLEDNESS");
$ChacoboNonInterruptibleByNP_7-19->add_edge_by_id("open3", "coherent2", "COHERENCE");
$ChacoboNonInterruptibleByNP_7-19->add_edge_by_id("component8", "stable8", "STABILITY");
$ChacoboNonInterruptibleByNP_7-19->add_edge_by_id("arch", "component9", "RIGHT_VOUSSOIR");
$ChacoboNonInterruptibleByNP_7-19->add_edge_by_id("component9", "open4", "FILLEDNESS");
$ChacoboNonInterruptibleByNP_7-19->add_edge_by_id("open4", "coherent3", "COHERENCE");
$ChacoboNonInterruptibleByNP_7-19->add_edge_by_id("component9", "elastic7", "ELASTICITY");
$ChacoboNonInterruptibleByNP_7-19->add_edge_by_id("elastic7", "MINIMUM0-7", "MINIMUM");
$ChacoboNonInterruptibleByNP_7-19->add_edge_by_id("elastic7", "MAXIMUM3-1", "MAXIMUM");
$ChacoboNonInterruptibleByNP_7-19->add_edge_by_id("component9", "stable9", "STABILITY");
$ChacoboNonInterruptibleByNP_7-19->add_edge_by_id("desmeme", "edge", "STRICTURE");
$ChacoboNonInterruptibleByNP_7-19->add_edge_by_id("edge", "COUNT2-1", "COUNT");
$ChacoboNonInterruptibleByNP_7-19->add_edge_by_id("edge", "morphologicalConstituent", "CONSTITUENT");
$ChacoboNonInterruptibleByNP_7-19->add_edge_by_id("desmeme", "notViolable", "VIOLABILITY");
$ChacoboNonInterruptibleByNP_7-19->add_edge_by_id("desmeme", "constructionalConditioning", "CONDITIONING");
$templateGraphs{ChacoboNonInterruptibleByNP_7-19} = $ChacoboNonInterruptibleByNP_7-19;

my $ChacoboNonPermutableStrict_7-10 = Graph->new(multiedged => 1);
$ChacoboNonPermutableStrict_7-10->set_graph_attribute("name", "ChacoboNonPermutableStrict_7-10");
$ChacoboNonPermutableStrict_7-10->add_edge_by_id("desmeme", "arch", "FOUNDATION");
$ChacoboNonPermutableStrict_7-10->add_edge_by_id("arch", "component1", "LEFT_VOUSSOIR");
$ChacoboNonPermutableStrict_7-10->add_edge_by_id("component1", "elastic1", "ELASTICITY");
$ChacoboNonPermutableStrict_7-10->add_edge_by_id("elastic1", "MAXIMUM1-1", "MAXIMUM");
$ChacoboNonPermutableStrict_7-10->add_edge_by_id("elastic1", "MINIMUM0-1", "MINIMUM");
$ChacoboNonPermutableStrict_7-10->add_edge_by_id("component1", "open1", "FILLEDNESS");
$ChacoboNonPermutableStrict_7-10->add_edge_by_id("open1", "coherent1", "COHERENCE");
$ChacoboNonPermutableStrict_7-10->add_edge_by_id("component1", "stable1", "STABILITY");
$ChacoboNonPermutableStrict_7-10->add_edge_by_id("arch", "component2", "KEYSTONE");
$ChacoboNonPermutableStrict_7-10->add_edge_by_id("component2", "open2", "FILLEDNESS");
$ChacoboNonPermutableStrict_7-10->add_edge_by_id("open2", "coherent2", "COHERENCE");
$ChacoboNonPermutableStrict_7-10->add_edge_by_id("component2", "inelastic1", "ELASTICITY");
$ChacoboNonPermutableStrict_7-10->add_edge_by_id("inelastic1", "COUNT1-1", "COUNT");
$ChacoboNonPermutableStrict_7-10->add_edge_by_id("component2", "stable2", "STABILITY");
$ChacoboNonPermutableStrict_7-10->add_edge_by_id("arch", "component3", "RIGHT_SUPPORT");
$ChacoboNonPermutableStrict_7-10->add_edge_by_id("component3", "open3", "FILLEDNESS");
$ChacoboNonPermutableStrict_7-10->add_edge_by_id("open3", "coherent3", "COHERENCE");
$ChacoboNonPermutableStrict_7-10->add_edge_by_id("component3", "elastic2", "ELASTICITY");
$ChacoboNonPermutableStrict_7-10->add_edge_by_id("elastic2", "MAXIMUM1-2", "MAXIMUM");
$ChacoboNonPermutableStrict_7-10->add_edge_by_id("elastic2", "MINIMUM0-2", "MINIMUM");
$ChacoboNonPermutableStrict_7-10->add_edge_by_id("component3", "stable3", "STABILITY");
$ChacoboNonPermutableStrict_7-10->add_edge_by_id("arch", "component4", "RIGHT_VOUSSOIR");
$ChacoboNonPermutableStrict_7-10->add_edge_by_id("component4", "unstable1", "STABILITY");
$ChacoboNonPermutableStrict_7-10->add_edge_by_id("unstable1", "component1", "ASSOCIATE");
$ChacoboNonPermutableStrict_7-10->add_edge_by_id("unstable1", "left", "ASSOCIATE_POSITION");
$ChacoboNonPermutableStrict_7-10->add_edge_by_id("component4", "open4", "FILLEDNESS");
$ChacoboNonPermutableStrict_7-10->add_edge_by_id("open4", "coherent4", "COHERENCE");
$ChacoboNonPermutableStrict_7-10->add_edge_by_id("component4", "elastic3", "ELASTICITY");
$ChacoboNonPermutableStrict_7-10->add_edge_by_id("elastic3", "MAXIMUM1-3", "MAXIMUM");
$ChacoboNonPermutableStrict_7-10->add_edge_by_id("elastic3", "MINIMUM0-3", "MINIMUM");
$ChacoboNonPermutableStrict_7-10->add_edge_by_id("arch", "component1", "LEFT_SUPPORT");
$ChacoboNonPermutableStrict_7-10->add_edge_by_id("desmeme", "constructionalConditioning", "CONDITIONING");
$ChacoboNonPermutableStrict_7-10->add_edge_by_id("desmeme", "order", "STRICTURE");
$ChacoboNonPermutableStrict_7-10->add_edge_by_id("order", "COUNT4-1", "COUNT");
$ChacoboNonPermutableStrict_7-10->add_edge_by_id("order", "simple", "RELATIONS");
$ChacoboNonPermutableStrict_7-10->add_edge_by_id("order", "morphologicalConstituent", "CONSTITUENT");
$templateGraphs{ChacoboNonPermutableStrict_7-10} = $ChacoboNonPermutableStrict_7-10;

my $ChacoboNonPermutableScopal_7-15 = Graph->new(multiedged => 1);
$ChacoboNonPermutableScopal_7-15->set_graph_attribute("name", "ChacoboNonPermutableScopal_7-15");
$ChacoboNonPermutableScopal_7-15->add_edge_by_id("desmeme", "constructionalConditioning", "CONDITIONING");
$ChacoboNonPermutableScopal_7-15->add_edge_by_id("desmeme", "notViolable", "VIOLABILITY");
$ChacoboNonPermutableScopal_7-15->add_edge_by_id("desmeme", "order", "STRICTURE");
$ChacoboNonPermutableScopal_7-15->add_edge_by_id("order", "morphologicalConstituent", "CONSTITUENT");
$ChacoboNonPermutableScopal_7-15->add_edge_by_id("order", "COUNT9-1", "COUNT");
$ChacoboNonPermutableScopal_7-15->add_edge_by_id("order", "simple", "RELATIONS");
$ChacoboNonPermutableScopal_7-15->add_edge_by_id("desmeme", "arch", "FOUNDATION");
$ChacoboNonPermutableScopal_7-15->add_edge_by_id("arch", "component1", "RIGHT_VOUSSOIR");
$ChacoboNonPermutableScopal_7-15->add_edge_by_id("component1", "unstable1", "STABILITY");
$ChacoboNonPermutableScopal_7-15->add_edge_by_id("unstable1", "component2", "ASSOCIATE");
$ChacoboNonPermutableScopal_7-15->add_edge_by_id("component2", "elastic1", "ELASTICITY");
$ChacoboNonPermutableScopal_7-15->add_edge_by_id("elastic1", "MAXIMUM1-1", "MAXIMUM");
$ChacoboNonPermutableScopal_7-15->add_edge_by_id("elastic1", "MINIMUM0-1", "MINIMUM");
$ChacoboNonPermutableScopal_7-15->add_edge_by_id("component2", "open1", "FILLEDNESS");
$ChacoboNonPermutableScopal_7-15->add_edge_by_id("open1", "coherent1", "COHERENCE");
$ChacoboNonPermutableScopal_7-15->add_edge_by_id("component2", "stable1", "STABILITY");
$ChacoboNonPermutableScopal_7-15->add_edge_by_id("unstable1", "left", "ASSOCIATE_POSITION");
$ChacoboNonPermutableScopal_7-15->add_edge_by_id("component1", "open2", "FILLEDNESS");
$ChacoboNonPermutableScopal_7-15->add_edge_by_id("open2", "coherent2", "COHERENCE");
$ChacoboNonPermutableScopal_7-15->add_edge_by_id("component1", "elastic2", "ELASTICITY");
$ChacoboNonPermutableScopal_7-15->add_edge_by_id("elastic2", "MAXIMUM1-2", "MAXIMUM");
$ChacoboNonPermutableScopal_7-15->add_edge_by_id("elastic2", "MINIMUM0-2", "MINIMUM");
$ChacoboNonPermutableScopal_7-15->add_edge_by_id("arch", "component3", "RIGHT_SUPPORT");
$ChacoboNonPermutableScopal_7-15->add_edge_by_id("component3", "elastic3", "ELASTICITY");
$ChacoboNonPermutableScopal_7-15->add_edge_by_id("elastic3", "MAXIMUM1-3", "MAXIMUM");
$ChacoboNonPermutableScopal_7-15->add_edge_by_id("elastic3", "MINIMUM0-3", "MINIMUM");
$ChacoboNonPermutableScopal_7-15->add_edge_by_id("component3", "stable2", "STABILITY");
$ChacoboNonPermutableScopal_7-15->add_edge_by_id("component3", "filled1", "FILLEDNESS");
$ChacoboNonPermutableScopal_7-15->add_edge_by_id("filled1", "canonicalLineate1", "FORM");
$ChacoboNonPermutableScopal_7-15->add_edge_by_id("arch", "component2", "LEFT_SUPPORT");
$ChacoboNonPermutableScopal_7-15->add_edge_by_id("arch", "component2", "LEFT_VOUSSOIR");
$ChacoboNonPermutableScopal_7-15->add_edge_by_id("arch", "restkomponentenSet", "RESTKOMPONENTEN");
$ChacoboNonPermutableScopal_7-15->add_edge_by_id("restkomponentenSet", "component4", "RESTKOMPONENTE");
$ChacoboNonPermutableScopal_7-15->add_edge_by_id("component4", "elastic4", "ELASTICITY");
$ChacoboNonPermutableScopal_7-15->add_edge_by_id("elastic4", "MINIMUM0-4", "MINIMUM");
$ChacoboNonPermutableScopal_7-15->add_edge_by_id("elastic4", "MAXIMUM2-1", "MAXIMUM");
$ChacoboNonPermutableScopal_7-15->add_edge_by_id("component4", "open3", "FILLEDNESS");
$ChacoboNonPermutableScopal_7-15->add_edge_by_id("open3", "coherent3", "COHERENCE");
$ChacoboNonPermutableScopal_7-15->add_edge_by_id("component4", "stable3", "STABILITY");
$ChacoboNonPermutableScopal_7-15->add_edge_by_id("restkomponentenSet", "component5", "RESTKOMPONENTE");
$ChacoboNonPermutableScopal_7-15->add_edge_by_id("component5", "open4", "FILLEDNESS");
$ChacoboNonPermutableScopal_7-15->add_edge_by_id("open4", "coherent4", "COHERENCE");
$ChacoboNonPermutableScopal_7-15->add_edge_by_id("component5", "elastic5", "ELASTICITY");
$ChacoboNonPermutableScopal_7-15->add_edge_by_id("elastic5", "MINIMUM0-5", "MINIMUM");
$ChacoboNonPermutableScopal_7-15->add_edge_by_id("elastic5", "MAXIMUM3-1", "MAXIMUM");
$ChacoboNonPermutableScopal_7-15->add_edge_by_id("component5", "stable4", "STABILITY");
$ChacoboNonPermutableScopal_7-15->add_edge_by_id("restkomponentenSet", "component6", "RESTKOMPONENTE");
$ChacoboNonPermutableScopal_7-15->add_edge_by_id("component6", "filled2", "FILLEDNESS");
$ChacoboNonPermutableScopal_7-15->add_edge_by_id("filled2", "canonicalLineate2", "FORM");
$ChacoboNonPermutableScopal_7-15->add_edge_by_id("component6", "elastic6", "ELASTICITY");
$ChacoboNonPermutableScopal_7-15->add_edge_by_id("elastic6", "MAXIMUM1-4", "MAXIMUM");
$ChacoboNonPermutableScopal_7-15->add_edge_by_id("elastic6", "MINIMUM0-6", "MINIMUM");
$ChacoboNonPermutableScopal_7-15->add_edge_by_id("component6", "stable5", "STABILITY");
$ChacoboNonPermutableScopal_7-15->add_edge_by_id("restkomponentenSet", "component7", "RESTKOMPONENTE");
$ChacoboNonPermutableScopal_7-15->add_edge_by_id("component7", "elastic7", "ELASTICITY");
$ChacoboNonPermutableScopal_7-15->add_edge_by_id("elastic7", "MINIMUM0-7", "MINIMUM");
$ChacoboNonPermutableScopal_7-15->add_edge_by_id("elastic7", "MAXIMUM1-5", "MAXIMUM");
$ChacoboNonPermutableScopal_7-15->add_edge_by_id("component7", "stable6", "STABILITY");
$ChacoboNonPermutableScopal_7-15->add_edge_by_id("component7", "open5", "FILLEDNESS");
$ChacoboNonPermutableScopal_7-15->add_edge_by_id("open5", "coherent5", "COHERENCE");
$ChacoboNonPermutableScopal_7-15->add_edge_by_id("restkomponentenSet", "component8", "RESTKOMPONENTE");
$ChacoboNonPermutableScopal_7-15->add_edge_by_id("component8", "open6", "FILLEDNESS");
$ChacoboNonPermutableScopal_7-15->add_edge_by_id("open6", "coherent6", "COHERENCE");
$ChacoboNonPermutableScopal_7-15->add_edge_by_id("component8", "elastic8", "ELASTICITY");
$ChacoboNonPermutableScopal_7-15->add_edge_by_id("elastic8", "MAXIMUM1-6", "MAXIMUM");
$ChacoboNonPermutableScopal_7-15->add_edge_by_id("elastic8", "MINIMUM0-8", "MINIMUM");
$ChacoboNonPermutableScopal_7-15->add_edge_by_id("component8", "stable7", "STABILITY");
$ChacoboNonPermutableScopal_7-15->add_edge_by_id("arch", "component9", "KEYSTONE");
$ChacoboNonPermutableScopal_7-15->add_edge_by_id("component9", "open7", "FILLEDNESS");
$ChacoboNonPermutableScopal_7-15->add_edge_by_id("open7", "coherent7", "COHERENCE");
$ChacoboNonPermutableScopal_7-15->add_edge_by_id("component9", "inelastic1", "ELASTICITY");
$ChacoboNonPermutableScopal_7-15->add_edge_by_id("inelastic1", "COUNT1-1", "COUNT");
$ChacoboNonPermutableScopal_7-15->add_edge_by_id("component9", "stable8", "STABILITY");
$templateGraphs{ChacoboNonPermutableScopal_7-15} = $ChacoboNonPermutableScopal_7-15;

my @templates = ("ChacoboApocope_1-24", "ChacoboBodyPartPfxVerbTrans_7-9", "ChacoboDoTakeDrinkKillLatent_7-24", "ChacoboGlottalStopMax_7-19", "ChacoboGlottalStopMin_7-8", "ChacoboGrabGetLatent_7-24", "ChacoboHighToneInsertion_7-13", "ChacoboHighToneReduction_6-27", "ChacoboMinimality_7-10", "ChacoboNonInterruptableBySimple_7-11", "ChacoboNonInterruptibleByNP_7-19", "ChacoboNonPermutableScopal_7-15", "ChacoboNonPermutableStrict_7-10");
my @templatesCopy = @templates;

open (NULL, '>FloodingSimilarities.txt');  #Erase file
my %seenPairs = { };
for my $templateName1 (@templates) {

	for my $templateName2 (@templatesCopy) {

		if ($seenPairs{$templateName2."/".$templateName1}) { print next; }

		# Initialize simList for calculating Euclidean distances.
		my $initialS = new GraphJG::SimilarityJG(graph => [$templateGraphs{$templateName1}, $templateGraphs{$templateName2}]);
		my $initialMethod = $initialS->use('SimilarityFlooding');
		$initialMethod->setNumOfIteration(1);
		$initialMethod->calculate();
		my %simList = $initialMethod->getAllSimilarities;
	
		print "$templateName1/$templateName2\n";

		# Keep incrementing the iteration until we reach Euclidean distance of less than or equal to .05. Start at 2 to get difference from initial condition.
		for (my $count = 2; $count <=100; $count++) {

			my $s = new GraphJG::SimilarityJG(graph => [$templateGraphs{$templateName1}, $templateGraphs{$templateName2}]);
			my $method = $s->use('SimilarityFlooding');
			$method->setNumOfIteration($count);
			$method->calculate();

			my %newSimList = $method->getAllSimilarities;

			my @dists;
			for my $v (keys(%simList)) {
				# This is messy: We run through the paired graph to see if this paired node is in any subgraph.
				# "Free-floating" nodes get ignored for the purposes of calculating the Euclidean distance.
				# Appears to not actually make a difference if epsilon is set to .05 since the residuals converge pretty quickly to nearly the same. This is because free-floating nodes rapidly get a score close to zero.
				my $pcg = $method->pcg;
				my @pairedvs = $pcg->vertices();
				for my $pairedv (@pairedvs) {
					if($v eq $pairedv) {
						my $oldSim = $simList{$v};
						my $newSim = $newSimList{$v};
						my $diff = $oldSim - $newSim;
						push(@dists,$diff);
						last;
						}
					}
				}
	
			my $eucSum;
			for my $dist (@dists) {	
				$eucSum += $dist*$dist;
				}
	
			my $eucDist = sqrt($eucSum);
			print "$count: $eucDist\n";
	
			if ($eucDist < .05) {
	 			$method->getLargeSimilarities($templateName1,$templateName2);
 				$seenPairs{$templateName1."/".$templateName2} = 1;
				last;
				}
	
			%simList = %newSimList;
	
			}
		}
	}
