my $NimboranVerb = Graph->new(multiedged => 1);
$NimboranVerb->set_graph_attribute("name", "NimboranVerb");
$NimboranVerb->add_edge_by_id("desmeme", "potentiallyViolable", "VIOLABILITY");
$NimboranVerb->add_edge_by_id("desmeme", "order", "STRICTURE");
$NimboranVerb->add_edge_by_id("desmeme", "constructionalConditioning", "CONDITIONING");
$NimboranVerb->add_edge_by_id("desmeme", "span", "FOUNDATION");
$NimboranVerb->add_edge_by_id("elastic2", "MINIMUM0-2", "MINIMUM");
$NimboranVerb->add_edge_by_id("elastic2", "MAXIMUM1-2", "MAXIMUM");
$NimboranVerb->add_edge_by_id("elastic3", "MINIMUM0-3", "MINIMUM");
$NimboranVerb->add_edge_by_id("elastic3", "MAXIMUM1-3", "MAXIMUM");
$NimboranVerb->add_edge_by_id("elastic1", "MINIMUM0-1", "MINIMUM");
$NimboranVerb->add_edge_by_id("elastic1", "MAXIMUM1-1", "MAXIMUM");
$NimboranVerb->add_edge_by_id("filled3", "canonicalLineate3", "FORM");
$NimboranVerb->add_edge_by_id("filled2", "canonicalLineate2", "FORM");
$NimboranVerb->add_edge_by_id("filled1", "canonicalLineate1", "FORM");
$NimboranVerb->add_edge_by_id("elastic4", "MINIMUM0-4", "MINIMUM");
$NimboranVerb->add_edge_by_id("elastic4", "MAXIMUM1-4", "MAXIMUM");
$NimboranVerb->add_edge_by_id("span", "component1", "RIGHT_SUPPORT");
$NimboranVerb->add_edge_by_id("span", "restkomponentenSet", "RESTKOMPONENTEN");
$NimboranVerb->add_edge_by_id("span", "component7", "LEFT_SUPPORT");
$NimboranVerb->add_edge_by_id("component5", "filled2", "FILLEDNESS");
$NimboranVerb->add_edge_by_id("component5", "elastic3", "ELASTICITY");
$NimboranVerb->add_edge_by_id("component5", "stable4", "STABILITY");
$NimboranVerb->add_edge_by_id("component4", "open3", "FILLEDNESS");
$NimboranVerb->add_edge_by_id("component4", "elastic2", "ELASTICITY");
$NimboranVerb->add_edge_by_id("component4", "stable3", "STABILITY");
$NimboranVerb->add_edge_by_id("component7", "open4", "FILLEDNESS");
$NimboranVerb->add_edge_by_id("component7", "elastic5", "ELASTICITY");
$NimboranVerb->add_edge_by_id("component7", "stable6", "STABILITY");
$NimboranVerb->add_edge_by_id("component6", "filled3", "FILLEDNESS");
$NimboranVerb->add_edge_by_id("component6", "elastic4", "ELASTICITY");
$NimboranVerb->add_edge_by_id("component6", "stable5", "STABILITY");
$NimboranVerb->add_edge_by_id("component1", "open1", "FILLEDNESS");
$NimboranVerb->add_edge_by_id("component1", "inelastic1", "ELASTICITY");
$NimboranVerb->add_edge_by_id("component1", "stable1", "STABILITY");
$NimboranVerb->add_edge_by_id("component2", "filled1", "FILLEDNESS");
$NimboranVerb->add_edge_by_id("component2", "elastic1", "ELASTICITY");
$NimboranVerb->add_edge_by_id("component2", "stable2", "STABILITY");
$NimboranVerb->add_edge_by_id("component3", "open2", "FILLEDNESS");
$NimboranVerb->add_edge_by_id("component3", "inelastic2", "ELASTICITY");
$NimboranVerb->add_edge_by_id("component3", "unstable1", "STABILITY");
$NimboranVerb->add_edge_by_id("elastic5", "MINIMUM0-5", "MINIMUM");
$NimboranVerb->add_edge_by_id("elastic5", "MAXIMUM1-5", "MAXIMUM");
$NimboranVerb->add_edge_by_id("unstable1", "left", "ASSOCIATE_POSITION");
$NimboranVerb->add_edge_by_id("unstable1", "component4", "ASSOCIATE");
$NimboranVerb->add_edge_by_id("inelastic1", "COUNT1-1", "COUNT");
$NimboranVerb->add_edge_by_id("potentiallyViolable", "homophony", "REPARABILITY");
$NimboranVerb->add_edge_by_id("potentiallyViolable", "noKnownExceptions", "EXCEPTIONALITY");
$NimboranVerb->add_edge_by_id("inelastic2", "COUNT1-2", "COUNT");
$NimboranVerb->add_edge_by_id("restkomponentenSet", "component2", "RESTKOMPONENT");
$NimboranVerb->add_edge_by_id("restkomponentenSet", "component3", "RESTKOMPONENT");
$NimboranVerb->add_edge_by_id("restkomponentenSet", "component4", "RESTKOMPONENT");
$NimboranVerb->add_edge_by_id("restkomponentenSet", "component5", "RESTKOMPONENT");
$NimboranVerb->add_edge_by_id("restkomponentenSet", "component6", "RESTKOMPONENT");
$NimboranVerb->add_edge_by_id("open4", "incoherent1", "COHERENCE");
$NimboranVerb->add_edge_by_id("open1", "coherent1", "COHERENCE");
$NimboranVerb->add_edge_by_id("order", "taxonomic", "RELATIONS");
$NimboranVerb->add_edge_by_id("order", "morphologicalConstituent", "CONSTITUENT");
$NimboranVerb->add_edge_by_id("order", "COUNT7-1", "COUNT");
$NimboranVerb->add_edge_by_id("open3", "coherent3", "COHERENCE");
$NimboranVerb->add_edge_by_id("open2", "coherent2", "COHERENCE");

$x = "27";

my @templates = ("AghemClause", "BantuCA", "BantuCT", "BantuVCy", "ChechenPreverbalA", "ChichewaAR", "ChintangPrefixes", "EnglishPlural", "EnglishVP", "GermanClause", "MandeClause", "MeskwakiClause", "NdebeleCA", "NimboranVerb", "SerboCroatianJe", "SerboCroatianTopicalization", "TieneVerbProsodic", "TieneVerbSegments", "TurkishNominalMinimality", "TurkishVerbalMinimality");

1;