#! /usr/bin/perl
use strict;
use FindBin;
use lib "$FindBin::Bin/.";
use GraphJG::SimilarityJG;


my %templateGraphs = {};

my $ChichewaNiEnclitic-CLT = Graph->new(multiedged => 1);
$ChichewaNiEnclitic-CLT->set_graph_attribute("name", "ChichewaNiEnclitic-CLT");
$ChichewaNiEnclitic-CLT->add_edge_by_id("desmeme", "order", "STRICTURE");
$ChichewaNiEnclitic-CLT->add_edge_by_id("order", "simple", "RELATIONS");
$ChichewaNiEnclitic-CLT->add_edge_by_id("order", "COUNT2-1", "COUNT");
$ChichewaNiEnclitic-CLT->add_edge_by_id("order", "morphologicalConstituent", "CONSTITUENT");
$ChichewaNiEnclitic-CLT->add_edge_by_id("desmeme", "notViolable", "VIOLABILITY");
$ChichewaNiEnclitic-CLT->add_edge_by_id("desmeme", "lexicoconstructionalConditioning", "CONDITIONING");
$ChichewaNiEnclitic-CLT->add_edge_by_id("lexicoconstructionalConditioning", "filledComponentSet", "FILLED_COMPONENTS");
$ChichewaNiEnclitic-CLT->add_edge_by_id("filledComponentSet", "component1", "FILLED_COMPONENT");
$ChichewaNiEnclitic-CLT->add_edge_by_id("component1", "filled1", "FILLEDNESS");
$ChichewaNiEnclitic-CLT->add_edge_by_id("filled1", "canonicalLineate1", "FORM");
$ChichewaNiEnclitic-CLT->add_edge_by_id("component1", "inelastic1", "ELASTICITY");
$ChichewaNiEnclitic-CLT->add_edge_by_id("inelastic1", "COUNT1-1", "COUNT");
$ChichewaNiEnclitic-CLT->add_edge_by_id("component1", "stable1", "STABILITY");
$ChichewaNiEnclitic-CLT->add_edge_by_id("lexicoconstructionalConditioning", "templateFinal", "FILLER_POSITION");
$ChichewaNiEnclitic-CLT->add_edge_by_id("desmeme", "span", "FOUNDATION");
$ChichewaNiEnclitic-CLT->add_edge_by_id("span", "component2", "LEFT_SUPPORT");
$ChichewaNiEnclitic-CLT->add_edge_by_id("component2", "stable2", "STABILITY");
$ChichewaNiEnclitic-CLT->add_edge_by_id("component2", "inelastic2", "ELASTICITY");
$ChichewaNiEnclitic-CLT->add_edge_by_id("inelastic2", "COUNT1-2", "COUNT");
$ChichewaNiEnclitic-CLT->add_edge_by_id("component2", "open1", "FILLEDNESS");
$ChichewaNiEnclitic-CLT->add_edge_by_id("open1", "coherent1", "COHERENCE");
$ChichewaNiEnclitic-CLT->add_edge_by_id("span", "component1", "RIGHT_SUPPORT");
$templateGraphs{ChichewaNiEnclitic-CLT} = $ChichewaNiEnclitic-CLT;

my $ChichewaORelative-CLT = Graph->new(multiedged => 1);
$ChichewaORelative-CLT->set_graph_attribute("name", "ChichewaORelative-CLT");
$ChichewaORelative-CLT->add_edge_by_id("desmeme", "notViolable", "VIOLABILITY");
$ChichewaORelative-CLT->add_edge_by_id("desmeme", "lexicoconstructionalConditioning", "CONDITIONING");
$ChichewaORelative-CLT->add_edge_by_id("lexicoconstructionalConditioning", "filledComponentSet", "FILLED_COMPONENTS");
$ChichewaORelative-CLT->add_edge_by_id("filledComponentSet", "component1", "FILLED_COMPONENT");
$ChichewaORelative-CLT->add_edge_by_id("component1", "partiallyFilled1", "FILLEDNESS");
$ChichewaORelative-CLT->add_edge_by_id("partiallyFilled1", "coherent1", "COHERENCE");
$ChichewaORelative-CLT->add_edge_by_id("partiallyFilled1", "componentFinal", "FILLER_PLACEMENT");
$ChichewaORelative-CLT->add_edge_by_id("partiallyFilled1", "embeddedDesmeme", "FORM");
$ChichewaORelative-CLT->add_edge_by_id("component1", "inelastic1", "ELASTICITY");
$ChichewaORelative-CLT->add_edge_by_id("inelastic1", "COUNT1-1", "COUNT");
$ChichewaORelative-CLT->add_edge_by_id("component1", "stable1", "STABILITY");
$ChichewaORelative-CLT->add_edge_by_id("lexicoconstructionalConditioning", "templateFinal", "FILLER_POSITION");
$ChichewaORelative-CLT->add_edge_by_id("desmeme", "order", "STRICTURE");
$ChichewaORelative-CLT->add_edge_by_id("order", "COUNT2-1", "COUNT");
$ChichewaORelative-CLT->add_edge_by_id("order", "morphologicalConstituent", "CONSTITUENT");
$ChichewaORelative-CLT->add_edge_by_id("order", "simple", "RELATIONS");
$ChichewaORelative-CLT->add_edge_by_id("desmeme", "span", "FOUNDATION");
$ChichewaORelative-CLT->add_edge_by_id("span", "component1", "RIGHT_SUPPORT");
$ChichewaORelative-CLT->add_edge_by_id("span", "component2", "LEFT_SUPPORT");
$ChichewaORelative-CLT->add_edge_by_id("component2", "open1", "FILLEDNESS");
$ChichewaORelative-CLT->add_edge_by_id("open1", "coherent2", "COHERENCE");
$ChichewaORelative-CLT->add_edge_by_id("component2", "inelastic2", "ELASTICITY");
$ChichewaORelative-CLT->add_edge_by_id("inelastic2", "COUNT1-2", "COUNT");
$ChichewaORelative-CLT->add_edge_by_id("component2", "stable2", "STABILITY");
$templateGraphs{ChichewaORelative-CLT} = $ChichewaORelative-CLT;

my $ChichewaSyllable-PHON = Graph->new(multiedged => 1);
$ChichewaSyllable-PHON->set_graph_attribute("name", "ChichewaSyllable-PHON");
$ChichewaSyllable-PHON->add_edge_by_id("desmeme", "potentiallyViolable", "VIOLABILITY");
$ChichewaSyllable-PHON->add_edge_by_id("potentiallyViolable", "noKnownExceptions", "EXCEPTIONALITY");
$ChichewaSyllable-PHON->add_edge_by_id("potentiallyViolable", "phonologicalRepair", "REPARABILITY");
$ChichewaSyllable-PHON->add_edge_by_id("desmeme", "prosodicConditioning", "CONDITIONING");
$ChichewaSyllable-PHON->add_edge_by_id("desmeme", "span", "FOUNDATION");
$ChichewaSyllable-PHON->add_edge_by_id("span", "restkomponentenSet", "RESTKOMPONENTEN");
$ChichewaSyllable-PHON->add_edge_by_id("restkomponentenSet", "component1", "RESTKOMPONENTE");
$ChichewaSyllable-PHON->add_edge_by_id("component1", "elastic1", "ELASTICITY");
$ChichewaSyllable-PHON->add_edge_by_id("elastic1", "MAXIMUM1-1", "MAXIMUM");
$ChichewaSyllable-PHON->add_edge_by_id("elastic1", "MINIMUM0-1", "MINIMUM");
$ChichewaSyllable-PHON->add_edge_by_id("component1", "open1", "FILLEDNESS");
$ChichewaSyllable-PHON->add_edge_by_id("open1", "incoherent1", "COHERENCE");
$ChichewaSyllable-PHON->add_edge_by_id("component1", "unstable1", "STABILITY");
$ChichewaSyllable-PHON->add_edge_by_id("unstable1", "left", "ASSOCIATE_POSITION");
$ChichewaSyllable-PHON->add_edge_by_id("unstable1", "component2", "ASSOCIATE");
$ChichewaSyllable-PHON->add_edge_by_id("component2", "elastic2", "ELASTICITY");
$ChichewaSyllable-PHON->add_edge_by_id("elastic2", "MAXIMUM1-2", "MAXIMUM");
$ChichewaSyllable-PHON->add_edge_by_id("elastic2", "MINIMUM0-2", "MINIMUM");
$ChichewaSyllable-PHON->add_edge_by_id("component2", "open2", "FILLEDNESS");
$ChichewaSyllable-PHON->add_edge_by_id("open2", "coherent1", "COHERENCE");
$ChichewaSyllable-PHON->add_edge_by_id("component2", "unstable2", "STABILITY");
$ChichewaSyllable-PHON->add_edge_by_id("unstable2", "right", "ASSOCIATE_POSITION");
$ChichewaSyllable-PHON->add_edge_by_id("unstable2", "component1", "ASSOCIATE");
$ChichewaSyllable-PHON->add_edge_by_id("span", "component2", "LEFT_SUPPORT");
$ChichewaSyllable-PHON->add_edge_by_id("span", "component3", "RIGHT_SUPPORT");
$ChichewaSyllable-PHON->add_edge_by_id("component3", "open3", "FILLEDNESS");
$ChichewaSyllable-PHON->add_edge_by_id("open3", "coherent2", "COHERENCE");
$ChichewaSyllable-PHON->add_edge_by_id("component3", "inelastic1", "ELASTICITY");
$ChichewaSyllable-PHON->add_edge_by_id("inelastic1", "COUNT1-1", "COUNT");
$ChichewaSyllable-PHON->add_edge_by_id("component3", "stable1", "STABILITY");
$ChichewaSyllable-PHON->add_edge_by_id("desmeme", "order", "STRICTURE");
$ChichewaSyllable-PHON->add_edge_by_id("order", "simple", "RELATIONS");
$ChichewaSyllable-PHON->add_edge_by_id("order", "COUNT2-1", "COUNT");
$ChichewaSyllable-PHON->add_edge_by_id("order", "segment", "CONSTITUENT");
$templateGraphs{ChichewaSyllable-PHON} = $ChichewaSyllable-PHON;

my $ChichewaNeg1Verb-PhMOR = Graph->new(multiedged => 1);
$ChichewaNeg1Verb-PhMOR->set_graph_attribute("name", "ChichewaNeg1Verb-PhMOR");
$ChichewaNeg1Verb-PhMOR->add_edge_by_id("desmeme", "span", "FOUNDATION");
$ChichewaNeg1Verb-PhMOR->add_edge_by_id("span", "component1", "LEFT_SUPPORT");
$ChichewaNeg1Verb-PhMOR->add_edge_by_id("component1", "elastic1", "ELASTICITY");
$ChichewaNeg1Verb-PhMOR->add_edge_by_id("elastic1", "MAXIMUM1-1", "MAXIMUM");
$ChichewaNeg1Verb-PhMOR->add_edge_by_id("elastic1", "MINIMUM0-1", "MINIMUM");
$ChichewaNeg1Verb-PhMOR->add_edge_by_id("component1", "filled1", "FILLEDNESS");
$ChichewaNeg1Verb-PhMOR->add_edge_by_id("filled1", "canonicalLineate1", "FORM");
$ChichewaNeg1Verb-PhMOR->add_edge_by_id("component1", "stable1", "STABILITY");
$ChichewaNeg1Verb-PhMOR->add_edge_by_id("span", "component2", "RIGHT_SUPPORT");
$ChichewaNeg1Verb-PhMOR->add_edge_by_id("component2", "inelastic1", "ELASTICITY");
$ChichewaNeg1Verb-PhMOR->add_edge_by_id("inelastic1", "COUNT1-1", "COUNT");
$ChichewaNeg1Verb-PhMOR->add_edge_by_id("component2", "open1", "FILLEDNESS");
$ChichewaNeg1Verb-PhMOR->add_edge_by_id("open1", "coherent1", "COHERENCE");
$ChichewaNeg1Verb-PhMOR->add_edge_by_id("component2", "stable2", "STABILITY");
$ChichewaNeg1Verb-PhMOR->add_edge_by_id("desmeme", "order", "STRICTURE");
$ChichewaNeg1Verb-PhMOR->add_edge_by_id("order", "COUNT2-1", "COUNT");
$ChichewaNeg1Verb-PhMOR->add_edge_by_id("order", "morphologicalConstituent", "CONSTITUENT");
$ChichewaNeg1Verb-PhMOR->add_edge_by_id("order", "simple", "RELATIONS");
$ChichewaNeg1Verb-PhMOR->add_edge_by_id("desmeme", "notViolable", "VIOLABILITY");
$ChichewaNeg1Verb-PhMOR->add_edge_by_id("desmeme", "constructionalConditioning", "CONDITIONING");
$templateGraphs{ChichewaNeg1Verb-PhMOR} = $ChichewaNeg1Verb-PhMOR;

my $ChichewaWordMinimality-PhMOR = Graph->new(multiedged => 1);
$ChichewaWordMinimality-PhMOR->set_graph_attribute("name", "ChichewaWordMinimality-PhMOR");
$ChichewaWordMinimality-PhMOR->add_edge_by_id("desmeme", "length", "STRICTURE");
$ChichewaWordMinimality-PhMOR->add_edge_by_id("length", "Syllable", "CONSTITUENT");
$ChichewaWordMinimality-PhMOR->add_edge_by_id("length", "COUNT2-1", "COUNT");
$ChichewaWordMinimality-PhMOR->add_edge_by_id("desmeme", "prosodicConditioning", "CONDITIONING");
$ChichewaWordMinimality-PhMOR->add_edge_by_id("desmeme", "span", "FOUNDATION");
$ChichewaWordMinimality-PhMOR->add_edge_by_id("span", "component1", "LEFT_SUPPORT");
$ChichewaWordMinimality-PhMOR->add_edge_by_id("component1", "elastic1", "ELASTICITY");
$ChichewaWordMinimality-PhMOR->add_edge_by_id("elastic1", "MINIMUM1-1", "MINIMUM");
$ChichewaWordMinimality-PhMOR->add_edge_by_id("elastic1", "MAXIMUM100-1", "MAXIMUM");
$ChichewaWordMinimality-PhMOR->add_edge_by_id("component1", "open1", "FILLEDNESS");
$ChichewaWordMinimality-PhMOR->add_edge_by_id("open1", "coherent1", "COHERENCE");
$ChichewaWordMinimality-PhMOR->add_edge_by_id("component1", "stable1", "STABILITY");
$ChichewaWordMinimality-PhMOR->add_edge_by_id("span", "component2", "RIGHT_SUPPORT");
$ChichewaWordMinimality-PhMOR->add_edge_by_id("component2", "stable2", "STABILITY");
$ChichewaWordMinimality-PhMOR->add_edge_by_id("component2", "elastic2", "ELASTICITY");
$ChichewaWordMinimality-PhMOR->add_edge_by_id("elastic2", "MINIMUM1-2", "MINIMUM");
$ChichewaWordMinimality-PhMOR->add_edge_by_id("elastic2", "MAXIMUM100-2", "MAXIMUM");
$ChichewaWordMinimality-PhMOR->add_edge_by_id("component2", "open2", "FILLEDNESS");
$ChichewaWordMinimality-PhMOR->add_edge_by_id("open2", "coherent2", "COHERENCE");
$ChichewaWordMinimality-PhMOR->add_edge_by_id("desmeme", "potentiallyViolable", "VIOLABILITY");
$ChichewaWordMinimality-PhMOR->add_edge_by_id("potentiallyViolable", "noKnownExceptions", "EXCEPTIONALITY");
$ChichewaWordMinimality-PhMOR->add_edge_by_id("potentiallyViolable", "phonologicalInsertion", "REPARABILITY");
$templateGraphs{ChichewaWordMinimality-PhMOR} = $ChichewaWordMinimality-PhMOR;

my $ChacoboGlottalStop_7-8 = Graph->new(multiedged => 1);
$ChacoboGlottalStop_7-8->set_graph_attribute("name", "ChacoboGlottalStop_7-8");
$ChacoboGlottalStop_7-8->add_edge_by_id("desmeme", "notViolable", "VIOLABILITY");
$ChacoboGlottalStop_7-8->add_edge_by_id("desmeme", "juncture", "STRICTURE");
$ChacoboGlottalStop_7-8->add_edge_by_id("desmeme", "span", "FOUNDATION");
$ChacoboGlottalStop_7-8->add_edge_by_id("span", "component1", "RIGHT_SUPPORT");
$ChacoboGlottalStop_7-8->add_edge_by_id("component1", "inelastic1", "ELASTICITY");
$ChacoboGlottalStop_7-8->add_edge_by_id("inelastic1", "COUNT1-1", "COUNT");
$ChacoboGlottalStop_7-8->add_edge_by_id("component1", "open1", "FILLEDNESS");
$ChacoboGlottalStop_7-8->add_edge_by_id("open1", "coherent1", "COHERENCE");
$ChacoboGlottalStop_7-8->add_edge_by_id("component1", "stable1", "STABILITY");
$ChacoboGlottalStop_7-8->add_edge_by_id("span", "component2", "LEFT_SUPPORT");
$ChacoboGlottalStop_7-8->add_edge_by_id("component2", "stable2", "STABILITY");
$ChacoboGlottalStop_7-8->add_edge_by_id("component2", "elastic1", "ELASTICITY");
$ChacoboGlottalStop_7-8->add_edge_by_id("elastic1", "MINIMUM0-1", "MINIMUM");
$ChacoboGlottalStop_7-8->add_edge_by_id("elastic1", "MAXIMUM1-1", "MAXIMUM");
$ChacoboGlottalStop_7-8->add_edge_by_id("component2", "open2", "FILLEDNESS");
$ChacoboGlottalStop_7-8->add_edge_by_id("open2", "coherent2", "COHERENCE");
$ChacoboGlottalStop_7-8->add_edge_by_id("desmeme", "segmental", "CONDITIONING");
$templateGraphs{ChacoboGlottalStop_7-8} = $ChacoboGlottalStop_7-8;

my $ChichewaNoun-MOR = Graph->new(multiedged => 1);
$ChichewaNoun-MOR->set_graph_attribute("name", "ChichewaNoun-MOR");
$ChichewaNoun-MOR->add_edge_by_id("desmeme", "constructionalConditioning", "CONDITIONING");
$ChichewaNoun-MOR->add_edge_by_id("desmeme", "potentiallyViolable", "VIOLABILITY");
$ChichewaNoun-MOR->add_edge_by_id("potentiallyViolable", "surfaceViolable", "REPARABILITY");
$ChichewaNoun-MOR->add_edge_by_id("potentiallyViolable", "lexical", "EXCEPTIONALITY");
$ChichewaNoun-MOR->add_edge_by_id("desmeme", "order", "STRICTURE");
$ChichewaNoun-MOR->add_edge_by_id("order", "morphologicalConstituent", "CONSTITUENT");
$ChichewaNoun-MOR->add_edge_by_id("order", "COUNT2-1", "COUNT");
$ChichewaNoun-MOR->add_edge_by_id("order", "simple", "RELATIONS");
$ChichewaNoun-MOR->add_edge_by_id("desmeme", "span", "FOUNDATION");
$ChichewaNoun-MOR->add_edge_by_id("span", "component1", "RIGHT_SUPPORT");
$ChichewaNoun-MOR->add_edge_by_id("component1", "unstable1", "STABILITY");
$ChichewaNoun-MOR->add_edge_by_id("unstable1", "component2", "ASSOCIATE");
$ChichewaNoun-MOR->add_edge_by_id("component2", "unstable2", "STABILITY");
$ChichewaNoun-MOR->add_edge_by_id("unstable2", "component1", "ASSOCIATE");
$ChichewaNoun-MOR->add_edge_by_id("unstable2", "right", "ASSOCIATE_POSITION");
$ChichewaNoun-MOR->add_edge_by_id("component2", "open1", "FILLEDNESS");
$ChichewaNoun-MOR->add_edge_by_id("open1", "coherent1", "COHERENCE");
$ChichewaNoun-MOR->add_edge_by_id("component2", "inelastic1", "ELASTICITY");
$ChichewaNoun-MOR->add_edge_by_id("inelastic1", "COUNT1-1", "COUNT");
$ChichewaNoun-MOR->add_edge_by_id("unstable1", "left", "ASSOCIATE_POSITION");
$ChichewaNoun-MOR->add_edge_by_id("component1", "open2", "FILLEDNESS");
$ChichewaNoun-MOR->add_edge_by_id("open2", "coherent2", "COHERENCE");
$ChichewaNoun-MOR->add_edge_by_id("component1", "inelastic2", "ELASTICITY");
$ChichewaNoun-MOR->add_edge_by_id("inelastic2", "COUNT1-2", "COUNT");
$ChichewaNoun-MOR->add_edge_by_id("span", "component2", "LEFT_SUPPORT");
$templateGraphs{ChichewaNoun-MOR} = $ChichewaNoun-MOR;

my $ChichewaNominalReduplication-PhMOR = Graph->new(multiedged => 1);
$ChichewaNominalReduplication-PhMOR->set_graph_attribute("name", "ChichewaNominalReduplication-PhMOR");
$ChichewaNominalReduplication-PhMOR->add_edge_by_id("desmeme", "notViolable", "VIOLABILITY");
$ChichewaNominalReduplication-PhMOR->add_edge_by_id("desmeme", "order", "STRICTURE");
$ChichewaNominalReduplication-PhMOR->add_edge_by_id("order", "COUNT2-1", "COUNT");
$ChichewaNominalReduplication-PhMOR->add_edge_by_id("order", "morphologicalConstituent", "CONSTITUENT");
$ChichewaNominalReduplication-PhMOR->add_edge_by_id("order", "simple", "RELATIONS");
$ChichewaNominalReduplication-PhMOR->add_edge_by_id("desmeme", "span", "FOUNDATION");
$ChichewaNominalReduplication-PhMOR->add_edge_by_id("span", "component1", "RIGHT_SUPPORT");
$ChichewaNominalReduplication-PhMOR->add_edge_by_id("component1", "elastic1", "ELASTICITY");
$ChichewaNominalReduplication-PhMOR->add_edge_by_id("elastic1", "MINIMUM0-1", "MINIMUM");
$ChichewaNominalReduplication-PhMOR->add_edge_by_id("elastic1", "MAXIMUM1-1", "MAXIMUM");
$ChichewaNominalReduplication-PhMOR->add_edge_by_id("component1", "filled1", "FILLEDNESS");
$ChichewaNominalReduplication-PhMOR->add_edge_by_id("filled1", "reduplicant", "FORM");
$ChichewaNominalReduplication-PhMOR->add_edge_by_id("component1", "unstable1", "STABILITY");
$ChichewaNominalReduplication-PhMOR->add_edge_by_id("unstable1", "component2", "ASSOCIATE");
$ChichewaNominalReduplication-PhMOR->add_edge_by_id("component2", "open1", "FILLEDNESS");
$ChichewaNominalReduplication-PhMOR->add_edge_by_id("open1", "coherent1", "COHERENCE");
$ChichewaNominalReduplication-PhMOR->add_edge_by_id("component2", "stable1", "STABILITY");
$ChichewaNominalReduplication-PhMOR->add_edge_by_id("component2", "inelastic1", "ELASTICITY");
$ChichewaNominalReduplication-PhMOR->add_edge_by_id("inelastic1", "COUNT1-1", "COUNT");
$ChichewaNominalReduplication-PhMOR->add_edge_by_id("unstable1", "left", "ASSOCIATE_POSITION");
$ChichewaNominalReduplication-PhMOR->add_edge_by_id("span", "component2", "LEFT_SUPPORT");
$ChichewaNominalReduplication-PhMOR->add_edge_by_id("desmeme", "constructionalConditioning", "CONDITIONING");
$templateGraphs{ChichewaNominalReduplication-PhMOR} = $ChichewaNominalReduplication-PhMOR;

my $ChichewaImperative-MOR = Graph->new(multiedged => 1);
$ChichewaImperative-MOR->set_graph_attribute("name", "ChichewaImperative-MOR");
$ChichewaImperative-MOR->add_edge_by_id("desmeme", "order", "STRICTURE");
$ChichewaImperative-MOR->add_edge_by_id("order", "COUNT1-1", "COUNT");
$ChichewaImperative-MOR->add_edge_by_id("order", "simple", "RELATIONS");
$ChichewaImperative-MOR->add_edge_by_id("order", "morphologicalConstituent", "CONSTITUENT");
$ChichewaImperative-MOR->add_edge_by_id("desmeme", "arch", "FOUNDATION");
$ChichewaImperative-MOR->add_edge_by_id("arch", "component1", "LEFT_VOUSSOIR");
$ChichewaImperative-MOR->add_edge_by_id("component1", "null1", "FILLEDNESS");
$ChichewaImperative-MOR->add_edge_by_id("component1", "inelastic1", "ELASTICITY");
$ChichewaImperative-MOR->add_edge_by_id("inelastic1", "COUNT0-1", "COUNT");
$ChichewaImperative-MOR->add_edge_by_id("component1", "stable1", "STABILITY");
$ChichewaImperative-MOR->add_edge_by_id("arch", "component1", "RIGHT_VOUSSOIR");
$ChichewaImperative-MOR->add_edge_by_id("arch", "component2", "LEFT_SUPPORT");
$ChichewaImperative-MOR->add_edge_by_id("component2", "null2", "FILLEDNESS");
$ChichewaImperative-MOR->add_edge_by_id("component2", "stable2", "STABILITY");
$ChichewaImperative-MOR->add_edge_by_id("component2", "inelastic2", "ELASTICITY");
$ChichewaImperative-MOR->add_edge_by_id("inelastic2", "COUNT0-2", "COUNT");
$ChichewaImperative-MOR->add_edge_by_id("arch", "component3", "KEYSTONE");
$ChichewaImperative-MOR->add_edge_by_id("component3", "inelastic3", "ELASTICITY");
$ChichewaImperative-MOR->add_edge_by_id("inelastic3", "COUNT1-2", "COUNT");
$ChichewaImperative-MOR->add_edge_by_id("component3", "open1", "FILLEDNESS");
$ChichewaImperative-MOR->add_edge_by_id("open1", "coherent1", "COHERENCE");
$ChichewaImperative-MOR->add_edge_by_id("component3", "stable3", "STABILITY");
$ChichewaImperative-MOR->add_edge_by_id("arch", "component3", "RIGHT_SUPPORT");
$ChichewaImperative-MOR->add_edge_by_id("desmeme", "constructionalConditioning", "CONDITIONING");
$ChichewaImperative-MOR->add_edge_by_id("desmeme", "notViolable", "VIOLABILITY");
$templateGraphs{ChichewaImperative-MOR} = $ChichewaImperative-MOR;

my $ChichewaPhrase-PhSYN = Graph->new(multiedged => 1);
$ChichewaPhrase-PhSYN->set_graph_attribute("name", "ChichewaPhrase-PhSYN");
$ChichewaPhrase-PhSYN->add_edge_by_id("desmeme", "span", "FOUNDATION");
$ChichewaPhrase-PhSYN->add_edge_by_id("span", "component1", "LEFT_SUPPORT");
$ChichewaPhrase-PhSYN->add_edge_by_id("component1", "stable1", "STABILITY");
$ChichewaPhrase-PhSYN->add_edge_by_id("component1", "elastic1", "ELASTICITY");
$ChichewaPhrase-PhSYN->add_edge_by_id("elastic1", "MINIMUM0-1", "MINIMUM");
$ChichewaPhrase-PhSYN->add_edge_by_id("elastic1", "MAXIMUM100-1", "MAXIMUM");
$ChichewaPhrase-PhSYN->add_edge_by_id("component1", "open1", "FILLEDNESS");
$ChichewaPhrase-PhSYN->add_edge_by_id("open1", "coherent1", "COHERENCE");
$ChichewaPhrase-PhSYN->add_edge_by_id("span", "component2", "RIGHT_SUPPORT");
$ChichewaPhrase-PhSYN->add_edge_by_id("component2", "inelastic1", "ELASTICITY");
$ChichewaPhrase-PhSYN->add_edge_by_id("inelastic1", "COUNT1-1", "COUNT");
$ChichewaPhrase-PhSYN->add_edge_by_id("component2", "stable2", "STABILITY");
$ChichewaPhrase-PhSYN->add_edge_by_id("component2", "open2", "FILLEDNESS");
$ChichewaPhrase-PhSYN->add_edge_by_id("open2", "coherent2", "COHERENCE");
$ChichewaPhrase-PhSYN->add_edge_by_id("desmeme", "notViolable", "VIOLABILITY");
$ChichewaPhrase-PhSYN->add_edge_by_id("desmeme", "prosodicConditioning", "CONDITIONING");
$ChichewaPhrase-PhSYN->add_edge_by_id("desmeme", "order", "STRICTURE");
$ChichewaPhrase-PhSYN->add_edge_by_id("order", "COUNT2-1", "COUNT");
$ChichewaPhrase-PhSYN->add_edge_by_id("order", "prosodicPhrase", "CONSTITUENT");
$ChichewaPhrase-PhSYN->add_edge_by_id("order", "simple", "RELATIONS");
$templateGraphs{ChichewaPhrase-PhSYN} = $ChichewaPhrase-PhSYN;

my $ChichewaRelativeClause-SYN = Graph->new(multiedged => 1);
$ChichewaRelativeClause-SYN->set_graph_attribute("name", "ChichewaRelativeClause-SYN");
$ChichewaRelativeClause-SYN->add_edge_by_id("desmeme", "span", "FOUNDATION");
$ChichewaRelativeClause-SYN->add_edge_by_id("span", "component1", "LEFT_SUPPORT");
$ChichewaRelativeClause-SYN->add_edge_by_id("component1", "elastic1", "ELASTICITY");
$ChichewaRelativeClause-SYN->add_edge_by_id("elastic1", "MAXIMUM1-1", "MAXIMUM");
$ChichewaRelativeClause-SYN->add_edge_by_id("elastic1", "MINIMUM0-1", "MINIMUM");
$ChichewaRelativeClause-SYN->add_edge_by_id("component1", "stable1", "STABILITY");
$ChichewaRelativeClause-SYN->add_edge_by_id("component1", "partiallyFilled1", "FILLEDNESS");
$ChichewaRelativeClause-SYN->add_edge_by_id("partiallyFilled1", "coherent1", "COHERENCE");
$ChichewaRelativeClause-SYN->add_edge_by_id("partiallyFilled1", "embeddedDesmeme", "FORM");
$ChichewaRelativeClause-SYN->add_edge_by_id("partiallyFilled1", "componentFinal", "FILLER_PLACEMENT");
$ChichewaRelativeClause-SYN->add_edge_by_id("span", "component2", "RIGHT_SUPPORT");
$ChichewaRelativeClause-SYN->add_edge_by_id("component2", "open1", "FILLEDNESS");
$ChichewaRelativeClause-SYN->add_edge_by_id("open1", "coherent2", "COHERENCE");
$ChichewaRelativeClause-SYN->add_edge_by_id("component2", "inelastic1", "ELASTICITY");
$ChichewaRelativeClause-SYN->add_edge_by_id("inelastic1", "COUNT1-1", "COUNT");
$ChichewaRelativeClause-SYN->add_edge_by_id("component2", "stable2", "STABILITY");
$ChichewaRelativeClause-SYN->add_edge_by_id("desmeme", "constructionalConditioning", "CONDITIONING");
$ChichewaRelativeClause-SYN->add_edge_by_id("desmeme", "order", "STRICTURE");
$ChichewaRelativeClause-SYN->add_edge_by_id("order", "simple", "RELATIONS");
$ChichewaRelativeClause-SYN->add_edge_by_id("order", "syntacticConstituent", "CONSTITUENT");
$ChichewaRelativeClause-SYN->add_edge_by_id("order", "COUNT2-1", "COUNT");
$ChichewaRelativeClause-SYN->add_edge_by_id("desmeme", "notViolable", "VIOLABILITY");
$templateGraphs{ChichewaRelativeClause-SYN} = $ChichewaRelativeClause-SYN;

my $ChichewaVerbWithImperatives-MOR = Graph->new(multiedged => 1);
$ChichewaVerbWithImperatives-MOR->set_graph_attribute("name", "ChichewaVerbWithImperatives-MOR");
$ChichewaVerbWithImperatives-MOR->add_edge_by_id("desmeme", "notViolable", "VIOLABILITY");
$ChichewaVerbWithImperatives-MOR->add_edge_by_id("desmeme", "order", "STRICTURE");
$ChichewaVerbWithImperatives-MOR->add_edge_by_id("order", "COUNT8-1", "COUNT");
$ChichewaVerbWithImperatives-MOR->add_edge_by_id("order", "taxonomic", "RELATIONS");
$ChichewaVerbWithImperatives-MOR->add_edge_by_id("order", "morphologicalConstituent", "CONSTITUENT");
$ChichewaVerbWithImperatives-MOR->add_edge_by_id("desmeme", "arch", "FOUNDATION");
$ChichewaVerbWithImperatives-MOR->add_edge_by_id("arch", "restkomponentenSet", "RESTKOMPONENTEN");
$ChichewaVerbWithImperatives-MOR->add_edge_by_id("restkomponentenSet", "component1", "RESTKOMPONENTE");
$ChichewaVerbWithImperatives-MOR->add_edge_by_id("component1", "open1", "FILLEDNESS");
$ChichewaVerbWithImperatives-MOR->add_edge_by_id("open1", "coherent1", "COHERENCE");
$ChichewaVerbWithImperatives-MOR->add_edge_by_id("component1", "elastic1", "ELASTICITY");
$ChichewaVerbWithImperatives-MOR->add_edge_by_id("elastic1", "MINIMUM0-1", "MINIMUM");
$ChichewaVerbWithImperatives-MOR->add_edge_by_id("elastic1", "MAXIMUM1-1", "MAXIMUM");
$ChichewaVerbWithImperatives-MOR->add_edge_by_id("component1", "stable1", "STABILITY");
$ChichewaVerbWithImperatives-MOR->add_edge_by_id("restkomponentenSet", "component2", "RESTKOMPONENTE");
$ChichewaVerbWithImperatives-MOR->add_edge_by_id("component2", "stable2", "STABILITY");
$ChichewaVerbWithImperatives-MOR->add_edge_by_id("component2", "elastic2", "ELASTICITY");
$ChichewaVerbWithImperatives-MOR->add_edge_by_id("elastic2", "MINIMUM0-2", "MINIMUM");
$ChichewaVerbWithImperatives-MOR->add_edge_by_id("elastic2", "MAXIMUM1-2", "MAXIMUM");
$ChichewaVerbWithImperatives-MOR->add_edge_by_id("component2", "open2", "FILLEDNESS");
$ChichewaVerbWithImperatives-MOR->add_edge_by_id("open2", "coherent2", "COHERENCE");
$ChichewaVerbWithImperatives-MOR->add_edge_by_id("restkomponentenSet", "component3", "RESTKOMPONENTE");
$ChichewaVerbWithImperatives-MOR->add_edge_by_id("component3", "elastic3", "ELASTICITY");
$ChichewaVerbWithImperatives-MOR->add_edge_by_id("elastic3", "MINIMUM0-3", "MINIMUM");
$ChichewaVerbWithImperatives-MOR->add_edge_by_id("elastic3", "MAXIMUM1-3", "MAXIMUM");
$ChichewaVerbWithImperatives-MOR->add_edge_by_id("component3", "open3", "FILLEDNESS");
$ChichewaVerbWithImperatives-MOR->add_edge_by_id("open3", "coherent3", "COHERENCE");
$ChichewaVerbWithImperatives-MOR->add_edge_by_id("component3", "stable3", "STABILITY");
$ChichewaVerbWithImperatives-MOR->add_edge_by_id("restkomponentenSet", "component4", "RESTKOMPONENTE");
$ChichewaVerbWithImperatives-MOR->add_edge_by_id("component4", "elastic4", "ELASTICITY");
$ChichewaVerbWithImperatives-MOR->add_edge_by_id("elastic4", "MAXIMUM1-4", "MAXIMUM");
$ChichewaVerbWithImperatives-MOR->add_edge_by_id("elastic4", "MINIMUM0-4", "MINIMUM");
$ChichewaVerbWithImperatives-MOR->add_edge_by_id("component4", "filled1", "FILLEDNESS");
$ChichewaVerbWithImperatives-MOR->add_edge_by_id("filled1", "canonicalLineate1", "FORM");
$ChichewaVerbWithImperatives-MOR->add_edge_by_id("component4", "stable4", "STABILITY");
$ChichewaVerbWithImperatives-MOR->add_edge_by_id("arch", "component5", "KEYSTONE");
$ChichewaVerbWithImperatives-MOR->add_edge_by_id("component5", "inelastic1", "ELASTICITY");
$ChichewaVerbWithImperatives-MOR->add_edge_by_id("inelastic1", "COUNT1-1", "COUNT");
$ChichewaVerbWithImperatives-MOR->add_edge_by_id("component5", "open4", "FILLEDNESS");
$ChichewaVerbWithImperatives-MOR->add_edge_by_id("open4", "coherent4", "COHERENCE");
$ChichewaVerbWithImperatives-MOR->add_edge_by_id("component5", "stable5", "STABILITY");
$ChichewaVerbWithImperatives-MOR->add_edge_by_id("arch", "component6", "LEFT_VOUSSOIR");
$ChichewaVerbWithImperatives-MOR->add_edge_by_id("component6", "elastic5", "ELASTICITY");
$ChichewaVerbWithImperatives-MOR->add_edge_by_id("elastic5", "MINIMUM0-5", "MINIMUM");
$ChichewaVerbWithImperatives-MOR->add_edge_by_id("elastic5", "MAXIMUM1-5", "MAXIMUM");
$ChichewaVerbWithImperatives-MOR->add_edge_by_id("component6", "open5", "FILLEDNESS");
$ChichewaVerbWithImperatives-MOR->add_edge_by_id("open5", "coherent5", "COHERENCE");
$ChichewaVerbWithImperatives-MOR->add_edge_by_id("component6", "stable6", "STABILITY");
$ChichewaVerbWithImperatives-MOR->add_edge_by_id("arch", "component7", "LEFT_SUPPORT");
$ChichewaVerbWithImperatives-MOR->add_edge_by_id("component7", "elastic6", "ELASTICITY");
$ChichewaVerbWithImperatives-MOR->add_edge_by_id("elastic6", "MAXIMUM1-6", "MAXIMUM");
$ChichewaVerbWithImperatives-MOR->add_edge_by_id("elastic6", "MINIMUM0-6", "MINIMUM");
$ChichewaVerbWithImperatives-MOR->add_edge_by_id("component7", "stable7", "STABILITY");
$ChichewaVerbWithImperatives-MOR->add_edge_by_id("component7", "open6", "FILLEDNESS");
$ChichewaVerbWithImperatives-MOR->add_edge_by_id("open6", "coherent6", "COHERENCE");
$ChichewaVerbWithImperatives-MOR->add_edge_by_id("arch", "component8", "RIGHT_SUPPORT");
$ChichewaVerbWithImperatives-MOR->add_edge_by_id("component8", "elastic7", "ELASTICITY");
$ChichewaVerbWithImperatives-MOR->add_edge_by_id("elastic7", "MINIMUM0-7", "MINIMUM");
$ChichewaVerbWithImperatives-MOR->add_edge_by_id("elastic7", "MAXIMUM1-7", "MAXIMUM");
$ChichewaVerbWithImperatives-MOR->add_edge_by_id("component8", "unstable1", "STABILITY");
$ChichewaVerbWithImperatives-MOR->add_edge_by_id("unstable1", "left", "ASSOCIATE_POSITION");
$ChichewaVerbWithImperatives-MOR->add_edge_by_id("unstable1", "component7", "ASSOCIATE");
$ChichewaVerbWithImperatives-MOR->add_edge_by_id("component8", "filled2", "FILLEDNESS");
$ChichewaVerbWithImperatives-MOR->add_edge_by_id("filled2", "embeddedDesmeme", "FORM");
$ChichewaVerbWithImperatives-MOR->add_edge_by_id("desmeme", "constructionalConditioning", "CONDITIONING");
$templateGraphs{ChichewaVerbWithImperatives-MOR} = $ChichewaVerbWithImperatives-MOR;

my $ChichewaSTAMP-PhMOR = Graph->new(multiedged => 1);
$ChichewaSTAMP-PhMOR->set_graph_attribute("name", "ChichewaSTAMP-PhMOR");
$ChichewaSTAMP-PhMOR->add_edge_by_id("desmeme", "order", "STRICTURE");
$ChichewaSTAMP-PhMOR->add_edge_by_id("order", "COUNT4-1", "COUNT");
$ChichewaSTAMP-PhMOR->add_edge_by_id("order", "morphologicalConstituent", "CONSTITUENT");
$ChichewaSTAMP-PhMOR->add_edge_by_id("order", "simple", "RELATIONS");
$ChichewaSTAMP-PhMOR->add_edge_by_id("desmeme", "span", "FOUNDATION");
$ChichewaSTAMP-PhMOR->add_edge_by_id("span", "component1", "RIGHT_SUPPORT");
$ChichewaSTAMP-PhMOR->add_edge_by_id("component1", "elastic1", "ELASTICITY");
$ChichewaSTAMP-PhMOR->add_edge_by_id("elastic1", "MAXIMUM1-1", "MAXIMUM");
$ChichewaSTAMP-PhMOR->add_edge_by_id("elastic1", "MINIMUM0-1", "MINIMUM");
$ChichewaSTAMP-PhMOR->add_edge_by_id("component1", "filled1", "FILLEDNESS");
$ChichewaSTAMP-PhMOR->add_edge_by_id("filled1", "canonicalLineate1", "FORM");
$ChichewaSTAMP-PhMOR->add_edge_by_id("component1", "stable1", "STABILITY");
$ChichewaSTAMP-PhMOR->add_edge_by_id("span", "restkomponentenSet", "RESTKOMPONENTEN");
$ChichewaSTAMP-PhMOR->add_edge_by_id("restkomponentenSet", "component2", "RESTKOMPONENTE");
$ChichewaSTAMP-PhMOR->add_edge_by_id("component2", "elastic2", "ELASTICITY");
$ChichewaSTAMP-PhMOR->add_edge_by_id("elastic2", "MINIMUM0-2", "MINIMUM");
$ChichewaSTAMP-PhMOR->add_edge_by_id("elastic2", "MAXIMUM1-2", "MAXIMUM");
$ChichewaSTAMP-PhMOR->add_edge_by_id("component2", "open1", "FILLEDNESS");
$ChichewaSTAMP-PhMOR->add_edge_by_id("open1", "coherent1", "COHERENCE");
$ChichewaSTAMP-PhMOR->add_edge_by_id("component2", "stable2", "STABILITY");
$ChichewaSTAMP-PhMOR->add_edge_by_id("restkomponentenSet", "component3", "RESTKOMPONENTE");
$ChichewaSTAMP-PhMOR->add_edge_by_id("component3", "stable3", "STABILITY");
$ChichewaSTAMP-PhMOR->add_edge_by_id("component3", "elastic3", "ELASTICITY");
$ChichewaSTAMP-PhMOR->add_edge_by_id("elastic3", "MINIMUM0-3", "MINIMUM");
$ChichewaSTAMP-PhMOR->add_edge_by_id("elastic3", "MAXIMUM1-3", "MAXIMUM");
$ChichewaSTAMP-PhMOR->add_edge_by_id("component3", "open2", "FILLEDNESS");
$ChichewaSTAMP-PhMOR->add_edge_by_id("open2", "coherent2", "COHERENCE");
$ChichewaSTAMP-PhMOR->add_edge_by_id("span", "component4", "LEFT_SUPPORT");
$ChichewaSTAMP-PhMOR->add_edge_by_id("component4", "open3", "FILLEDNESS");
$ChichewaSTAMP-PhMOR->add_edge_by_id("open3", "coherent3", "COHERENCE");
$ChichewaSTAMP-PhMOR->add_edge_by_id("component4", "inelastic1", "ELASTICITY");
$ChichewaSTAMP-PhMOR->add_edge_by_id("inelastic1", "COUNT1-1", "COUNT");
$ChichewaSTAMP-PhMOR->add_edge_by_id("component4", "stable4", "STABILITY");
$ChichewaSTAMP-PhMOR->add_edge_by_id("desmeme", "constructionalConditioning", "CONDITIONING");
$ChichewaSTAMP-PhMOR->add_edge_by_id("desmeme", "notViolable", "VIOLABILITY");
$templateGraphs{ChichewaSTAMP-PhMOR} = $ChichewaSTAMP-PhMOR;

my $ChichewaVOX-SYN = Graph->new(multiedged => 1);
$ChichewaVOX-SYN->set_graph_attribute("name", "ChichewaVOX-SYN");
$ChichewaVOX-SYN->add_edge_by_id("desmeme", "constructionalConditioning", "CONDITIONING");
$ChichewaVOX-SYN->add_edge_by_id("desmeme", "potentiallyViolable", "VIOLABILITY");
$ChichewaVOX-SYN->add_edge_by_id("potentiallyViolable", "morphosyntactic", "EXCEPTIONALITY");
$ChichewaVOX-SYN->add_edge_by_id("potentiallyViolable", "surfaceViolable", "REPARABILITY");
$ChichewaVOX-SYN->add_edge_by_id("desmeme", "arch", "FOUNDATION");
$ChichewaVOX-SYN->add_edge_by_id("arch", "component1", "KEYSTONE");
$ChichewaVOX-SYN->add_edge_by_id("component1", "open1", "FILLEDNESS");
$ChichewaVOX-SYN->add_edge_by_id("open1", "coherent1", "COHERENCE");
$ChichewaVOX-SYN->add_edge_by_id("component1", "inelastic1", "ELASTICITY");
$ChichewaVOX-SYN->add_edge_by_id("inelastic1", "COUNT1-1", "COUNT");
$ChichewaVOX-SYN->add_edge_by_id("component1", "stable1", "STABILITY");
$ChichewaVOX-SYN->add_edge_by_id("arch", "component2", "RIGHT_SUPPORT");
$ChichewaVOX-SYN->add_edge_by_id("component2", "elastic1", "ELASTICITY");
$ChichewaVOX-SYN->add_edge_by_id("elastic1", "MINIMUM0-1", "MINIMUM");
$ChichewaVOX-SYN->add_edge_by_id("elastic1", "MAXIMUM100-1", "MAXIMUM");
$ChichewaVOX-SYN->add_edge_by_id("component2", "open2", "FILLEDNESS");
$ChichewaVOX-SYN->add_edge_by_id("open2", "coherent2", "COHERENCE");
$ChichewaVOX-SYN->add_edge_by_id("component2", "stable2", "STABILITY");
$ChichewaVOX-SYN->add_edge_by_id("arch", "component3", "RIGHT_VOUSSOIR");
$ChichewaVOX-SYN->add_edge_by_id("component3", "elastic2", "ELASTICITY");
$ChichewaVOX-SYN->add_edge_by_id("elastic2", "MINIMUM0-2", "MINIMUM");
$ChichewaVOX-SYN->add_edge_by_id("elastic2", "MAXIMUM1-1", "MAXIMUM");
$ChichewaVOX-SYN->add_edge_by_id("component3", "open3", "FILLEDNESS");
$ChichewaVOX-SYN->add_edge_by_id("open3", "coherent3", "COHERENCE");
$ChichewaVOX-SYN->add_edge_by_id("component3", "stable3", "STABILITY");
$ChichewaVOX-SYN->add_edge_by_id("arch", "component4", "LEFT_VOUSSOIR");
$ChichewaVOX-SYN->add_edge_by_id("component4", "stable4", "STABILITY");
$ChichewaVOX-SYN->add_edge_by_id("component4", "null1", "FILLEDNESS");
$ChichewaVOX-SYN->add_edge_by_id("component4", "inelastic2", "ELASTICITY");
$ChichewaVOX-SYN->add_edge_by_id("inelastic2", "COUNT0-1", "COUNT");
$ChichewaVOX-SYN->add_edge_by_id("arch", "component1", "LEFT_SUPPORT");
$ChichewaVOX-SYN->add_edge_by_id("desmeme", "order", "STRICTURE");
$ChichewaVOX-SYN->add_edge_by_id("order", "COUNT3-1", "COUNT");
$ChichewaVOX-SYN->add_edge_by_id("order", "simple", "RELATIONS");
$ChichewaVOX-SYN->add_edge_by_id("order", "syntacticConstituent", "CONSTITUENT");
$templateGraphs{ChichewaVOX-SYN} = $ChichewaVOX-SYN;

my $ChichewaLocative-CLT = Graph->new(multiedged => 1);
$ChichewaLocative-CLT->set_graph_attribute("name", "ChichewaLocative-CLT");
$ChichewaLocative-CLT->add_edge_by_id("desmeme", "constructionalConditioning", "CONDITIONING");
$ChichewaLocative-CLT->add_edge_by_id("desmeme", "notViolable", "VIOLABILITY");
$ChichewaLocative-CLT->add_edge_by_id("desmeme", "order", "STRICTURE");
$ChichewaLocative-CLT->add_edge_by_id("order", "COUNT2-1", "COUNT");
$ChichewaLocative-CLT->add_edge_by_id("order", "simple", "RELATIONS");
$ChichewaLocative-CLT->add_edge_by_id("order", "morphologicalConstituent", "CONSTITUENT");
$ChichewaLocative-CLT->add_edge_by_id("desmeme", "span", "FOUNDATION");
$ChichewaLocative-CLT->add_edge_by_id("span", "restkomponentenSet", "RESTKOMPONENTEN");
$ChichewaLocative-CLT->add_edge_by_id("restkomponentenSet", "component1", "RESTKOMPONENTE");
$ChichewaLocative-CLT->add_edge_by_id("component1", "inelastic1", "ELASTICITY");
$ChichewaLocative-CLT->add_edge_by_id("inelastic1", "COUNT1-1", "COUNT");
$ChichewaLocative-CLT->add_edge_by_id("component1", "partiallyFilled1", "FILLEDNESS");
$ChichewaLocative-CLT->add_edge_by_id("partiallyFilled1", "coherent1", "COHERENCE");
$ChichewaLocative-CLT->add_edge_by_id("partiallyFilled1", "componentFinal", "FILLER_PLACEMENT");
$ChichewaLocative-CLT->add_edge_by_id("partiallyFilled1", "embeddedDesmeme", "FORM");
$ChichewaLocative-CLT->add_edge_by_id("component1", "unstable1", "STABILITY");
$ChichewaLocative-CLT->add_edge_by_id("unstable1", "component2", "ASSOCIATE");
$ChichewaLocative-CLT->add_edge_by_id("component2", "inelastic2", "ELASTICITY");
$ChichewaLocative-CLT->add_edge_by_id("inelastic2", "COUNT1-2", "COUNT");
$ChichewaLocative-CLT->add_edge_by_id("component2", "open1", "FILLEDNESS");
$ChichewaLocative-CLT->add_edge_by_id("open1", "coherent2", "COHERENCE");
$ChichewaLocative-CLT->add_edge_by_id("component2", "stable1", "STABILITY");
$ChichewaLocative-CLT->add_edge_by_id("unstable1", "right", "ASSOCIATE_POSITION");
$ChichewaLocative-CLT->add_edge_by_id("span", "component3", "RIGHT_SUPPORT");
$ChichewaLocative-CLT->add_edge_by_id("component3", "stable2", "STABILITY");
$ChichewaLocative-CLT->add_edge_by_id("component3", "inelastic3", "ELASTICITY");
$ChichewaLocative-CLT->add_edge_by_id("inelastic3", "COUNT1-3", "COUNT");
$ChichewaLocative-CLT->add_edge_by_id("component3", "filled1", "FILLEDNESS");
$ChichewaLocative-CLT->add_edge_by_id("filled1", "embeddedDesmeme", "FORM");
$ChichewaLocative-CLT->add_edge_by_id("span", "component4", "LEFT_SUPPORT");
$ChichewaLocative-CLT->add_edge_by_id("component4", "inelastic4", "ELASTICITY");
$ChichewaLocative-CLT->add_edge_by_id("inelastic4", "COUNT1-4", "COUNT");
$ChichewaLocative-CLT->add_edge_by_id("component4", "unstable2", "STABILITY");
$ChichewaLocative-CLT->add_edge_by_id("unstable2", "left", "ASSOCIATE_POSITION");
$ChichewaLocative-CLT->add_edge_by_id("unstable2", "component3", "ASSOCIATE");
$ChichewaLocative-CLT->add_edge_by_id("component4", "open2", "FILLEDNESS");
$ChichewaLocative-CLT->add_edge_by_id("open2", "coherent3", "COHERENCE");
$templateGraphs{ChichewaLocative-CLT} = $ChichewaLocative-CLT;

my $ChichewaKodi-SYN = Graph->new(multiedged => 1);
$ChichewaKodi-SYN->set_graph_attribute("name", "ChichewaKodi-SYN");
$ChichewaKodi-SYN->add_edge_by_id("desmeme", "span", "FOUNDATION");
$ChichewaKodi-SYN->add_edge_by_id("span", "component1", "RIGHT_SUPPORT");
$ChichewaKodi-SYN->add_edge_by_id("component1", "inelastic1", "ELASTICITY");
$ChichewaKodi-SYN->add_edge_by_id("inelastic1", "COUNT1-1", "COUNT");
$ChichewaKodi-SYN->add_edge_by_id("component1", "stable1", "STABILITY");
$ChichewaKodi-SYN->add_edge_by_id("component1", "filled1", "FILLEDNESS");
$ChichewaKodi-SYN->add_edge_by_id("filled1", "embeddedDesmeme", "FORM");
$ChichewaKodi-SYN->add_edge_by_id("span", "component2", "LEFT_SUPPORT");
$ChichewaKodi-SYN->add_edge_by_id("component2", "inelastic2", "ELASTICITY");
$ChichewaKodi-SYN->add_edge_by_id("inelastic2", "COUNT1-2", "COUNT");
$ChichewaKodi-SYN->add_edge_by_id("component2", "filled2", "FILLEDNESS");
$ChichewaKodi-SYN->add_edge_by_id("filled2", "canonicalLineate1", "FORM");
$ChichewaKodi-SYN->add_edge_by_id("component2", "stable2", "STABILITY");
$ChichewaKodi-SYN->add_edge_by_id("desmeme", "order", "STRICTURE");
$ChichewaKodi-SYN->add_edge_by_id("order", "COUNT2-1", "COUNT");
$ChichewaKodi-SYN->add_edge_by_id("order", "simple", "RELATIONS");
$ChichewaKodi-SYN->add_edge_by_id("order", "syntacticConstituent", "CONSTITUENT");
$ChichewaKodi-SYN->add_edge_by_id("desmeme", "lexicoconstructionalConditioning", "CONDITIONING");
$ChichewaKodi-SYN->add_edge_by_id("lexicoconstructionalConditioning", "filledComponentSet", "FILLED_COMPONENTS");
$ChichewaKodi-SYN->add_edge_by_id("filledComponentSet", "component2", "FILLED_COMPONENT");
$ChichewaKodi-SYN->add_edge_by_id("lexicoconstructionalConditioning", "templateInitial", "FILLER_POSITION");
$ChichewaKodi-SYN->add_edge_by_id("desmeme", "potentiallyViolable", "VIOLABILITY");
$ChichewaKodi-SYN->add_edge_by_id("potentiallyViolable", "pragmatic", "EXCEPTIONALITY");
$ChichewaKodi-SYN->add_edge_by_id("potentiallyViolable", "surfaceViolable", "REPARABILITY");
$templateGraphs{ChichewaKodi-SYN} = $ChichewaKodi-SYN;

my $ChichewaVowelHarmony-PhMOR = Graph->new(multiedged => 1);
$ChichewaVowelHarmony-PhMOR->set_graph_attribute("name", "ChichewaVowelHarmony-PhMOR");
$ChichewaVowelHarmony-PhMOR->add_edge_by_id("desmeme", "span", "FOUNDATION");
$ChichewaVowelHarmony-PhMOR->add_edge_by_id("span", "component1", "LEFT_SUPPORT");
$ChichewaVowelHarmony-PhMOR->add_edge_by_id("component1", "stable1", "STABILITY");
$ChichewaVowelHarmony-PhMOR->add_edge_by_id("component1", "open1", "FILLEDNESS");
$ChichewaVowelHarmony-PhMOR->add_edge_by_id("open1", "coherent1", "COHERENCE");
$ChichewaVowelHarmony-PhMOR->add_edge_by_id("component1", "inelastic1", "ELASTICITY");
$ChichewaVowelHarmony-PhMOR->add_edge_by_id("inelastic1", "COUNT1-1", "COUNT");
$ChichewaVowelHarmony-PhMOR->add_edge_by_id("span", "component2", "RIGHT_SUPPORT");
$ChichewaVowelHarmony-PhMOR->add_edge_by_id("component2", "open2", "FILLEDNESS");
$ChichewaVowelHarmony-PhMOR->add_edge_by_id("open2", "coherent2", "COHERENCE");
$ChichewaVowelHarmony-PhMOR->add_edge_by_id("component2", "elastic1", "ELASTICITY");
$ChichewaVowelHarmony-PhMOR->add_edge_by_id("elastic1", "MINIMUM0-1", "MINIMUM");
$ChichewaVowelHarmony-PhMOR->add_edge_by_id("elastic1", "MAXIMUM100-1", "MAXIMUM");
$ChichewaVowelHarmony-PhMOR->add_edge_by_id("component2", "unstable1", "STABILITY");
$ChichewaVowelHarmony-PhMOR->add_edge_by_id("unstable1", "left", "ASSOCIATE_POSITION");
$ChichewaVowelHarmony-PhMOR->add_edge_by_id("unstable1", "component1", "ASSOCIATE");
$ChichewaVowelHarmony-PhMOR->add_edge_by_id("desmeme", "potentiallyViolable", "VIOLABILITY");
$ChichewaVowelHarmony-PhMOR->add_edge_by_id("potentiallyViolable", "lexical", "EXCEPTIONALITY");
$ChichewaVowelHarmony-PhMOR->add_edge_by_id("potentiallyViolable", "surfaceViolable", "REPARABILITY");
$ChichewaVowelHarmony-PhMOR->add_edge_by_id("desmeme", "order", "STRICTURE");
$ChichewaVowelHarmony-PhMOR->add_edge_by_id("order", "COUNT2-1", "COUNT");
$ChichewaVowelHarmony-PhMOR->add_edge_by_id("order", "Syllable", "CONSTITUENT");
$ChichewaVowelHarmony-PhMOR->add_edge_by_id("order", "simple", "RELATIONS");
$ChichewaVowelHarmony-PhMOR->add_edge_by_id("desmeme", "constructionalConditioning", "CONDITIONING");
$templateGraphs{ChichewaVowelHarmony-PhMOR} = $ChichewaVowelHarmony-PhMOR;

my $ChichewaAR-MOR = Graph->new(multiedged => 1);
$ChichewaAR-MOR->set_graph_attribute("name", "ChichewaAR-MOR");
$ChichewaAR-MOR->add_edge_by_id("desmeme", "arch", "FOUNDATION");
$ChichewaAR-MOR->add_edge_by_id("arch", "component1", "RIGHT_VOUSSOIR");
$ChichewaAR-MOR->add_edge_by_id("component1", "stable1", "STABILITY");
$ChichewaAR-MOR->add_edge_by_id("component1", "filled1", "FILLEDNESS");
$ChichewaAR-MOR->add_edge_by_id("filled1", "canonicalLineate1", "FORM");
$ChichewaAR-MOR->add_edge_by_id("component1", "elastic1", "ELASTICITY");
$ChichewaAR-MOR->add_edge_by_id("elastic1", "MAXIMUM1-1", "MAXIMUM");
$ChichewaAR-MOR->add_edge_by_id("elastic1", "MINIMUM0-1", "MINIMUM");
$ChichewaAR-MOR->add_edge_by_id("arch", "component2", "LEFT_SUPPORT");
$ChichewaAR-MOR->add_edge_by_id("component2", "inelastic1", "ELASTICITY");
$ChichewaAR-MOR->add_edge_by_id("inelastic1", "COUNT1-1", "COUNT");
$ChichewaAR-MOR->add_edge_by_id("component2", "open1", "FILLEDNESS");
$ChichewaAR-MOR->add_edge_by_id("open1", "coherent1", "COHERENCE");
$ChichewaAR-MOR->add_edge_by_id("component2", "stable2", "STABILITY");
$ChichewaAR-MOR->add_edge_by_id("arch", "component3", "RIGHT_SUPPORT");
$ChichewaAR-MOR->add_edge_by_id("component3", "stable3", "STABILITY");
$ChichewaAR-MOR->add_edge_by_id("component3", "elastic2", "ELASTICITY");
$ChichewaAR-MOR->add_edge_by_id("elastic2", "MAXIMUM1-2", "MAXIMUM");
$ChichewaAR-MOR->add_edge_by_id("elastic2", "MINIMUM0-2", "MINIMUM");
$ChichewaAR-MOR->add_edge_by_id("component3", "filled2", "FILLEDNESS");
$ChichewaAR-MOR->add_edge_by_id("filled2", "canonicalLineate2", "FORM");
$ChichewaAR-MOR->add_edge_by_id("arch", "component2", "KEYSTONE");
$ChichewaAR-MOR->add_edge_by_id("arch", "component4", "LEFT_VOUSSOIR");
$ChichewaAR-MOR->add_edge_by_id("component4", "null1", "FILLEDNESS");
$ChichewaAR-MOR->add_edge_by_id("component4", "inelastic2", "ELASTICITY");
$ChichewaAR-MOR->add_edge_by_id("inelastic2", "COUNT0-1", "COUNT");
$ChichewaAR-MOR->add_edge_by_id("component4", "stable4", "STABILITY");
$ChichewaAR-MOR->add_edge_by_id("desmeme", "order", "STRICTURE");
$ChichewaAR-MOR->add_edge_by_id("order", "morphologicalConstituent", "CONSTITUENT");
$ChichewaAR-MOR->add_edge_by_id("order", "simple", "RELATIONS");
$ChichewaAR-MOR->add_edge_by_id("order", "COUNT3-1", "COUNT");
$ChichewaAR-MOR->add_edge_by_id("desmeme", "potentiallyViolable", "VIOLABILITY");
$ChichewaAR-MOR->add_edge_by_id("potentiallyViolable", "semantic", "EXCEPTIONALITY");
$ChichewaAR-MOR->add_edge_by_id("potentiallyViolable", "morphosyntacticInsertion", "REPARABILITY");
$ChichewaAR-MOR->add_edge_by_id("desmeme", "lexicoconstructionalConditioning", "CONDITIONING");
$ChichewaAR-MOR->add_edge_by_id("lexicoconstructionalConditioning", "templateMultiple", "FILLER_POSITION");
$ChichewaAR-MOR->add_edge_by_id("lexicoconstructionalConditioning", "filledComponentSet", "FILLED_COMPONENTS");
$ChichewaAR-MOR->add_edge_by_id("filledComponentSet", "component3", "FILLED_COMPONENT");
$ChichewaAR-MOR->add_edge_by_id("filledComponentSet", "component1", "FILLED_COMPONENT");
$templateGraphs{ChichewaAR-MOR} = $ChichewaAR-MOR;

my $ChichewaCP-MOR = Graph->new(multiedged => 1);
$ChichewaCP-MOR->set_graph_attribute("name", "ChichewaCP-MOR");
$ChichewaCP-MOR->add_edge_by_id("desmeme", "notViolable", "VIOLABILITY");
$ChichewaCP-MOR->add_edge_by_id("desmeme", "arch", "FOUNDATION");
$ChichewaCP-MOR->add_edge_by_id("arch", "component1", "LEFT_SUPPORT");
$ChichewaCP-MOR->add_edge_by_id("component1", "inelastic1", "ELASTICITY");
$ChichewaCP-MOR->add_edge_by_id("inelastic1", "COUNT1-1", "COUNT");
$ChichewaCP-MOR->add_edge_by_id("component1", "open1", "FILLEDNESS");
$ChichewaCP-MOR->add_edge_by_id("open1", "coherent1", "COHERENCE");
$ChichewaCP-MOR->add_edge_by_id("component1", "stable1", "STABILITY");
$ChichewaCP-MOR->add_edge_by_id("arch", "component2", "RIGHT_SUPPORT");
$ChichewaCP-MOR->add_edge_by_id("component2", "elastic1", "ELASTICITY");
$ChichewaCP-MOR->add_edge_by_id("elastic1", "MINIMUM0-1", "MINIMUM");
$ChichewaCP-MOR->add_edge_by_id("elastic1", "MAXIMUM1-1", "MAXIMUM");
$ChichewaCP-MOR->add_edge_by_id("component2", "filled1", "FILLEDNESS");
$ChichewaCP-MOR->add_edge_by_id("filled1", "canonicalLineate1", "FORM");
$ChichewaCP-MOR->add_edge_by_id("component2", "stable2", "STABILITY");
$ChichewaCP-MOR->add_edge_by_id("arch", "component3", "LEFT_VOUSSOIR");
$ChichewaCP-MOR->add_edge_by_id("component3", "null1", "FILLEDNESS");
$ChichewaCP-MOR->add_edge_by_id("component3", "stable3", "STABILITY");
$ChichewaCP-MOR->add_edge_by_id("component3", "inelastic2", "ELASTICITY");
$ChichewaCP-MOR->add_edge_by_id("inelastic2", "COUNT0-1", "COUNT");
$ChichewaCP-MOR->add_edge_by_id("arch", "component4", "RIGHT_VOUSSOIR");
$ChichewaCP-MOR->add_edge_by_id("component4", "elastic2", "ELASTICITY");
$ChichewaCP-MOR->add_edge_by_id("elastic2", "MINIMUM0-2", "MINIMUM");
$ChichewaCP-MOR->add_edge_by_id("elastic2", "MAXIMUM1-2", "MAXIMUM");
$ChichewaCP-MOR->add_edge_by_id("component4", "stable4", "STABILITY");
$ChichewaCP-MOR->add_edge_by_id("component4", "filled2", "FILLEDNESS");
$ChichewaCP-MOR->add_edge_by_id("filled2", "canonicalLineate2", "FORM");
$ChichewaCP-MOR->add_edge_by_id("arch", "component1", "KEYSTONE");
$ChichewaCP-MOR->add_edge_by_id("desmeme", "lexicoconstructionalConditioning", "CONDITIONING");
$ChichewaCP-MOR->add_edge_by_id("lexicoconstructionalConditioning", "filledComponentSet", "FILLED_COMPONENTS");
$ChichewaCP-MOR->add_edge_by_id("filledComponentSet", "component4", "FILLED_COMPONENT");
$ChichewaCP-MOR->add_edge_by_id("filledComponentSet", "component2", "FILLED_COMPONENT");
$ChichewaCP-MOR->add_edge_by_id("lexicoconstructionalConditioning", "templateMultiple", "FILLER_POSITION");
$ChichewaCP-MOR->add_edge_by_id("desmeme", "order", "STRICTURE");
$ChichewaCP-MOR->add_edge_by_id("order", "morphologicalConstituent", "CONSTITUENT");
$ChichewaCP-MOR->add_edge_by_id("order", "COUNT3-1", "COUNT");
$ChichewaCP-MOR->add_edge_by_id("order", "simple", "RELATIONS");
$templateGraphs{ChichewaCP-MOR} = $ChichewaCP-MOR;

my $ChichewaComplementClause-SYN = Graph->new(multiedged => 1);
$ChichewaComplementClause-SYN->set_graph_attribute("name", "ChichewaComplementClause-SYN");
$ChichewaComplementClause-SYN->add_edge_by_id("desmeme", "lexicoconstructionalConditioning", "CONDITIONING");
$ChichewaComplementClause-SYN->add_edge_by_id("desmeme", "order", "STRICTURE");
$ChichewaComplementClause-SYN->add_edge_by_id("order", "simple", "RELATIONS");
$ChichewaComplementClause-SYN->add_edge_by_id("order", "COUNT2-1", "COUNT");
$ChichewaComplementClause-SYN->add_edge_by_id("order", "syntacticConstituent", "CONSTITUENT");
$ChichewaComplementClause-SYN->add_edge_by_id("desmeme", "span", "FOUNDATION");
$ChichewaComplementClause-SYN->add_edge_by_id("span", "component1", "LEFT_SUPPORT");
$ChichewaComplementClause-SYN->add_edge_by_id("component1", "filled1", "FILLEDNESS");
$ChichewaComplementClause-SYN->add_edge_by_id("filled1", "canonicalLineate1", "FORM");
$ChichewaComplementClause-SYN->add_edge_by_id("component1", "inelastic1", "ELASTICITY");
$ChichewaComplementClause-SYN->add_edge_by_id("inelastic1", "COUNT1-1", "COUNT");
$ChichewaComplementClause-SYN->add_edge_by_id("component1", "unstable1", "STABILITY");
$ChichewaComplementClause-SYN->add_edge_by_id("unstable1", "component2", "ASSOCIATE");
$ChichewaComplementClause-SYN->add_edge_by_id("component2", "stable1", "STABILITY");
$ChichewaComplementClause-SYN->add_edge_by_id("component2", "inelastic2", "ELASTICITY");
$ChichewaComplementClause-SYN->add_edge_by_id("inelastic2", "COUNT1-2", "COUNT");
$ChichewaComplementClause-SYN->add_edge_by_id("component2", "open1", "FILLEDNESS");
$ChichewaComplementClause-SYN->add_edge_by_id("open1", "coherent1", "COHERENCE");
$ChichewaComplementClause-SYN->add_edge_by_id("unstable1", "right", "ASSOCIATE_POSITION");
$ChichewaComplementClause-SYN->add_edge_by_id("span", "component2", "RIGHT_SUPPORT");
$ChichewaComplementClause-SYN->add_edge_by_id("desmeme", "notViolable", "VIOLABILITY");
$templateGraphs{ChichewaComplementClause-SYN} = $ChichewaComplementClause-SYN;

my $ChichewaVerbStem-PhMOR = Graph->new(multiedged => 1);
$ChichewaVerbStem-PhMOR->set_graph_attribute("name", "ChichewaVerbStem-PhMOR");
$ChichewaVerbStem-PhMOR->add_edge_by_id("desmeme", "constructionalConditioning", "CONDITIONING");
$ChichewaVerbStem-PhMOR->add_edge_by_id("desmeme", "span", "FOUNDATION");
$ChichewaVerbStem-PhMOR->add_edge_by_id("span", "component1", "LEFT_SUPPORT");
$ChichewaVerbStem-PhMOR->add_edge_by_id("component1", "filled1", "FILLEDNESS");
$ChichewaVerbStem-PhMOR->add_edge_by_id("filled1", "embeddedDesmeme", "FORM");
$ChichewaVerbStem-PhMOR->add_edge_by_id("component1", "unstable1", "STABILITY");
$ChichewaVerbStem-PhMOR->add_edge_by_id("unstable1", "right", "ASSOCIATE_POSITION");
$ChichewaVerbStem-PhMOR->add_edge_by_id("unstable1", "component2", "ASSOCIATE");
$ChichewaVerbStem-PhMOR->add_edge_by_id("component2", "open1", "FILLEDNESS");
$ChichewaVerbStem-PhMOR->add_edge_by_id("open1", "coherent1", "COHERENCE");
$ChichewaVerbStem-PhMOR->add_edge_by_id("component2", "inelastic1", "ELASTICITY");
$ChichewaVerbStem-PhMOR->add_edge_by_id("inelastic1", "COUNT1-1", "COUNT");
$ChichewaVerbStem-PhMOR->add_edge_by_id("component2", "unstable2", "STABILITY");
$ChichewaVerbStem-PhMOR->add_edge_by_id("unstable2", "left", "ASSOCIATE_POSITION");
$ChichewaVerbStem-PhMOR->add_edge_by_id("unstable2", "component1", "ASSOCIATE");
$ChichewaVerbStem-PhMOR->add_edge_by_id("component1", "inelastic2", "ELASTICITY");
$ChichewaVerbStem-PhMOR->add_edge_by_id("inelastic2", "COUNT1-2", "COUNT");
$ChichewaVerbStem-PhMOR->add_edge_by_id("span", "component2", "RIGHT_SUPPORT");
$ChichewaVerbStem-PhMOR->add_edge_by_id("desmeme", "notViolable", "VIOLABILITY");
$ChichewaVerbStem-PhMOR->add_edge_by_id("desmeme", "order", "STRICTURE");
$ChichewaVerbStem-PhMOR->add_edge_by_id("order", "COUNT2-1", "COUNT");
$ChichewaVerbStem-PhMOR->add_edge_by_id("order", "morphologicalConstituent", "CONSTITUENT");
$ChichewaVerbStem-PhMOR->add_edge_by_id("order", "simple", "RELATIONS");
$templateGraphs{ChichewaVerbStem-PhMOR} = $ChichewaVerbStem-PhMOR;

my $ChichewaOsaVerb-MOR = Graph->new(multiedged => 1);
$ChichewaOsaVerb-MOR->set_graph_attribute("name", "ChichewaOsaVerb-MOR");
$ChichewaOsaVerb-MOR->add_edge_by_id("desmeme", "order", "STRICTURE");
$ChichewaOsaVerb-MOR->add_edge_by_id("order", "simple", "RELATIONS");
$ChichewaOsaVerb-MOR->add_edge_by_id("order", "morphologicalConstituent", "CONSTITUENT");
$ChichewaOsaVerb-MOR->add_edge_by_id("order", "COUNT2-1", "COUNT");
$ChichewaOsaVerb-MOR->add_edge_by_id("desmeme", "notViolable", "VIOLABILITY");
$ChichewaOsaVerb-MOR->add_edge_by_id("desmeme", "arch", "FOUNDATION");
$ChichewaOsaVerb-MOR->add_edge_by_id("arch", "component1", "KEYSTONE");
$ChichewaOsaVerb-MOR->add_edge_by_id("component1", "inelastic1", "ELASTICITY");
$ChichewaOsaVerb-MOR->add_edge_by_id("inelastic1", "COUNT1-1", "COUNT");
$ChichewaOsaVerb-MOR->add_edge_by_id("component1", "open1", "FILLEDNESS");
$ChichewaOsaVerb-MOR->add_edge_by_id("open1", "coherent1", "COHERENCE");
$ChichewaOsaVerb-MOR->add_edge_by_id("component1", "stable1", "STABILITY");
$ChichewaOsaVerb-MOR->add_edge_by_id("arch", "component2", "LEFT_VOUSSOIR");
$ChichewaOsaVerb-MOR->add_edge_by_id("component2", "elastic1", "ELASTICITY");
$ChichewaOsaVerb-MOR->add_edge_by_id("elastic1", "MINIMUM0-1", "MINIMUM");
$ChichewaOsaVerb-MOR->add_edge_by_id("elastic1", "MAXIMUM1-1", "MAXIMUM");
$ChichewaOsaVerb-MOR->add_edge_by_id("component2", "open2", "FILLEDNESS");
$ChichewaOsaVerb-MOR->add_edge_by_id("open2", "coherent2", "COHERENCE");
$ChichewaOsaVerb-MOR->add_edge_by_id("component2", "stable2", "STABILITY");
$ChichewaOsaVerb-MOR->add_edge_by_id("arch", "component3", "RIGHT_VOUSSOIR");
$ChichewaOsaVerb-MOR->add_edge_by_id("component3", "null1", "FILLEDNESS");
$ChichewaOsaVerb-MOR->add_edge_by_id("component3", "stable3", "STABILITY");
$ChichewaOsaVerb-MOR->add_edge_by_id("component3", "inelastic2", "ELASTICITY");
$ChichewaOsaVerb-MOR->add_edge_by_id("inelastic2", "COUNT0-1", "COUNT");
$ChichewaOsaVerb-MOR->add_edge_by_id("arch", "component1", "RIGHT_SUPPORT");
$ChichewaOsaVerb-MOR->add_edge_by_id("arch", "component4", "LEFT_SUPPORT");
$ChichewaOsaVerb-MOR->add_edge_by_id("component4", "stable4", "STABILITY");
$ChichewaOsaVerb-MOR->add_edge_by_id("component4", "filled1", "FILLEDNESS");
$ChichewaOsaVerb-MOR->add_edge_by_id("filled1", "canonicalLineate1", "FORM");
$ChichewaOsaVerb-MOR->add_edge_by_id("component4", "inelastic3", "ELASTICITY");
$ChichewaOsaVerb-MOR->add_edge_by_id("inelastic3", "COUNT1-2", "COUNT");
$ChichewaOsaVerb-MOR->add_edge_by_id("desmeme", "lexicoconstructionalConditioning", "CONDITIONING");
$ChichewaOsaVerb-MOR->add_edge_by_id("lexicoconstructionalConditioning", "templateInitial", "FILLER_POSITION");
$ChichewaOsaVerb-MOR->add_edge_by_id("lexicoconstructionalConditioning", "filledComponentSet", "FILLED_COMPONENTS");
$ChichewaOsaVerb-MOR->add_edge_by_id("filledComponentSet", "component4", "FILLED_COMPONENT");
$templateGraphs{ChichewaOsaVerb-MOR} = $ChichewaOsaVerb-MOR;

my $ChichewaDerivationalStem-PhMOR = Graph->new(multiedged => 1);
$ChichewaDerivationalStem-PhMOR->set_graph_attribute("name", "ChichewaDerivationalStem-PhMOR");
$ChichewaDerivationalStem-PhMOR->add_edge_by_id("desmeme", "span", "FOUNDATION");
$ChichewaDerivationalStem-PhMOR->add_edge_by_id("span", "component1", "LEFT_SUPPORT");
$ChichewaDerivationalStem-PhMOR->add_edge_by_id("component1", "open1", "FILLEDNESS");
$ChichewaDerivationalStem-PhMOR->add_edge_by_id("open1", "coherent1", "COHERENCE");
$ChichewaDerivationalStem-PhMOR->add_edge_by_id("component1", "inelastic1", "ELASTICITY");
$ChichewaDerivationalStem-PhMOR->add_edge_by_id("component1", "stable1", "STABILITY");
$ChichewaDerivationalStem-PhMOR->add_edge_by_id("span", "component2", "RIGHT_SUPPORT");
$ChichewaDerivationalStem-PhMOR->add_edge_by_id("component2", "open2", "FILLEDNESS");
$ChichewaDerivationalStem-PhMOR->add_edge_by_id("open2", "coherent2", "COHERENCE");
$ChichewaDerivationalStem-PhMOR->add_edge_by_id("component2", "elastic1", "ELASTICITY");
$ChichewaDerivationalStem-PhMOR->add_edge_by_id("elastic1", "MAXIMUM100-1", "MAXIMUM");
$ChichewaDerivationalStem-PhMOR->add_edge_by_id("elastic1", "MINIMUM0-1", "MINIMUM");
$ChichewaDerivationalStem-PhMOR->add_edge_by_id("component2", "unstable1", "STABILITY");
$ChichewaDerivationalStem-PhMOR->add_edge_by_id("unstable1", "left", "ASSOCIATE_POSITION");
$ChichewaDerivationalStem-PhMOR->add_edge_by_id("unstable1", "component1", "ASSOCIATE");
$ChichewaDerivationalStem-PhMOR->add_edge_by_id("desmeme", "order", "STRICTURE");
$ChichewaDerivationalStem-PhMOR->add_edge_by_id("order", "COUNT2-1", "COUNT");
$ChichewaDerivationalStem-PhMOR->add_edge_by_id("order", "morphologicalConstituent", "CONSTITUENT");
$ChichewaDerivationalStem-PhMOR->add_edge_by_id("order", "simple", "RELATIONS");
$ChichewaDerivationalStem-PhMOR->add_edge_by_id("desmeme", "notViolable", "VIOLABILITY");
$ChichewaDerivationalStem-PhMOR->add_edge_by_id("desmeme", "constructionalConditioning", "CONDITIONING");
$templateGraphs{ChichewaDerivationalStem-PhMOR} = $ChichewaDerivationalStem-PhMOR;

my $ChichewaCA-MOR = Graph->new(multiedged => 1);
$ChichewaCA-MOR->set_graph_attribute("name", "ChichewaCA-MOR");
$ChichewaCA-MOR->add_edge_by_id("desmeme", "lexicoconstructionalConditioning", "CONDITIONING");
$ChichewaCA-MOR->add_edge_by_id("lexicoconstructionalConditioning", "filledComponentSet", "FILLED_COMPONENTS");
$ChichewaCA-MOR->add_edge_by_id("filledComponentSet", "component1", "FILLED_COMPONENT");
$ChichewaCA-MOR->add_edge_by_id("component1", "elastic1", "ELASTICITY");
$ChichewaCA-MOR->add_edge_by_id("elastic1", "MINIMUM0-1", "MINIMUM");
$ChichewaCA-MOR->add_edge_by_id("elastic1", "MAXIMUM1-1", "MAXIMUM");
$ChichewaCA-MOR->add_edge_by_id("component1", "stable1", "STABILITY");
$ChichewaCA-MOR->add_edge_by_id("component1", "filled1", "FILLEDNESS");
$ChichewaCA-MOR->add_edge_by_id("filled1", "canonicalLineate1", "FORM");
$ChichewaCA-MOR->add_edge_by_id("filledComponentSet", "component2", "FILLED_COMPONENT");
$ChichewaCA-MOR->add_edge_by_id("component2", "stable2", "STABILITY");
$ChichewaCA-MOR->add_edge_by_id("component2", "filled2", "FILLEDNESS");
$ChichewaCA-MOR->add_edge_by_id("filled2", "canonicalLineate2", "FORM");
$ChichewaCA-MOR->add_edge_by_id("component2", "elastic2", "ELASTICITY");
$ChichewaCA-MOR->add_edge_by_id("elastic2", "MAXIMUM1-2", "MAXIMUM");
$ChichewaCA-MOR->add_edge_by_id("elastic2", "MINIMUM0-2", "MINIMUM");
$ChichewaCA-MOR->add_edge_by_id("lexicoconstructionalConditioning", "templateMultiple", "FILLER_POSITION");
$ChichewaCA-MOR->add_edge_by_id("desmeme", "arch", "FOUNDATION");
$ChichewaCA-MOR->add_edge_by_id("arch", "component2", "RIGHT_SUPPORT");
$ChichewaCA-MOR->add_edge_by_id("arch", "component1", "RIGHT_VOUSSOIR");
$ChichewaCA-MOR->add_edge_by_id("arch", "component3", "KEYSTONE");
$ChichewaCA-MOR->add_edge_by_id("component3", "inelastic1", "ELASTICITY");
$ChichewaCA-MOR->add_edge_by_id("inelastic1", "COUNT1-1", "COUNT");
$ChichewaCA-MOR->add_edge_by_id("component3", "open1", "FILLEDNESS");
$ChichewaCA-MOR->add_edge_by_id("open1", "coherent1", "COHERENCE");
$ChichewaCA-MOR->add_edge_by_id("component3", "stable3", "STABILITY");
$ChichewaCA-MOR->add_edge_by_id("arch", "component3", "LEFT_SUPPORT");
$ChichewaCA-MOR->add_edge_by_id("arch", "component4", "LEFT_VOUSSOIR");
$ChichewaCA-MOR->add_edge_by_id("component4", "null1", "FILLEDNESS");
$ChichewaCA-MOR->add_edge_by_id("component4", "inelastic2", "ELASTICITY");
$ChichewaCA-MOR->add_edge_by_id("inelastic2", "COUNT0-1", "COUNT");
$ChichewaCA-MOR->add_edge_by_id("component4", "stable4", "STABILITY");
$ChichewaCA-MOR->add_edge_by_id("desmeme", "order", "STRICTURE");
$ChichewaCA-MOR->add_edge_by_id("order", "simple", "RELATIONS");
$ChichewaCA-MOR->add_edge_by_id("order", "COUNT3-1", "COUNT");
$ChichewaCA-MOR->add_edge_by_id("order", "morphologicalConstituent", "CONSTITUENT");
$ChichewaCA-MOR->add_edge_by_id("desmeme", "notViolable", "VIOLABILITY");
$templateGraphs{ChichewaCA-MOR} = $ChichewaCA-MOR;

my $ChichewaMacroStem-PhMOR = Graph->new(multiedged => 1);
$ChichewaMacroStem-PhMOR->set_graph_attribute("name", "ChichewaMacroStem-PhMOR");
$ChichewaMacroStem-PhMOR->add_edge_by_id("desmeme", "notViolable", "VIOLABILITY");
$ChichewaMacroStem-PhMOR->add_edge_by_id("desmeme", "constructionalConditioning", "CONDITIONING");
$ChichewaMacroStem-PhMOR->add_edge_by_id("desmeme", "span", "FOUNDATION");
$ChichewaMacroStem-PhMOR->add_edge_by_id("span", "component1", "LEFT_SUPPORT");
$ChichewaMacroStem-PhMOR->add_edge_by_id("component1", "unstable1", "STABILITY");
$ChichewaMacroStem-PhMOR->add_edge_by_id("unstable1", "right", "ASSOCIATE_POSITION");
$ChichewaMacroStem-PhMOR->add_edge_by_id("unstable1", "component2", "ASSOCIATE");
$ChichewaMacroStem-PhMOR->add_edge_by_id("component2", "open1", "FILLEDNESS");
$ChichewaMacroStem-PhMOR->add_edge_by_id("open1", "coherent1", "COHERENCE");
$ChichewaMacroStem-PhMOR->add_edge_by_id("component2", "stable1", "STABILITY");
$ChichewaMacroStem-PhMOR->add_edge_by_id("component2", "inelastic1", "ELASTICITY");
$ChichewaMacroStem-PhMOR->add_edge_by_id("inelastic1", "COUNT1-1", "COUNT");
$ChichewaMacroStem-PhMOR->add_edge_by_id("component1", "open2", "FILLEDNESS");
$ChichewaMacroStem-PhMOR->add_edge_by_id("open2", "coherent2", "COHERENCE");
$ChichewaMacroStem-PhMOR->add_edge_by_id("component1", "elastic1", "ELASTICITY");
$ChichewaMacroStem-PhMOR->add_edge_by_id("elastic1", "MAXIMUM1-1", "MAXIMUM");
$ChichewaMacroStem-PhMOR->add_edge_by_id("elastic1", "MINIMUM0-1", "MINIMUM");
$ChichewaMacroStem-PhMOR->add_edge_by_id("span", "component2", "RIGHT_SUPPORT");
$ChichewaMacroStem-PhMOR->add_edge_by_id("desmeme", "order", "STRICTURE");
$ChichewaMacroStem-PhMOR->add_edge_by_id("order", "COUNT2-1", "COUNT");
$ChichewaMacroStem-PhMOR->add_edge_by_id("order", "morphologicalConstituent", "CONSTITUENT");
$ChichewaMacroStem-PhMOR->add_edge_by_id("order", "simple", "RELATIONS");
$templateGraphs{ChichewaMacroStem-PhMOR} = $ChichewaMacroStem-PhMOR;

my $ChichewaVerb-MOR = Graph->new(multiedged => 1);
$ChichewaVerb-MOR->set_graph_attribute("name", "ChichewaVerb-MOR");
$ChichewaVerb-MOR->add_edge_by_id("desmeme", "constructionalConditioning", "CONDITIONING");
$ChichewaVerb-MOR->add_edge_by_id("desmeme", "order", "STRICTURE");
$ChichewaVerb-MOR->add_edge_by_id("order", "COUNT7-1", "COUNT");
$ChichewaVerb-MOR->add_edge_by_id("order", "morphosyntacticConstituent", "CONSTITUENT");
$ChichewaVerb-MOR->add_edge_by_id("order", "simple", "RELATIONS");
$ChichewaVerb-MOR->add_edge_by_id("desmeme", "notViolable", "VIOLABILITY");
$ChichewaVerb-MOR->add_edge_by_id("desmeme", "arch", "FOUNDATION");
$ChichewaVerb-MOR->add_edge_by_id("arch", "component1", "LEFT_VOUSSOIR");
$ChichewaVerb-MOR->add_edge_by_id("component1", "elastic1", "ELASTICITY");
$ChichewaVerb-MOR->add_edge_by_id("elastic1", "MINIMUM0-1", "MINIMUM");
$ChichewaVerb-MOR->add_edge_by_id("elastic1", "MAXIMUM1-1", "MAXIMUM");
$ChichewaVerb-MOR->add_edge_by_id("component1", "open1", "FILLEDNESS");
$ChichewaVerb-MOR->add_edge_by_id("open1", "coherent1", "COHERENCE");
$ChichewaVerb-MOR->add_edge_by_id("component1", "stable1", "STABILITY");
$ChichewaVerb-MOR->add_edge_by_id("arch", "component2", "RIGHT_VOUSSOIR");
$ChichewaVerb-MOR->add_edge_by_id("component2", "null1", "FILLEDNESS");
$ChichewaVerb-MOR->add_edge_by_id("component2", "stable2", "STABILITY");
$ChichewaVerb-MOR->add_edge_by_id("component2", "inelastic1", "ELASTICITY");
$ChichewaVerb-MOR->add_edge_by_id("inelastic1", "COUNT0-1", "COUNT");
$ChichewaVerb-MOR->add_edge_by_id("arch", "component3", "RIGHT_SUPPORT");
$ChichewaVerb-MOR->add_edge_by_id("component3", "inelastic2", "ELASTICITY");
$ChichewaVerb-MOR->add_edge_by_id("inelastic2", "COUNT1-1", "COUNT");
$ChichewaVerb-MOR->add_edge_by_id("component3", "open2", "FILLEDNESS");
$ChichewaVerb-MOR->add_edge_by_id("open2", "coherent2", "COHERENCE");
$ChichewaVerb-MOR->add_edge_by_id("component3", "stable3", "STABILITY");
$ChichewaVerb-MOR->add_edge_by_id("arch", "component4", "LEFT_SUPPORT");
$ChichewaVerb-MOR->add_edge_by_id("component4", "elastic2", "ELASTICITY");
$ChichewaVerb-MOR->add_edge_by_id("elastic2", "MAXIMUM1-2", "MAXIMUM");
$ChichewaVerb-MOR->add_edge_by_id("elastic2", "MINIMUM0-2", "MINIMUM");
$ChichewaVerb-MOR->add_edge_by_id("component4", "filled1", "FILLEDNESS");
$ChichewaVerb-MOR->add_edge_by_id("filled1", "canonicalLineate1", "FORM");
$ChichewaVerb-MOR->add_edge_by_id("component4", "stable4", "STABILITY");
$ChichewaVerb-MOR->add_edge_by_id("arch", "component3", "KEYSTONE");
$ChichewaVerb-MOR->add_edge_by_id("arch", "restkomponentenSet", "RESTKOMPONENTEN");
$ChichewaVerb-MOR->add_edge_by_id("restkomponentenSet", "component5", "RESTKOMPONENTE");
$ChichewaVerb-MOR->add_edge_by_id("component5", "stable5", "STABILITY");
$ChichewaVerb-MOR->add_edge_by_id("component5", "elastic3", "ELASTICITY");
$ChichewaVerb-MOR->add_edge_by_id("elastic3", "MINIMUM0-3", "MINIMUM");
$ChichewaVerb-MOR->add_edge_by_id("elastic3", "MAXIMUM1-3", "MAXIMUM");
$ChichewaVerb-MOR->add_edge_by_id("component5", "open3", "FILLEDNESS");
$ChichewaVerb-MOR->add_edge_by_id("open3", "coherent3", "COHERENCE");
$ChichewaVerb-MOR->add_edge_by_id("restkomponentenSet", "component6", "RESTKOMPONENTE");
$ChichewaVerb-MOR->add_edge_by_id("component6", "open4", "FILLEDNESS");
$ChichewaVerb-MOR->add_edge_by_id("open4", "coherent4", "COHERENCE");
$ChichewaVerb-MOR->add_edge_by_id("component6", "inelastic3", "ELASTICITY");
$ChichewaVerb-MOR->add_edge_by_id("inelastic3", "COUNT1-2", "COUNT");
$ChichewaVerb-MOR->add_edge_by_id("component6", "stable6", "STABILITY");
$ChichewaVerb-MOR->add_edge_by_id("restkomponentenSet", "component7", "RESTKOMPONENTE");
$ChichewaVerb-MOR->add_edge_by_id("component7", "elastic4", "ELASTICITY");
$ChichewaVerb-MOR->add_edge_by_id("elastic4", "MAXIMUM1-4", "MAXIMUM");
$ChichewaVerb-MOR->add_edge_by_id("elastic4", "MINIMUM0-4", "MINIMUM");
$ChichewaVerb-MOR->add_edge_by_id("component7", "filled2", "FILLEDNESS");
$ChichewaVerb-MOR->add_edge_by_id("filled2", "canonicalLineate2", "FORM");
$ChichewaVerb-MOR->add_edge_by_id("component7", "stable7", "STABILITY");
$ChichewaVerb-MOR->add_edge_by_id("restkomponentenSet", "component8", "RESTKOMPONENTE");
$ChichewaVerb-MOR->add_edge_by_id("component8", "elastic5", "ELASTICITY");
$ChichewaVerb-MOR->add_edge_by_id("elastic5", "MINIMUM0-5", "MINIMUM");
$ChichewaVerb-MOR->add_edge_by_id("elastic5", "MAXIMUM1-5", "MAXIMUM");
$ChichewaVerb-MOR->add_edge_by_id("component8", "open5", "FILLEDNESS");
$ChichewaVerb-MOR->add_edge_by_id("open5", "coherent5", "COHERENCE");
$ChichewaVerb-MOR->add_edge_by_id("component8", "stable8", "STABILITY");
$templateGraphs{ChichewaVerb-MOR} = $ChichewaVerb-MOR;

my $ChichewaNP-SYN = Graph->new(multiedged => 1);
$ChichewaNP-SYN->set_graph_attribute("name", "ChichewaNP-SYN");
$ChichewaNP-SYN->add_edge_by_id("desmeme", "potentiallyViolable", "VIOLABILITY");
$ChichewaNP-SYN->add_edge_by_id("potentiallyViolable", "pragmatic", "EXCEPTIONALITY");
$ChichewaNP-SYN->add_edge_by_id("potentiallyViolable", "surfaceViolable", "REPARABILITY");
$ChichewaNP-SYN->add_edge_by_id("desmeme", "constructionalConditioning", "CONDITIONING");
$ChichewaNP-SYN->add_edge_by_id("desmeme", "order", "STRICTURE");
$ChichewaNP-SYN->add_edge_by_id("order", "COUNT4-1", "COUNT");
$ChichewaNP-SYN->add_edge_by_id("order", "simple", "RELATIONS");
$ChichewaNP-SYN->add_edge_by_id("order", "syntacticConstituent", "CONSTITUENT");
$ChichewaNP-SYN->add_edge_by_id("desmeme", "arch", "FOUNDATION");
$ChichewaNP-SYN->add_edge_by_id("arch", "component1", "RIGHT_VOUSSOIR");
$ChichewaNP-SYN->add_edge_by_id("component1", "elastic1", "ELASTICITY");
$ChichewaNP-SYN->add_edge_by_id("elastic1", "MINIMUM0-1", "MINIMUM");
$ChichewaNP-SYN->add_edge_by_id("elastic1", "MAXIMUM1-1", "MAXIMUM");
$ChichewaNP-SYN->add_edge_by_id("component1", "open1", "FILLEDNESS");
$ChichewaNP-SYN->add_edge_by_id("open1", "coherent1", "COHERENCE");
$ChichewaNP-SYN->add_edge_by_id("arch", "component2", "LEFT_SUPPORT");
$ChichewaNP-SYN->add_edge_by_id("component2", "open2", "FILLEDNESS");
$ChichewaNP-SYN->add_edge_by_id("open2", "coherent2", "COHERENCE");
$ChichewaNP-SYN->add_edge_by_id("component2", "inelastic1", "ELASTICITY");
$ChichewaNP-SYN->add_edge_by_id("inelastic1", "COUNT1-1", "COUNT");
$ChichewaNP-SYN->add_edge_by_id("component2", "stable1", "STABILITY");
$ChichewaNP-SYN->add_edge_by_id("arch", "component3", "RIGHT_SUPPORT");
$ChichewaNP-SYN->add_edge_by_id("component3", "elastic2", "ELASTICITY");
$ChichewaNP-SYN->add_edge_by_id("elastic2", "MINIMUM0-2", "MINIMUM");
$ChichewaNP-SYN->add_edge_by_id("elastic2", "MAXIMUM1-2", "MAXIMUM");
$ChichewaNP-SYN->add_edge_by_id("component3", "stable2", "STABILITY");
$ChichewaNP-SYN->add_edge_by_id("component3", "open3", "FILLEDNESS");
$ChichewaNP-SYN->add_edge_by_id("open3", "coherent3", "COHERENCE");
$ChichewaNP-SYN->add_edge_by_id("arch", "restkomponentenSet", "RESTKOMPONENTEN");
$ChichewaNP-SYN->add_edge_by_id("restkomponentenSet", "component4", "RESTKOMPONENTE");
$ChichewaNP-SYN->add_edge_by_id("component4", "elastic3", "ELASTICITY");
$ChichewaNP-SYN->add_edge_by_id("elastic3", "MAXIMUM100-1", "MAXIMUM");
$ChichewaNP-SYN->add_edge_by_id("elastic3", "MINIMUM0-3", "MINIMUM");
$ChichewaNP-SYN->add_edge_by_id("component4", "open4", "FILLEDNESS");
$ChichewaNP-SYN->add_edge_by_id("open4", "incoherent1", "COHERENCE");
$ChichewaNP-SYN->add_edge_by_id("component4", "stable3", "STABILITY");
$ChichewaNP-SYN->add_edge_by_id("arch", "component2", "KEYSTONE");
$ChichewaNP-SYN->add_edge_by_id("arch", "component5", "LEFT_VOUSSOIR");
$ChichewaNP-SYN->add_edge_by_id("component5", "stable4", "STABILITY");
$ChichewaNP-SYN->add_edge_by_id("component5", "inelastic2", "ELASTICITY");
$ChichewaNP-SYN->add_edge_by_id("inelastic2", "COUNT0-1", "COUNT");
$ChichewaNP-SYN->add_edge_by_id("component5", "null1", "FILLEDNESS");
$templateGraphs{ChichewaNP-SYN} = $ChichewaNP-SYN;

my $ChichewaNominalReduplicant-PhMOR = Graph->new(multiedged => 1);
$ChichewaNominalReduplicant-PhMOR->set_graph_attribute("name", "ChichewaNominalReduplicant-PhMOR");
$ChichewaNominalReduplicant-PhMOR->add_edge_by_id("desmeme", "span", "FOUNDATION");
$ChichewaNominalReduplicant-PhMOR->add_edge_by_id("span", "component1", "RIGHT_SUPPORT");
$ChichewaNominalReduplicant-PhMOR->add_edge_by_id("component1", "open1", "FILLEDNESS");
$ChichewaNominalReduplicant-PhMOR->add_edge_by_id("open1", "coherent1", "COHERENCE");
$ChichewaNominalReduplicant-PhMOR->add_edge_by_id("component1", "stable1", "STABILITY");
$ChichewaNominalReduplicant-PhMOR->add_edge_by_id("component1", "inelastic1", "ELASTICITY");
$ChichewaNominalReduplicant-PhMOR->add_edge_by_id("inelastic1", "COUNT1-1", "COUNT");
$ChichewaNominalReduplicant-PhMOR->add_edge_by_id("span", "component2", "LEFT_SUPPORT");
$ChichewaNominalReduplicant-PhMOR->add_edge_by_id("component2", "open2", "FILLEDNESS");
$ChichewaNominalReduplicant-PhMOR->add_edge_by_id("open2", "coherent2", "COHERENCE");
$ChichewaNominalReduplicant-PhMOR->add_edge_by_id("component2", "inelastic2", "ELASTICITY");
$ChichewaNominalReduplicant-PhMOR->add_edge_by_id("inelastic2", "COUNT1-2", "COUNT");
$ChichewaNominalReduplicant-PhMOR->add_edge_by_id("component2", "stable2", "STABILITY");
$ChichewaNominalReduplicant-PhMOR->add_edge_by_id("desmeme", "notViolable", "VIOLABILITY");
$ChichewaNominalReduplicant-PhMOR->add_edge_by_id("desmeme", "prosodicConditioning", "CONDITIONING");
$ChichewaNominalReduplicant-PhMOR->add_edge_by_id("desmeme", "length", "STRICTURE");
$ChichewaNominalReduplicant-PhMOR->add_edge_by_id("length", "COUNT2-1", "COUNT");
$ChichewaNominalReduplicant-PhMOR->add_edge_by_id("length", "Syllable", "CONSTITUENT");
$templateGraphs{ChichewaNominalReduplicant-PhMOR} = $ChichewaNominalReduplicant-PhMOR;

my $ChacoboBPVerbTrans_7-9 = Graph->new(multiedged => 1);
$ChacoboBPVerbTrans_7-9->set_graph_attribute("name", "ChacoboBPVerbTrans_7-9");
$ChacoboBPVerbTrans_7-9->add_edge_by_id("desmeme", "order", "STRICTURE");
$ChacoboBPVerbTrans_7-9->add_edge_by_id("order", "morphologicalConstituent", "CONSTITUENT");
$ChacoboBPVerbTrans_7-9->add_edge_by_id("order", "COUNT3-1", "COUNT");
$ChacoboBPVerbTrans_7-9->add_edge_by_id("order", "simple", "RELATIONS");
$ChacoboBPVerbTrans_7-9->add_edge_by_id("desmeme", "arch", "FOUNDATION");
$ChacoboBPVerbTrans_7-9->add_edge_by_id("arch", "component1", "RIGHT_VOUSSOIR");
$ChacoboBPVerbTrans_7-9->add_edge_by_id("component1", "unstable1", "STABILITY");
$ChacoboBPVerbTrans_7-9->add_edge_by_id("unstable1", "component2", "ASSOCIATE");
$ChacoboBPVerbTrans_7-9->add_edge_by_id("component2", "stable1", "STABILITY");
$ChacoboBPVerbTrans_7-9->add_edge_by_id("component2", "elastic1", "ELASTICITY");
$ChacoboBPVerbTrans_7-9->add_edge_by_id("elastic1", "MINIMUM0-1", "MINIMUM");
$ChacoboBPVerbTrans_7-9->add_edge_by_id("elastic1", "MAXIMUM1-1", "MAXIMUM");
$ChacoboBPVerbTrans_7-9->add_edge_by_id("component2", "open1", "FILLEDNESS");
$ChacoboBPVerbTrans_7-9->add_edge_by_id("open1", "coherent1", "COHERENCE");
$ChacoboBPVerbTrans_7-9->add_edge_by_id("unstable1", "left", "ASSOCIATE_POSITION");
$ChacoboBPVerbTrans_7-9->add_edge_by_id("component1", "open2", "FILLEDNESS");
$ChacoboBPVerbTrans_7-9->add_edge_by_id("open2", "coherent2", "COHERENCE");
$ChacoboBPVerbTrans_7-9->add_edge_by_id("component1", "elastic2", "ELASTICITY");
$ChacoboBPVerbTrans_7-9->add_edge_by_id("elastic2", "MINIMUM0-2", "MINIMUM");
$ChacoboBPVerbTrans_7-9->add_edge_by_id("elastic2", "MAXIMUM1-2", "MAXIMUM");
$ChacoboBPVerbTrans_7-9->add_edge_by_id("arch", "component2", "LEFT_SUPPORT");
$ChacoboBPVerbTrans_7-9->add_edge_by_id("arch", "component2", "LEFT_VOUSSOIR");
$ChacoboBPVerbTrans_7-9->add_edge_by_id("arch", "component3", "KEYSTONE");
$ChacoboBPVerbTrans_7-9->add_edge_by_id("component3", "inelastic1", "ELASTICITY");
$ChacoboBPVerbTrans_7-9->add_edge_by_id("inelastic1", "COUNT1-1", "COUNT");
$ChacoboBPVerbTrans_7-9->add_edge_by_id("component3", "open3", "FILLEDNESS");
$ChacoboBPVerbTrans_7-9->add_edge_by_id("open3", "coherent3", "COHERENCE");
$ChacoboBPVerbTrans_7-9->add_edge_by_id("component3", "stable2", "STABILITY");
$ChacoboBPVerbTrans_7-9->add_edge_by_id("arch", "component1", "RIGHT_SUPPORT");
$ChacoboBPVerbTrans_7-9->add_edge_by_id("desmeme", "notViolable", "VIOLABILITY");
$ChacoboBPVerbTrans_7-9->add_edge_by_id("desmeme", "constructionalConditioning", "CONDITIONING");
$templateGraphs{ChacoboBPVerbTrans_7-9} = $ChacoboBPVerbTrans_7-9;

my $ChichewaRMC-MOR = Graph->new(multiedged => 1);
$ChichewaRMC-MOR->set_graph_attribute("name", "ChichewaRMC-MOR");
$ChichewaRMC-MOR->add_edge_by_id("desmeme", "order", "STRICTURE");
$ChichewaRMC-MOR->add_edge_by_id("order", "COUNT2-1", "COUNT");
$ChichewaRMC-MOR->add_edge_by_id("order", "simple", "RELATIONS");
$ChichewaRMC-MOR->add_edge_by_id("order", "morphologicalConstituent", "CONSTITUENT");
$ChichewaRMC-MOR->add_edge_by_id("desmeme", "notViolable", "VIOLABILITY");
$ChichewaRMC-MOR->add_edge_by_id("desmeme", "span", "FOUNDATION");
$ChichewaRMC-MOR->add_edge_by_id("span", "component1", "LEFT_SUPPORT");
$ChichewaRMC-MOR->add_edge_by_id("component1", "inelastic1", "ELASTICITY");
$ChichewaRMC-MOR->add_edge_by_id("inelastic1", "COUNT1-1", "COUNT");
$ChichewaRMC-MOR->add_edge_by_id("component1", "open1", "FILLEDNESS");
$ChichewaRMC-MOR->add_edge_by_id("open1", "coherent1", "COHERENCE");
$ChichewaRMC-MOR->add_edge_by_id("component1", "unstable1", "STABILITY");
$ChichewaRMC-MOR->add_edge_by_id("unstable1", "component2", "ASSOCIATE");
$ChichewaRMC-MOR->add_edge_by_id("component2", "unstable2", "STABILITY");
$ChichewaRMC-MOR->add_edge_by_id("unstable2", "left", "ASSOCIATE_POSITION");
$ChichewaRMC-MOR->add_edge_by_id("unstable2", "component1", "ASSOCIATE");
$ChichewaRMC-MOR->add_edge_by_id("component2", "open2", "FILLEDNESS");
$ChichewaRMC-MOR->add_edge_by_id("open2", "coherent2", "COHERENCE");
$ChichewaRMC-MOR->add_edge_by_id("component2", "inelastic2", "ELASTICITY");
$ChichewaRMC-MOR->add_edge_by_id("inelastic2", "COUNT1-2", "COUNT");
$ChichewaRMC-MOR->add_edge_by_id("unstable1", "right", "ASSOCIATE_POSITION");
$ChichewaRMC-MOR->add_edge_by_id("span", "component2", "RIGHT_SUPPORT");
$ChichewaRMC-MOR->add_edge_by_id("desmeme", "constructionalConditioning", "CONDITIONING");
$templateGraphs{ChichewaRMC-MOR} = $ChichewaRMC-MOR;

my $ChichewaNDem-PhSYN = Graph->new(multiedged => 1);
$ChichewaNDem-PhSYN->set_graph_attribute("name", "ChichewaNDem-PhSYN");
$ChichewaNDem-PhSYN->add_edge_by_id("desmeme", "span", "FOUNDATION");
$ChichewaNDem-PhSYN->add_edge_by_id("span", "component1", "LEFT_SUPPORT");
$ChichewaNDem-PhSYN->add_edge_by_id("component1", "open1", "FILLEDNESS");
$ChichewaNDem-PhSYN->add_edge_by_id("open1", "coherent1", "COHERENCE");
$ChichewaNDem-PhSYN->add_edge_by_id("component1", "inelastic1", "ELASTICITY");
$ChichewaNDem-PhSYN->add_edge_by_id("inelastic1", "COUNT1-1", "COUNT");
$ChichewaNDem-PhSYN->add_edge_by_id("component1", "stable1", "STABILITY");
$ChichewaNDem-PhSYN->add_edge_by_id("span", "component2", "RIGHT_SUPPORT");
$ChichewaNDem-PhSYN->add_edge_by_id("component2", "open2", "FILLEDNESS");
$ChichewaNDem-PhSYN->add_edge_by_id("open2", "coherent2", "COHERENCE");
$ChichewaNDem-PhSYN->add_edge_by_id("component2", "elastic1", "ELASTICITY");
$ChichewaNDem-PhSYN->add_edge_by_id("elastic1", "MINIMUM0-1", "MINIMUM");
$ChichewaNDem-PhSYN->add_edge_by_id("elastic1", "MAXIMUM1-1", "MAXIMUM");
$ChichewaNDem-PhSYN->add_edge_by_id("component2", "stable2", "STABILITY");
$ChichewaNDem-PhSYN->add_edge_by_id("desmeme", "constructionalConditioning", "CONDITIONING");
$ChichewaNDem-PhSYN->add_edge_by_id("desmeme", "order", "STRICTURE");
$ChichewaNDem-PhSYN->add_edge_by_id("order", "simple", "RELATIONS");
$ChichewaNDem-PhSYN->add_edge_by_id("order", "COUNT2-1", "COUNT");
$ChichewaNDem-PhSYN->add_edge_by_id("order", "syntacticConstituent", "CONSTITUENT");
$ChichewaNDem-PhSYN->add_edge_by_id("desmeme", "potentiallyViolable", "VIOLABILITY");
$ChichewaNDem-PhSYN->add_edge_by_id("potentiallyViolable", "morphosyntactic", "EXCEPTIONALITY");
$ChichewaNDem-PhSYN->add_edge_by_id("potentiallyViolable", "surfaceViolable", "REPARABILITY");
$templateGraphs{ChichewaNDem-PhSYN} = $ChichewaNDem-PhSYN;

my $ChichewaVerbWord-PhMOR = Graph->new(multiedged => 1);
$ChichewaVerbWord-PhMOR->set_graph_attribute("name", "ChichewaVerbWord-PhMOR");
$ChichewaVerbWord-PhMOR->add_edge_by_id("desmeme", "order", "STRICTURE");
$ChichewaVerbWord-PhMOR->add_edge_by_id("order", "simple", "RELATIONS");
$ChichewaVerbWord-PhMOR->add_edge_by_id("order", "COUNT2-1", "COUNT");
$ChichewaVerbWord-PhMOR->add_edge_by_id("order", "morphologicalConstituent", "CONSTITUENT");
$ChichewaVerbWord-PhMOR->add_edge_by_id("desmeme", "span", "FOUNDATION");
$ChichewaVerbWord-PhMOR->add_edge_by_id("span", "component1", "RIGHT_SUPPORT");
$ChichewaVerbWord-PhMOR->add_edge_by_id("component1", "filled1", "FILLEDNESS");
$ChichewaVerbWord-PhMOR->add_edge_by_id("filled1", "embeddedDesmeme", "FORM");
$ChichewaVerbWord-PhMOR->add_edge_by_id("component1", "stable1", "STABILITY");
$ChichewaVerbWord-PhMOR->add_edge_by_id("component1", "inelastic1", "ELASTICITY");
$ChichewaVerbWord-PhMOR->add_edge_by_id("inelastic1", "COUNT1-1", "COUNT");
$ChichewaVerbWord-PhMOR->add_edge_by_id("span", "component2", "LEFT_SUPPORT");
$ChichewaVerbWord-PhMOR->add_edge_by_id("component2", "open1", "FILLEDNESS");
$ChichewaVerbWord-PhMOR->add_edge_by_id("open1", "incoherent1", "COHERENCE");
$ChichewaVerbWord-PhMOR->add_edge_by_id("component2", "unstable1", "STABILITY");
$ChichewaVerbWord-PhMOR->add_edge_by_id("unstable1", "component1", "ASSOCIATE");
$ChichewaVerbWord-PhMOR->add_edge_by_id("unstable1", "right", "ASSOCIATE_POSITION");
$ChichewaVerbWord-PhMOR->add_edge_by_id("component2", "elastic1", "ELASTICITY");
$ChichewaVerbWord-PhMOR->add_edge_by_id("elastic1", "MINIMUM0-1", "MINIMUM");
$ChichewaVerbWord-PhMOR->add_edge_by_id("elastic1", "MAXIMUM100-1", "MAXIMUM");
$ChichewaVerbWord-PhMOR->add_edge_by_id("desmeme", "constructionalConditioning", "CONDITIONING");
$ChichewaVerbWord-PhMOR->add_edge_by_id("desmeme", "notViolable", "VIOLABILITY");
$templateGraphs{ChichewaVerbWord-PhMOR} = $ChichewaVerbWord-PhMOR;

my $ChichewaAssociative-SYN = Graph->new(multiedged => 1);
$ChichewaAssociative-SYN->set_graph_attribute("name", "ChichewaAssociative-SYN");
$ChichewaAssociative-SYN->add_edge_by_id("desmeme", "notViolable", "VIOLABILITY");
$ChichewaAssociative-SYN->add_edge_by_id("desmeme", "lexicoconstructionalConditioning", "CONDITIONING");
$ChichewaAssociative-SYN->add_edge_by_id("desmeme", "span", "FOUNDATION");
$ChichewaAssociative-SYN->add_edge_by_id("span", "component1", "LEFT_SUPPORT");
$ChichewaAssociative-SYN->add_edge_by_id("component1", "elastic1", "ELASTICITY");
$ChichewaAssociative-SYN->add_edge_by_id("elastic1", "MAXIMUM1-1", "MAXIMUM");
$ChichewaAssociative-SYN->add_edge_by_id("elastic1", "MINIMUM0-1", "MINIMUM");
$ChichewaAssociative-SYN->add_edge_by_id("component1", "stable1", "STABILITY");
$ChichewaAssociative-SYN->add_edge_by_id("component1", "open1", "FILLEDNESS");
$ChichewaAssociative-SYN->add_edge_by_id("open1", "coherent1", "COHERENCE");
$ChichewaAssociative-SYN->add_edge_by_id("span", "component2", "RIGHT_SUPPORT");
$ChichewaAssociative-SYN->add_edge_by_id("component2", "inelastic1", "ELASTICITY");
$ChichewaAssociative-SYN->add_edge_by_id("inelastic1", "COUNT1-1", "COUNT");
$ChichewaAssociative-SYN->add_edge_by_id("component2", "open2", "FILLEDNESS");
$ChichewaAssociative-SYN->add_edge_by_id("open2", "coherent2", "COHERENCE");
$ChichewaAssociative-SYN->add_edge_by_id("component2", "stable2", "STABILITY");
$ChichewaAssociative-SYN->add_edge_by_id("span", "restkomponentenSet", "RESTKOMPONENTEN");
$ChichewaAssociative-SYN->add_edge_by_id("restkomponentenSet", "component3", "RESTKOMPONENTE");
$ChichewaAssociative-SYN->add_edge_by_id("component3", "inelastic2", "ELASTICITY");
$ChichewaAssociative-SYN->add_edge_by_id("inelastic2", "COUNT1-2", "COUNT");
$ChichewaAssociative-SYN->add_edge_by_id("component3", "partiallyFilled1", "FILLEDNESS");
$ChichewaAssociative-SYN->add_edge_by_id("partiallyFilled1", "coherent3", "COHERENCE");
$ChichewaAssociative-SYN->add_edge_by_id("partiallyFilled1", "componentFinal", "FILLER_PLACEMENT");
$ChichewaAssociative-SYN->add_edge_by_id("partiallyFilled1", "embeddedDesmeme", "FORM");
$ChichewaAssociative-SYN->add_edge_by_id("component3", "unstable1", "STABILITY");
$ChichewaAssociative-SYN->add_edge_by_id("unstable1", "component2", "ASSOCIATE");
$ChichewaAssociative-SYN->add_edge_by_id("unstable1", "right", "ASSOCIATE_POSITION");
$ChichewaAssociative-SYN->add_edge_by_id("desmeme", "order", "STRICTURE");
$ChichewaAssociative-SYN->add_edge_by_id("order", "simple", "RELATIONS");
$ChichewaAssociative-SYN->add_edge_by_id("order", "COUNT3-1", "COUNT");
$ChichewaAssociative-SYN->add_edge_by_id("order", "syntacticConstituent", "CONSTITUENT");
$templateGraphs{ChichewaAssociative-SYN} = $ChichewaAssociative-SYN;

my $ChichewaCompoundStem-PHON = Graph->new(multiedged => 1);
$ChichewaCompoundStem-PHON->set_graph_attribute("name", "ChichewaCompoundStem-PHON");
$ChichewaCompoundStem-PHON->add_edge_by_id("desmeme", "order", "STRICTURE");
$ChichewaCompoundStem-PHON->add_edge_by_id("order", "COUNT2-1", "COUNT");
$ChichewaCompoundStem-PHON->add_edge_by_id("order", "morphologicalConstituent", "CONSTITUENT");
$ChichewaCompoundStem-PHON->add_edge_by_id("order", "simple", "RELATIONS");
$ChichewaCompoundStem-PHON->add_edge_by_id("desmeme", "constructionalConditioning", "CONDITIONING");
$ChichewaCompoundStem-PHON->add_edge_by_id("desmeme", "notViolable", "VIOLABILITY");
$ChichewaCompoundStem-PHON->add_edge_by_id("desmeme", "span", "FOUNDATION");
$ChichewaCompoundStem-PHON->add_edge_by_id("span", "component1", "RIGHT_SUPPORT");
$ChichewaCompoundStem-PHON->add_edge_by_id("component1", "filled1", "FILLEDNESS");
$ChichewaCompoundStem-PHON->add_edge_by_id("filled1", "embeddedDesmeme", "FORM");
$ChichewaCompoundStem-PHON->add_edge_by_id("component1", "inelastic1", "ELASTICITY");
$ChichewaCompoundStem-PHON->add_edge_by_id("inelastic1", "COUNT1-1", "COUNT");
$ChichewaCompoundStem-PHON->add_edge_by_id("component1", "stable1", "STABILITY");
$ChichewaCompoundStem-PHON->add_edge_by_id("span", "component2", "LEFT_SUPPORT");
$ChichewaCompoundStem-PHON->add_edge_by_id("component2", "unstable1", "STABILITY");
$ChichewaCompoundStem-PHON->add_edge_by_id("unstable1", "right", "ASSOCIATE_POSITION");
$ChichewaCompoundStem-PHON->add_edge_by_id("unstable1", "component1", "ASSOCIATE");
$ChichewaCompoundStem-PHON->add_edge_by_id("component2", "filled2", "FILLEDNESS");
$ChichewaCompoundStem-PHON->add_edge_by_id("filled2", "reduplicant", "FORM");
$ChichewaCompoundStem-PHON->add_edge_by_id("component2", "elastic1", "ELASTICITY");
$ChichewaCompoundStem-PHON->add_edge_by_id("elastic1", "MAXIMUM1-1", "MAXIMUM");
$ChichewaCompoundStem-PHON->add_edge_by_id("elastic1", "MINIMUM0-1", "MINIMUM");
$templateGraphs{ChichewaCompoundStem-PHON} = $ChichewaCompoundStem-PHON;

my $ChichewaCleft-SYN = Graph->new(multiedged => 1);
$ChichewaCleft-SYN->set_graph_attribute("name", "ChichewaCleft-SYN");
$ChichewaCleft-SYN->add_edge_by_id("desmeme", "constructionalConditioning", "CONDITIONING");
$ChichewaCleft-SYN->add_edge_by_id("desmeme", "order", "STRICTURE");
$ChichewaCleft-SYN->add_edge_by_id("order", "COUNT3-1", "COUNT");
$ChichewaCleft-SYN->add_edge_by_id("order", "simple", "RELATIONS");
$ChichewaCleft-SYN->add_edge_by_id("order", "syntacticConstituent", "CONSTITUENT");
$ChichewaCleft-SYN->add_edge_by_id("desmeme", "notViolable", "VIOLABILITY");
$ChichewaCleft-SYN->add_edge_by_id("desmeme", "span", "FOUNDATION");
$ChichewaCleft-SYN->add_edge_by_id("span", "component1", "LEFT_SUPPORT");
$ChichewaCleft-SYN->add_edge_by_id("component1", "inelastic1", "ELASTICITY");
$ChichewaCleft-SYN->add_edge_by_id("inelastic1", "COUNT1-1", "COUNT");
$ChichewaCleft-SYN->add_edge_by_id("component1", "filled1", "FILLEDNESS");
$ChichewaCleft-SYN->add_edge_by_id("filled1", "canonicalLineate1", "FORM");
$ChichewaCleft-SYN->add_edge_by_id("component1", "stable1", "STABILITY");
$ChichewaCleft-SYN->add_edge_by_id("span", "restkomponentenSet", "RESTKOMPONENTEN");
$ChichewaCleft-SYN->add_edge_by_id("restkomponentenSet", "component2", "RESTKOMPONENTE");
$ChichewaCleft-SYN->add_edge_by_id("component2", "stable2", "STABILITY");
$ChichewaCleft-SYN->add_edge_by_id("component2", "open1", "FILLEDNESS");
$ChichewaCleft-SYN->add_edge_by_id("open1", "coherent1", "COHERENCE");
$ChichewaCleft-SYN->add_edge_by_id("component2", "inelastic2", "ELASTICITY");
$ChichewaCleft-SYN->add_edge_by_id("inelastic2", "COUNT1-2", "COUNT");
$ChichewaCleft-SYN->add_edge_by_id("span", "component3", "RIGHT_SUPPORT");
$ChichewaCleft-SYN->add_edge_by_id("component3", "inelastic3", "ELASTICITY");
$ChichewaCleft-SYN->add_edge_by_id("inelastic3", "COUNT1-3", "COUNT");
$ChichewaCleft-SYN->add_edge_by_id("component3", "filled2", "FILLEDNESS");
$ChichewaCleft-SYN->add_edge_by_id("filled2", "embeddedDesmeme", "FORM");
$ChichewaCleft-SYN->add_edge_by_id("component3", "stable3", "STABILITY");
$templateGraphs{ChichewaCleft-SYN} = $ChichewaCleft-SYN;

my @templates = ("ChacoboBPVerbTrans_7-9", "ChacoboGlottalStop_7-8", "ChichewaAR-MOR", "ChichewaAssociative-SYN", "ChichewaCA-MOR", "ChichewaCP-MOR", "ChichewaCleft-SYN", "ChichewaComplementClause-SYN", "ChichewaCompoundStem-PHON", "ChichewaDerivationalStem-PhMOR", "ChichewaImperative-MOR", "ChichewaKodi-SYN", "ChichewaLocative-CLT", "ChichewaMacroStem-PhMOR", "ChichewaNDem-PhSYN", "ChichewaNP-SYN", "ChichewaNeg1Verb-PhMOR", "ChichewaNiEnclitic-CLT", "ChichewaNominalReduplicant-PhMOR", "ChichewaNominalReduplication-PhMOR", "ChichewaNoun-MOR", "ChichewaORelative-CLT", "ChichewaOsaVerb-MOR", "ChichewaPhrase-PhSYN", "ChichewaRMC-MOR", "ChichewaRelativeClause-SYN", "ChichewaSTAMP-PhMOR", "ChichewaSyllable-PHON", "ChichewaVOX-SYN", "ChichewaVerb-MOR", "ChichewaVerbStem-PhMOR", "ChichewaVerbWithImperatives-MOR", "ChichewaVerbWord-PhMOR", "ChichewaVowelHarmony-PhMOR", "ChichewaWordMinimality-PhMOR");
my @templatesCopy = @templates;

open (NULL, '>FloodingSimilarities.txt');  #Erase file
my %seenPairs = { };
for my $templateName1 (@templates) {

	for my $templateName2 (@templatesCopy) {

		if ($seenPairs{$templateName2."/".$templateName1}) { print next; }

		# Initialize simList for calculating Euclidean distances.
		my $initialS = new GraphJG::SimilarityJG(graph => [$templateGraphs{$templateName1}, $templateGraphs{$templateName2}]);
		my $initialMethod = $initialS->use('SimilarityFlooding');
		$initialMethod->setNumOfIteration(1);
		$initialMethod->calculate();
		my %simList = $initialMethod->getAllSimilarities;
	
		print "$templateName1/$templateName2\n";

		# Keep incrementing the iteration until we reach Euclidean distance of less than or equal to .05. Start at 2 to get difference from initial condition.
		for (my $count = 2; $count <=100; $count++) {

			my $s = new GraphJG::SimilarityJG(graph => [$templateGraphs{$templateName1}, $templateGraphs{$templateName2}]);
			my $method = $s->use('SimilarityFlooding');
			$method->setNumOfIteration($count);
			$method->calculate();

			my %newSimList = $method->getAllSimilarities;

			my @dists;
			for my $v (keys(%simList)) {
				# This is messy: We run through the paired graph to see if this paired node is in any subgraph.
				# "Free-floating" nodes get ignored for the purposes of calculating the Euclidean distance.
				# Appears to not actually make a difference if epsilon is set to .05 since the residuals converge pretty quickly to nearly the same. This is because free-floating nodes rapidly get a score close to zero.
				my $pcg = $method->pcg;
				my @pairedvs = $pcg->vertices();
				for my $pairedv (@pairedvs) {
					if($v eq $pairedv) {
						my $oldSim = $simList{$v};
						my $newSim = $newSimList{$v};
						my $diff = $oldSim - $newSim;
						push(@dists,$diff);
						last;
						}
					}
				}
	
			my $eucSum;
			for my $dist (@dists) {	
				$eucSum += $dist*$dist;
				}
	
			my $eucDist = sqrt($eucSum);
			print "$count: $eucDist\n";
	
			if ($eucDist < .05) {
	 			$method->getLargeSimilarities($templateName1,$templateName2);
 				$seenPairs{$templateName1."/".$templateName2} = 1;
				last;
				}
	
			%simList = %newSimList;
	
			}
		}
	}
