"""
Regression tests for the similarity flooding algorithm.

Algorithm reference: Melnik et al. (2002) "Similarity Flooding: A Versatile
Graph Matching Algorithm and its Application to Schema Matching". This
project uses the JG variant: bidirectional PCG, propagation weight divided
by total outgoing neighbours (not just label-matching ones), 100 iterations,
normalised by max after each round.

Reference output: scripts/earlier/FloodingSimilarities.txt contains node-level
similarity scores generated by the Perl GraphJG implementation on an older
multi-language dataset (Aghem, Bantu, Chichewa, English, etc.). That file uses
graph structures from the old RDF pipeline, so it cannot be used directly as a
test oracle against the current TSV-based tdags. A future task (see issue #17)
is to generate a TSV-pipeline ground truth and add it here.

Test strategy:
  1. Mathematical guarantees — properties that must hold for any correct
     implementation regardless of data.
  2. Hand-computed example — a minimal graph pair whose flooding scores can
     be calculated step-by-step by hand to catch implementation errors.
  3. Structural ordering — template pairs that should rank higher/lower than
     each other; direction is verifiable without exact reference values.
"""

import os
import sys
import pytest

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

from tdag.tdag import tdag
from tdag.tabbed import get_tabbed_desmemes
from tdag.comparison import similarity_flooding, sf_distance

DESMEME_TSV    = os.path.join(ROOT, "data", "nya", "ChichewaDesmemes.tsv")
COMPONENT_TSV  = os.path.join(ROOT, "data", "nya", "ChichewaComponents.tsv")
DESMEME_SCHEMA = os.path.join(ROOT, "schema", "DesmemeSchema.tsv")
COMPONENT_SCHEMA = os.path.join(ROOT, "schema", "ComponentSchema.tsv")

TOLERANCE = 1e-6


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def load_desmemes(skip_components=True):
    return get_tabbed_desmemes(
        DESMEME_TSV, COMPONENT_TSV, DESMEME_SCHEMA, COMPONENT_SCHEMA,
        skip_components=skip_components,
        skip_md=True, skip_an=True, skip_ex=True,
    )


def minimal_tdag(name, nodes, edges):
    """Build a tdag by hand from a list of node names and (from, to, label) edges."""
    g = tdag(name)
    for n in nodes:
        g.core.add_node(n, attrs=[("label", n)])
    for (u, v, label) in edges:
        g.add_edge((u, v), label)
    return g


# ---------------------------------------------------------------------------
# 1. Mathematical guarantees
# ---------------------------------------------------------------------------

def test_sf_scores_in_range():
    """All node-pair similarity scores must be in [0, 1]."""
    desmemes = load_desmemes()
    g1 = next(d for d in desmemes if "AR-MOR" in d.name)
    g2 = next(d for d in desmemes if "Associative" in d.name)
    scores = similarity_flooding(g1, g2)
    for (v1, v2), score in scores.items():
        assert 0.0 <= score <= 1.0 + TOLERANCE, \
            f"Score out of range for ({v1}, {v2}): {score}"


def test_sf_self_comparison_max_is_one():
    """When a graph is compared to itself, the maximum score must be 1.0.

    Proof: after initialisation all same-name pairs have score 1.0. After
    propagation+normalisation the max is always divided out to 1.0.
    """
    desmemes = load_desmemes()
    g = next(d for d in desmemes if "AR-MOR" in d.name)
    scores = similarity_flooding(g, g)
    assert max(scores.values()) == pytest.approx(1.0, abs=TOLERANCE)


def test_sf_self_comparison_diagonal_highest():
    """For a self-comparison each node should be most similar to itself."""
    desmemes = load_desmemes()
    g = next(d for d in desmemes if "AR-MOR" in d.name)
    scores = similarity_flooding(g, g)
    nodes = list(g.core.nodes())
    for v in nodes:
        self_score = scores[(v, v)]
        for u in nodes:
            assert scores[(v, u)] <= self_score + TOLERANCE, \
                f"Node {v} more similar to {u} ({scores[(v,u)]:.4f}) than to itself ({self_score:.4f})"


def test_sf_distance_in_range():
    """sf_distance must be in [0, 1]."""
    desmemes = load_desmemes()
    g1 = next(d for d in desmemes if "AR-MOR" in d.name)
    g2 = next(d for d in desmemes if "Associative" in d.name)
    d = sf_distance(g1, g2)
    assert 0.0 <= d <= 1.0 + TOLERANCE


def test_sf_self_distance_minimal():
    """A template's distance from itself should be less than its distance from any other.

    Because flooding normalises by the per-iteration maximum, mean similarity
    for a self-comparison won't reach 1.0 (cross-type pairs pull the mean
    down), so sf_distance(g, g) > 0. But it should always be lower than the
    distance to a structurally dissimilar template.
    """
    desmemes = load_desmemes()
    g = next(d for d in desmemes if "AR-MOR" in d.name)
    other = next(d for d in desmemes if "Syllable" in d.name)
    assert sf_distance(g, g) < sf_distance(g, other)


# ---------------------------------------------------------------------------
# 2. Hand-computed example
# ---------------------------------------------------------------------------

def test_sf_minimal_identical_graphs():
    """Two identical 2-node graphs: verified by hand.

    Structure: root -> child (via EDGE), both G1 and G2 identical.

    Initialisation (labels match everywhere since graphs are identical):
      sim(root, root) = 1.0   sim(child, child) = 1.0
      sim(root, child) = 0.5  sim(child, root) = 0.5

    PCG: root/root <-> child/child (bidirectional, via EDGE label)
         No PCG edges for cross pairs root/child or child/root.

    Iteration 1 (outgoing counts: root/root=1, child/child=1):
      next(root,root)   = 1.0 + sim(child,child)/1 = 2.0
      next(child,child) = 1.0 + sim(root,root)/1   = 2.0
      next(root,child)  = 0.5 + 0                  = 0.5   (no PCG neighbours)
      next(child,root)  = 0.5 + 0                  = 0.5
      max = 2.0  ->  sim(root,root)=1.0, sim(child,child)=1.0,
                     sim(root,child)=0.25, sim(child,root)=0.25

    After convergence (cross pairs have no PCG connections so shrink each
    round; after k rounds sim(root,child) = 0.5 / 2^k):
      sim(root,root) = 1.0  sim(child,child) = 1.0
      sim(root,child) -> 0  sim(child,root) -> 0
    """
    g1 = minimal_tdag("G1", ["root", "child"], [("root", "child", "EDGE")])
    g2 = minimal_tdag("G2", ["root", "child"], [("root", "child", "EDGE")])

    scores = similarity_flooding(g1, g2, iterations=100)

    assert scores[("root", "root")]   == pytest.approx(1.0, abs=TOLERANCE)
    assert scores[("child", "child")] == pytest.approx(1.0, abs=TOLERANCE)
    # Cross pairs converge toward 0; after 100 iterations they are negligible
    assert scores[("root", "child")]  < 0.01
    assert scores[("child", "root")]  < 0.01


def test_sf_minimal_single_node_graphs():
    """Two single-node graphs with matching labels: similarity should be 1.0."""
    g1 = minimal_tdag("G1", ["desmeme"], [])
    g2 = minimal_tdag("G2", ["desmeme"], [])
    scores = similarity_flooding(g1, g2)
    assert scores[("desmeme", "desmeme")] == pytest.approx(1.0, abs=TOLERANCE)


def test_sf_minimal_mismatched_labels():
    """Two single-node graphs with different labels initialise to mismatch_init.

    With iterations=0 we get the raw initial matrix before any propagation
    or normalisation (normalisation would divide 0.5 by max=0.5, giving 1.0,
    which is correct algorithm behaviour but not what this test is checking).
    """
    g1 = minimal_tdag("G1", ["arch"], [])
    g2 = minimal_tdag("G2", ["span"], [])
    scores = similarity_flooding(g1, g2, iterations=0)
    assert scores[("arch", "span")] == pytest.approx(0.5, abs=TOLERANCE)


# ---------------------------------------------------------------------------
# 3. Structural ordering
# ---------------------------------------------------------------------------

def test_sf_similar_pair_beats_dissimilar():
    """Two arch-foundation desmemes should score more similar than arch vs span.

    ChichewaAR-MOR and ChichewaCA-MOR: both arch, both lexicoconstructional.
    ChichewaAR-MOR and ChichewaAssociative-SYN: arch vs span, different conditioning.
    """
    desmemes = load_desmemes()
    by_name = {d.name: d for d in desmemes}
    ar  = by_name["ChichewaAR-MOR"]
    ca  = by_name["ChichewaCA-MOR"]
    assoc = by_name["ChichewaAssociative-SYN"]

    d_similar    = sf_distance(ar, ca)
    d_dissimilar = sf_distance(ar, assoc)

    assert d_similar < d_dissimilar, (
        f"Expected AR-MOR/CA-MOR ({d_similar:.4f}) < "
        f"AR-MOR/Associative-SYN ({d_dissimilar:.4f})"
    )


def test_sf_distance_symmetric_approx():
    """sf_distance(G1, G2) should approximately equal sf_distance(G2, G1).

    Similarity flooding is not strictly symmetric (PCG construction is
    symmetric but graph sizes may differ), so we allow a generous tolerance.
    """
    desmemes = load_desmemes()
    g1 = next(d for d in desmemes if "AR-MOR" in d.name)
    g2 = next(d for d in desmemes if "Syllable" in d.name)
    assert sf_distance(g1, g2) == pytest.approx(sf_distance(g2, g1), abs=0.05)
